import {textLabel,kindOf,relationOf,classify,layoutScene,projectPoint} from './model.js';
export const COLORS={'世界 / 类型':'#4e97bd','状态 / 事实':'#239f97','规则 / 谓词':'#8498cc','AST':'#a892ba','决策':'#5b8cbd','执行':'#52a6c2','事件 / 证据':'#80a589','其他 / 源类型':'#90a7b3'};
const short=(s,n=26)=>s.length>n?s.slice(0,n-1)+'…':s;
export class GraphRenderer {
  constructor(canvas,{onSelect=()=>{},onHover=()=>{},onDraw=()=>{}}={}) {
    this.canvas=canvas;this.ctx=canvas.getContext('2d');this.onSelect=onSelect;this.onHover=onHover;this.onDraw=onDraw;this.scene={nodes:[],edges:[]};this.positions=new Map();this.hitNodes=[];this.hitEdges=[];this.flat=false;this.labels=false;this.selected=null;this.hovered=null;this.camera={yaw:-.18,pitch:.12,panX:0,panY:0,zoom:1};this.drag=null;this.frame=null;this.destroyed=false;
    this.handlers={pointerdown:e=>this.pointerDown(e),pointermove:e=>this.pointerMove(e),pointerup:e=>this.pointerUp(e),pointercancel:()=>{this.drag=null},pointerleave:()=>{if(!this.drag){this.hovered=null;this.onHover(null);this.schedule()}},wheel:e=>this.wheel(e)};
    for(const [name,fn]of Object.entries(this.handlers))canvas.addEventListener(name,fn,name==='wheel'?{passive:false}:undefined);
    this.resizeObserver=typeof ResizeObserver==='function'?new ResizeObserver(()=>{this.resize();this.schedule()}):null;this.resizeObserver?.observe(canvas);this.resize();
  }
  resize(){const r=this.canvas.getBoundingClientRect();this.width=r.width||800;this.height=r.height||555;const ratio=Math.min(globalThis.devicePixelRatio||1,2);this.canvas.width=Math.round(this.width*ratio);this.canvas.height=Math.round(this.height*ratio);this.ctx?.setTransform(ratio,0,0,ratio,0,0);}
  setScene(scene,{fit=true}={}){this.scene=scene;this.positions=layoutScene(scene,this.flat);if(fit)this.fit();else this.schedule();}
  setMode(flat){this.flat=flat;this.camera.yaw=flat?0:-.18;this.camera.pitch=flat?0:.12;this.positions=layoutScene(this.scene,flat);this.fit();}
  setSelection(value){this.selected=value;this.schedule();}
  fit(){this.camera.panX=0;this.camera.panY=0;const ps=[...this.positions.values()];if(!ps.length){this.camera.zoom=1;this.schedule();return;}const xs=ps.map(p=>p.x),ys=ps.map(p=>p.y);const spanX=Math.max(...xs)-Math.min(...xs)+240,spanY=Math.max(...ys)-Math.min(...ys)+140;this.camera.zoom=Math.max(this.flat?.7:.04,Math.min(1.1,(this.width-80)/spanX,(this.height-80)/spanY));this.camera.panX=-(Math.max(...xs)+Math.min(...xs))/2*this.camera.zoom;this.camera.panY=-(Math.max(...ys)+Math.min(...ys))/2*this.camera.zoom;this.schedule();}
  zoom(factor){this.camera.zoom=Math.max(.025,Math.min(4,this.camera.zoom*factor));this.schedule();}
  schedule(){if(this.frame||this.destroyed)return;this.frame=requestAnimationFrame(()=>{this.frame=null;this.draw()});}
  local(e){const r=this.canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
  hit(x,y){for(let i=this.hitNodes.length-1;i>=0;i--){const h=this.hitNodes[i];if(Math.abs(x-h.x)<=h.w/2&&Math.abs(y-h.y)<=h.h/2)return{type:'node',id:h.id};}let best=null,dist=7;for(const h of this.hitEdges){const dx=h.b.x-h.a.x,dy=h.b.y-h.a.y,l=dx*dx+dy*dy,t=l?Math.max(0,Math.min(1,((x-h.a.x)*dx+(y-h.a.y)*dy)/l)):0,d=Math.hypot(x-h.a.x-t*dx,y-h.a.y-t*dy);if(d<dist){dist=d;best={type:'edge',id:h.id};}}return best;}
  pointerDown(e){if(e.button!==0)return;const p=this.local(e);this.drag={...p,startX:p.x,startY:p.y,moved:false,pan:e.shiftKey||this.flat};this.canvas.setPointerCapture?.(e.pointerId);}
  pointerMove(e){const p=this.local(e);if(this.drag){const dx=p.x-this.drag.x,dy=p.y-this.drag.y;this.drag.moved ||= Math.hypot(p.x-this.drag.startX,p.y-this.drag.startY)>4;if(this.drag.pan){this.camera.panX+=dx;this.camera.panY+=dy}else{this.camera.yaw+=dx*.006;this.camera.pitch=Math.max(-1.25,Math.min(1.25,this.camera.pitch+dy*.006))}this.drag.x=p.x;this.drag.y=p.y;this.onHover(null);this.schedule();return;}const hit=this.hit(p.x,p.y);this.hovered=hit;this.onHover(hit,p);this.canvas.style.cursor=hit?'pointer':this.flat?'grab':'move';this.schedule();}
  pointerUp(e){if(!this.drag)return;const click=!this.drag.moved;this.drag=null;this.canvas.releasePointerCapture?.(e.pointerId);if(click){const p=this.local(e);const hit=this.hit(p.x,p.y);if(hit)this.onSelect(hit);}}
  wheel(e){e.preventDefault();this.zoom(Math.exp(-e.deltaY*.001));}
  draw(){if(!this.ctx)return;const ctx=this.ctx,start=performance.now();ctx.clearRect(0,0,this.width,this.height);this.hitNodes=[];this.hitEdges=[];const projected=new Map();for(const [id,p]of this.positions)projected.set(id,projectPoint(p,this.camera,this.width,this.height));const selectedId=this.selected?.type==='node'?this.selected.id:null;const hoveredId=this.hovered?.type==='node'?this.hovered.id:null;let drawnEdges=0,labels=0;
    // Parallel relation strokes are separately offset; arrowheads retain declared source→target direction.
    const pairs=new Map();for(const e of this.scene.edges){const key=[e.source,e.target].sort().join('|');if(!pairs.has(key))pairs.set(key,[]);pairs.get(key).push(e.id);}
    for(const e of this.scene.edges){let a=projected.get(e.source),b=projected.get(e.target);if(!a||!b)continue;const ids=pairs.get([e.source,e.target].sort().join('|')),offset=(ids.indexOf(e.id)-(ids.length-1)/2)*7;const vx=b.x-a.x,vy=b.y-a.y,len=Math.hypot(vx,vy)||1,normalSign=e.source<e.target?1:-1,ox=-vy/len*offset*normalSign,oy=vx/len*offset*normalSign;a={x:a.x+ox,y:a.y+oy};b={x:b.x+ox,y:b.y+oy};const active=this.selected?.id===e.id||this.hovered?.id===e.id||e.source===selectedId||e.target===selectedId||e.source===hoveredId||e.target===hoveredId;ctx.strokeStyle=active?'#1886b1':'#b9d2dd';ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=active?1.8:1;ctx.globalAlpha=1;
      ctx.beginPath();if(e.source===e.target){const radius=18+ids.indexOf(e.id)*9;ctx.arc(a.x,a.y-radius,radius,.1,Math.PI*1.9);ctx.stroke();b={x:a.x+radius*.83,y:a.y-radius*.61};a={x:a.x+radius*1.22,y:a.y-radius*1.56};}else{ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}const angle=Math.atan2(b.y-a.y,b.x-a.x),t=Math.max(0,Math.min(1,(Math.hypot(b.x-a.x,b.y-a.y)-12)/Math.max(1,Math.hypot(b.x-a.x,b.y-a.y)))),ax=a.x+(b.x-a.x)*t,ay=a.y+(b.y-a.y)*t;ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(ax-7*Math.cos(angle-.4),ay-7*Math.sin(angle-.4));ctx.lineTo(ax-7*Math.cos(angle+.4),ay-7*Math.sin(angle+.4));ctx.closePath();ctx.fill();this.hitEdges.push({id:e.id,a,b});drawnEdges++;
      if(this.labels||active){const x=(a.x+b.x)/2,y=(a.y+b.y)/2-5,text=short(relationOf(e),35);ctx.font='11px system-ui';const w=ctx.measureText(text).width;ctx.fillStyle='#ffffffed';ctx.fillRect(x-w/2-3,y-11,w+6,15);ctx.fillStyle=active?'#1678a0':'#647f90';ctx.textAlign='center';ctx.fillText(text,x,y);labels++;}
    }
    const order=[...this.scene.nodes].sort((a,b)=>projected.get(b.id).depth-projected.get(a.id).depth);let nodeLabels=0,viewportNodes=0;const occupied=[];
    for(const n of order){const p=projected.get(n.id);if(p.x< -100||p.y< -40||p.x>this.width+100||p.y>this.height+40)continue;viewportNodes++;const color=COLORS[classify(n)],active=this.selected?.id===n.id||this.hovered?.id===n.id,canLabel=true;ctx.fillStyle=color;ctx.strokeStyle=active?'#0a719f':'#ffffff';ctx.lineWidth=active?3:2;ctx.beginPath();if(n.semantic_level==='definition'){ctx.rect(p.x-5,p.y-5,10,10)}else{ctx.arc(p.x,p.y,active?8:6,0,Math.PI*2)}ctx.fill();ctx.stroke();this.hitNodes.push({id:n.id,x:p.x,y:p.y,w:25,h:25});
      const text=short(textLabel(n.label)||n.id,active?44:24);ctx.font=active?'600 12px system-ui':'12px system-ui';const w=ctx.measureText(text).width+10,h=35,box={x:p.x+11,y:p.y-15,w,h};const collides=occupied.some(b=>box.x<b.x+b.w&&box.x+box.w>b.x&&box.y<b.y+b.h&&box.y+box.h>b.y);if(canLabel&&(!collides||active)){occupied.push(box);ctx.fillStyle=active?'#eaf6fbed':'#fffffff0';ctx.fillRect(box.x,box.y,w,h);ctx.fillStyle='#31566b';ctx.textAlign='left';ctx.fillText(text,box.x+5,p.y-1);ctx.font='10px system-ui';ctx.fillStyle='#6d8b99';ctx.fillText(short(kindOf(n),31),box.x+5,p.y+13);this.hitNodes.push({id:n.id,x:box.x+w/2,y:box.y+h/2,w,h});nodeLabels++;}
    }
    this.onDraw({viewportNodes,nodeLabels,edgeLabels:labels,drawnEdges,milliseconds:performance.now()-start});
  }
  destroy(){this.destroyed=true;this.resizeObserver?.disconnect();if(this.frame)cancelAnimationFrame(this.frame);for(const [name,fn]of Object.entries(this.handlers))this.canvas.removeEventListener(name,fn);}
}
