"""Module-level tests for the bounded selected-city no-fly violation detector.

The detector is a narrow pure domain component: strict lowering of the
current authoring zone shape into a canonical framed input, then
deterministic violation detection from caller-supplied authoritative position
samples. Tests here are real mathematical cases with positional and temporal
values chosen by hand; no sample is generated by the code under test.
"""

from __future__ import annotations

import math

import pytest
from pydantic import ValidationError

from aero_bench.tasks.logistics.airspace_events import (
    NO_FLY_FRAME,
    AuthoredNoFlyZone,
    NoFlyEventsReport,
    NoFlyZone,
    PositionSample,
    compile_no_fly_zone,
    compile_no_fly_zones,
    detect_no_fly_events,
)


def _square(half: float = 20.0) -> list[dict[str, float]]:
    return [
        {"x": -half, "z": -half},
        {"x": half, "z": -half},
        {"x": half, "z": half},
        {"x": -half, "z": half},
    ]


def _zone(
    *,
    zone_id: str = "nfz.1",
    name: str = "test-zone",
    polygon: object | None = None,
    floor: float = 0.0,
    ceiling: float = 50.0,
    starts: float = 0.0,
    ends: float | None = None,
) -> NoFlyZone:
    return NoFlyZone.model_validate(
        {
            "zone_id": zone_id,
            "name": name,
            "frame": NO_FLY_FRAME,
            "polygon": _square() if polygon is None else polygon,
            "floor_m": floor,
            "ceiling_m": ceiling,
            "starts_at_s": starts,
            "ends_at_s": ends,
            "source": {"kind": "manual", "label": "test", "uri": None},
        }
    )


def _sample(
    ref: str, time_s: float, x: float, y: float, z: float
) -> PositionSample:
    return PositionSample(
        sample_ref=ref, time_s=time_s, x=x, y=y, z=z
    )


def test_lowering_accepts_current_authoring_shape_and_attaches_frame() -> None:
    raw = {
        "id": "nfz.hospital",
        "name": "hospital",
        "polygon": [{"x": -50, "z": -50}, {"x": 50, "z": -50}, {"x": 50, "z": 50}, {"x": -50, "z": 50}],
        "floorM": 0,
        "ceilingM": 120,
        "startsAtS": 0,
        "endsAtS": None,
        "source": {"kind": "geojson", "label": "import", "uri": "asset://nfz"},
    }
    lowered = compile_no_fly_zone(raw)
    assert lowered.zone_id == "nfz.hospital"
    assert lowered.frame == NO_FLY_FRAME
    assert lowered.floor_m == 0.0
    assert lowered.ceiling_m == 120.0
    assert lowered.starts_at_s == 0.0
    assert lowered.ends_at_s is None
    assert lowered.source.kind == "geojson"
    assert len(lowered.polygon) == 4
    assert compile_no_fly_zones([raw])[0] == lowered


def test_lowering_rejects_duplicate_ids() -> None:
    raw = {
        "id": "nfz.dup",
        "name": "a",
        "polygon": _square(4),
        "floorM": 0,
        "ceilingM": 40,
        "startsAtS": 0,
        "endsAtS": None,
        "source": {"kind": "manual", "label": "test", "uri": None},
    }
    with pytest.raises(ValueError, match="unique"):
        compile_no_fly_zones([raw, {**raw, "polygon": _square(8)}])


def test_outside_outside_crossing_is_detected_without_tunneling() -> None:
    zone = _zone(zone_id="nfz.cross")
    samples = (
        _sample("s0", 0.0, -60.0, 10.0, 0.0),
        _sample("s1", 10.0, 60.0, 10.0, 0.0),
    )
    report = detect_no_fly_events(zone, samples, subject_id="aircraft.1")
    assert report.violation_count == 1
    event = report.violations[0]
    assert event.event_type == "observed_entry"
    assert event.start_basis == "interpolated_crossing"
    assert event.end_basis == "interpolated_crossing"
    assert event.start_inferred is True
    assert event.end_inferred is True
    assert event.bound_start_sample_ref == "s0"
    assert event.bound_end_sample_ref == "s1"
    # X=-20 -> X=+20 maps linearly onto the 10 s segment: [10/3, 20/3].
    assert event.start_time_s == pytest.approx(10.0 / 3.0)
    assert event.end_time_s == pytest.approx(20.0 / 3.0)
    assert report.interpolation_assumed is True
    assert report.body_clearance == "none"


def test_inactive_before_start_yields_no_violation_event() -> None:
    zone = _zone(zone_id="nfz.win", starts=10.0, ends=20.0)
    # Both segments lie entirely before the activation time; even a full
    # spatial crossing at t in [0, 5) cannot violate the inactive zone.
    samples = (
        _sample("s0", 0.0, -60.0, 10.0, 0.0),
        _sample("s1", 5.0, 60.0, 10.0, 0.0),
    )
    report = detect_no_fly_events(zone, samples, subject_id="aircraft.1")
    assert report.sample_count == 2
    assert report.violation_count == 0
    assert report.violations == ()


def test_expired_window_yields_no_violation_for_inside_samples() -> None:
    zone = _zone(zone_id="nfz.expired", starts=0.0, ends=10.0)
    samples = (
        _sample("s0", 12.0, 0.0, 10.0, 0.0),
        _sample("s1", 14.0, 0.0, 10.0, 0.0),
    )
    report = detect_no_fly_events(zone, samples, subject_id="aircraft.1")
    assert report.violation_count == 0


def test_vertical_entry_across_ceiling_and_floor() -> None:
    zone = _zone(zone_id="nfz.vertical", polygon=_square(10), floor=10.0, ceiling=20.0)
    samples = (
        _sample("s0", 0.0, 0.0, 30.0, 0.0),
        _sample("s1", 10.0, 0.0, 5.0, 0.0),
    )
    report = detect_no_fly_events(zone, samples, subject_id="aircraft.1")
    assert report.violation_count == 1
    event = report.violations[0]
    assert event.event_type == "observed_entry"
    assert event.start_basis == "interpolated_crossing"
    assert event.end_basis == "interpolated_crossing"
    # y(u) = 30 - 25u crosses 20 at u=0.4 and 10 at u=0.8.
    assert event.start_time_s == pytest.approx(4.0)
    assert event.end_time_s == pytest.approx(8.0)
    assert event.bound_start_sample_ref == "s0"
    assert event.bound_end_sample_ref == "s1"


def test_concave_polygon_multiple_entries_in_one_segment() -> None:
    concave = [
        {"x": -10, "z": -10}, {"x": 10, "z": -10}, {"x": 10, "z": 10},
        {"x": 5, "z": 10}, {"x": 5, "z": 0}, {"x": -5, "z": 0},
        {"x": -5, "z": 10}, {"x": -10, "z": 10},
    ]
    zone = _zone(zone_id="nfz.u", polygon=concave)
    samples = (
        _sample("s0", 0.0, -20.0, 10.0, 5.0),
        _sample("s1", 10.0, 20.0, 10.0, 5.0),
    )
    report = detect_no_fly_events(zone, samples, subject_id="aircraft.1")
    assert report.violation_count == 2
    left, right = report.violations
    assert left.event_type == "observed_entry"
    assert right.event_type == "observed_entry"
    assert left.start_basis == "interpolated_crossing"
    assert left.end_basis == "interpolated_crossing"
    assert left.start_time_s == pytest.approx(2.5)
    assert left.end_time_s == pytest.approx(3.75)
    assert right.start_time_s == pytest.approx(6.25)
    assert right.end_time_s == pytest.approx(7.5)
    assert left.bound_start_sample_ref == "s0"
    assert left.bound_end_sample_ref == "s1"
    assert right.bound_start_sample_ref == "s0"
    assert right.bound_end_sample_ref == "s1"
    assert len({event.event_id for event in report.violations}) == 2


def test_stationary_activation_while_inside_spatial_volume() -> None:
    zone = _zone(zone_id="nfz.activation", starts=10.0, ends=30.0)
    samples = (
        _sample("s0", 0.0, 0.0, 10.0, 0.0),
        _sample("s1", 20.0, 0.0, 10.0, 0.0),
        _sample("s2", 40.0, 0.0, 10.0, 0.0),
    )
    report = detect_no_fly_events(zone, samples, subject_id="aircraft.1")
    assert report.violation_count == 1
    event = report.violations[0]
    assert event.event_type == "stationary_activation"
    assert event.start_basis == "time_window_activation"
    assert event.end_basis == "time_window_expiry"
    assert event.start_time_s == 10.0
    assert event.end_time_s == 30.0
    assert event.start_inferred is False
    assert event.end_inferred is False
    assert event.bound_start_sample_ref == "s0"
    assert event.bound_end_sample_ref == "s2"


def test_initial_sample_inside_is_already_inside_not_observed_entry() -> None:
    zone = _zone(zone_id="nfz.init")
    samples = (
        _sample("s0", 0.0, 0.0, 10.0, 0.0),
        _sample("s1", 10.0, 0.0, 10.0, 0.0),
        _sample("s2", 12.0, 100.0, 10.0, 0.0),
    )
    report = detect_no_fly_events(zone, samples, subject_id="aircraft.1")
    assert report.violation_count == 1
    event = report.violations[0]
    assert event.event_type == "already_inside"
    assert event.start_basis == "initial_sample"
    assert event.start_inferred is False
    assert event.start_time_s == 0.0
    assert event.end_basis == "interpolated_crossing"
    assert event.end_inferred is True
    # Exit at x=+20 on the final segment (t=10 -> 12): u=0.2 -> 10.4 s.
    assert event.end_time_s == pytest.approx(10.4)
    assert event.bound_start_sample_ref == "s0"
    assert event.bound_end_sample_ref == "s2"


def test_half_open_window_sample_exactly_at_expiry_is_not_active() -> None:
    zone = _zone(zone_id="nfz.half", starts=0.0, ends=10.0)
    samples = (
        _sample("s0", 0.0, 0.0, 10.0, 0.0),
        _sample("s1", 10.0, 0.0, 10.0, 0.0),
    )
    report = detect_no_fly_events(zone, samples, subject_id="aircraft.1")
    assert report.violation_count == 1
    event = report.violations[0]
    assert event.end_basis == "time_window_expiry"
    assert event.end_time_s == 10.0
    assert event.end_inferred is False


def test_crossing_after_expiry_yields_no_violation() -> None:
    zone = _zone(zone_id="nfz.expired-cross", starts=0.0, ends=10.0)
    samples = (
        _sample("s0", 10.0, -60.0, 10.0, 0.0),
        _sample("s1", 20.0, 60.0, 10.0, 0.0),
    )
    report = detect_no_fly_events(zone, samples, subject_id="aircraft.1")
    assert report.violation_count == 0


def test_empty_sample_stream_is_deterministically_empty() -> None:
    zone = _zone(zone_id="nfz.empty")
    report = detect_no_fly_events(zone, (), subject_id="aircraft.1")
    assert isinstance(report, NoFlyEventsReport)
    assert report.sample_count == 0
    assert report.violation_count == 0


def test_single_sample_inside_active_is_already_inside() -> None:
    zone = _zone(zone_id="nfz.single")
    report = detect_no_fly_events(
        zone, (_sample("s0", 3.0, 0.0, 10.0, 0.0),), subject_id="aircraft.1"
    )
    assert report.violation_count == 1
    event = report.violations[0]
    assert event.event_type == "already_inside"
    assert event.start_basis == "initial_sample"
    assert event.end_basis == "stream_end"
    assert event.start_time_s == 3.0
    assert event.end_time_s == 3.0


def test_reversed_sample_times_are_rejected() -> None:
    zone = _zone(zone_id="nfz.reversed")
    with pytest.raises(ValueError, match="strictly increasing"):
        detect_no_fly_events(
            zone,
            (_sample("s0", 10.0, 0.0, 10.0, 0.0), _sample("s1", 0.0, 0.0, 10.0, 0.0)),
            subject_id="aircraft.1",
        )


def test_equal_sample_times_are_rejected() -> None:
    zone = _zone(zone_id="nfz.equal")
    with pytest.raises(ValueError, match="strictly increasing"):
        detect_no_fly_events(
            zone,
            (_sample("s0", 5.0, 0.0, 10.0, 0.0), _sample("s1", 5.0, 0.0, 10.0, 0.0)),
            subject_id="aircraft.1",
        )


def test_non_finite_sample_coordinates_are_rejected() -> None:
    with pytest.raises(ValidationError, match="finite"):
        _sample("s0", 0.0, math.nan, 10.0, 0.0)
    with pytest.raises(ValidationError, match="finite"):
        _sample("s1", math.inf, 0.0, 10.0, 0.0)


def test_non_finite_polygon_coordinates_are_rejected() -> None:
    with pytest.raises(ValidationError, match="finite"):
        _zone(polygon=[{"x": 0, "z": 0}, {"x": math.nan, "z": 0}, {"x": 0, "z": 1}])


def test_unknown_frame_is_rejected() -> None:
    zone = _zone(zone_id="nfz.frame")
    with pytest.raises(ValidationError):
        NoFlyZone.model_validate({**zone.model_dump(), "frame": "mars_frame"})


def test_self_intersecting_polygon_is_rejected() -> None:
    # A self-intersecting ring with non-zero swept area.
    crossing = [{"x": 0, "z": 0}, {"x": 4, "z": 6}, {"x": 4, "z": 0}, {"x": 0, "z": 2}]
    with pytest.raises(ValidationError, match="self-intersects"):
        _zone(zone_id="nfz.crossing", polygon=crossing)


def test_degenerate_polygons_are_rejected() -> None:
    with pytest.raises(ValidationError, match="at least three"):
        _zone(zone_id="nfz.two", polygon=[{"x": 0, "z": 0}, {"x": 1, "z": 0}])
    with pytest.raises(ValidationError, match="zero area"):
        _zone(
            zone_id="nfz.line",
            polygon=[{"x": 0, "z": 0}, {"x": 1, "z": 0}, {"x": 2, "z": 0}],
        )
    with pytest.raises(ValidationError, match="distinct"):
        _zone(
            zone_id="nfz.dup-vertex",
            polygon=[{"x": 0, "z": 0}, {"x": 0, "z": 0}, {"x": 1, "z": 1}],
        )


def test_closed_ring_is_normalized_to_open_ring() -> None:
    closed = _square(3) + [{"x": -3, "z": -3}]
    zone = _zone(zone_id="nfz.closed", polygon=closed)
    assert len(zone.polygon) == 4


def test_config_time_reversal_is_rejected() -> None:
    with pytest.raises(ValidationError, match="end time"):
        AuthoredNoFlyZone.model_validate(
            {
                "id": "nfz.t",
                "name": "t",
                "polygon": _square(3),
                "floorM": 0,
                "ceilingM": 40,
                "startsAtS": 10,
                "endsAtS": 5,
                "source": {"kind": "manual", "label": "test", "uri": None},
            }
        )


def test_config_height_reversal_is_rejected() -> None:
    with pytest.raises(ValidationError, match="ceiling"):
        _zone(zone_id="nfz.h", floor=20.0, ceiling=10.0)


def test_deterministic_event_ids_and_evidence_refs() -> None:
    zone = _zone(zone_id="nfz.det")
    samples = (
        _sample("a0", 0.0, -60.0, 10.0, 0.0),
        _sample("a1", 10.0, 60.0, 10.0, 0.0),
    )
    first = detect_no_fly_events(zone, samples, subject_id="aircraft.1")
    second = detect_no_fly_events(zone, samples, subject_id="aircraft.1")
    assert first == second
    for event in first.violations:
        assert len(event.event_id) == 64
        assert all(character in "0123456789abcdef" for character in event.event_id)
        assert event.bound_start_sample_ref in {"a0", "a1"}
        assert event.bound_end_sample_ref in {"a0", "a1"}
    ids = [event.event_id for event in first.violations]
    assert len(ids) == len(set(ids))


def test_detection_is_side_effect_free_pure_function() -> None:
    zone = _zone(zone_id="nfz.pure")
    samples = (
        _sample("s0", 0.0, -60.0, 10.0, 0.0),
        _sample("s1", 10.0, 60.0, 10.0, 0.0),
    )
    before_zone = zone.model_dump()
    before_samples = [sample.model_dump() for sample in samples]
    _ = detect_no_fly_events(zone, samples, subject_id="aircraft.1")
    assert zone.model_dump() == before_zone
    assert [sample.model_dump() for sample in samples] == before_samples


# ---------------------------------------------------------------- reviewer regressions
# Independent regressions for the boundary-touch and activation-naming defects
# found by the WorkBuddy review. Expectations are hand-computed with strict
# interior and half-open-window semantics; they do not reuse detection logic.


def test_boundary_touch_with_bounded_window_ends_at_touch_not_window_expiry() -> None:
    """B1: a measured sample exactly on the polygon edge ends the violation
    there even when the bounded window's scheduled expiry is much later."""
    zone = _zone(zone_id="nfz.reg-b1", starts=0.0, ends=100.0)
    samples = (
        _sample("s0", 0.0, -10.0, 10.0, 0.0),
        _sample("s1", 10.0, 20.0, 10.0, 0.0),  # exactly on the right edge x=20
        _sample("s2", 20.0, 60.0, 10.0, 0.0),  # clearly outside afterwards
    )
    report = detect_no_fly_events(zone, samples, subject_id="aircraft.1")
    assert report.violation_count == 1
    event = report.violations[0]
    # Strict interior makes the airframe leave the open volume at the measured
    # boundary sample (t=10), not at the scheduled window expiry (t=100).
    assert event.event_type == "already_inside"
    assert event.start_basis == "initial_sample"
    assert event.start_time_s == 0.0
    assert event.end_time_s == 10.0
    assert event.end_basis == "sample_boundary_touch"
    assert event.end_basis != "time_window_expiry"
    assert event.end_inferred is False
    assert event.bound_end_sample_ref == "s1"


def test_boundary_touch_unbounded_window_is_not_an_interpolated_crossing() -> None:
    """B2: the same measured boundary touch, unbounded window, must not be
    marked interpolated/inferred: the endpoint is the measured sample itself."""
    zone = _zone(zone_id="nfz.reg-b2")
    samples = (
        _sample("s0", 0.0, -10.0, 10.0, 0.0),
        _sample("s1", 10.0, 20.0, 10.0, 0.0),  # exactly on the right edge x=20
        _sample("s2", 20.0, 60.0, 10.0, 0.0),  # clearly outside afterwards
    )
    report = detect_no_fly_events(zone, samples, subject_id="aircraft.1")
    assert report.violation_count == 1
    event = report.violations[0]
    assert event.end_time_s == 10.0
    assert event.end_basis == "sample_boundary_touch"
    assert event.end_basis != "interpolated_crossing"
    assert event.end_inferred is False
    assert event.bound_end_sample_ref == "s1"


def test_boundary_touch_then_reentry_is_two_maximal_intervals() -> None:
    """B4 split: touching the boundary at a measured sample interrupts the open
    interior, so the re-entry afterwards is a distinct maximal interval."""
    zone = _zone(zone_id="nfz.reg-b4", starts=0.0, ends=100.0)
    samples = (
        _sample("s0", 0.0, -10.0, 10.0, 0.0),
        _sample("s1", 10.0, 20.0, 10.0, 0.0),  # exactly on the right edge x=20
        _sample("s2", 20.0, 10.0, 10.0, 0.0),  # inside again
    )
    report = detect_no_fly_events(zone, samples, subject_id="aircraft.1")
    assert report.violation_count == 2
    leaving, reentry = report.violations
    assert leaving.event_type == "already_inside"
    assert leaving.start_time_s == 0.0
    assert leaving.end_time_s == 10.0
    assert leaving.end_basis == "sample_boundary_touch"
    assert leaving.end_inferred is False
    assert leaving.bound_end_sample_ref == "s1"
    assert reentry.start_time_s == 10.0
    assert reentry.end_time_s == 20.0
    assert reentry.start_basis == "sample_endpoint"
    assert reentry.start_inferred is False
    assert reentry.end_basis == "stream_end"
    assert len({event.event_id for event in report.violations}) == 2


def test_window_activation_while_moving_is_not_stationary_activation() -> None:
    """B5: a moving airframe activated by the window is reported with the
    truthful activation cause, never a fabricated claim of hovering."""
    zone = _zone(zone_id="nfz.reg-b5-move", starts=10.0, ends=40.0)
    samples = (
        _sample("s0", 0.0, -60.0, 10.0, 0.0),
        _sample("s1", 8.0, 0.0, 10.0, 0.0),   # crosses in before activation
        _sample("s2", 30.0, 15.0, 10.0, 0.0),  # moving while active
    )
    report = detect_no_fly_events(zone, samples, subject_id="aircraft.1")
    assert report.violation_count == 1
    event = report.violations[0]
    assert event.event_type == "window_activation_inside"
    assert event.event_type != "stationary_activation"
    assert event.start_basis == "time_window_activation"
    assert event.start_time_s == 10.0
    assert event.start_inferred is False


def test_window_activation_while_hovering_is_stationary_activation() -> None:
    """B5 complement: samples at one position make the hover claim truthful and
    keep the stationary name."""
    zone = _zone(zone_id="nfz.reg-b5-hover", starts=10.0, ends=30.0)
    samples = (
        _sample("s0", 0.0, 0.0, 10.0, 0.0),
        _sample("s1", 20.0, 0.0, 10.0, 0.0),
        _sample("s2", 40.0, 0.0, 10.0, 0.0),
    )
    report = detect_no_fly_events(zone, samples, subject_id="aircraft.1")
    assert report.violation_count == 1
    event = report.violations[0]
    assert event.event_type == "stationary_activation"
    assert event.start_basis == "time_window_activation"
    assert event.start_time_s == 10.0
