import {SCHEMA,scalar,textLabel,kindOf,relationOf,scenariosOf,safeDataURL,makeIndex,queryNodes,chooseScene,factFields,classify} from './model.js';
import {GraphRenderer,COLORS} from './renderer.js';
const escapeHTML=value=>scalar(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number.isFinite(Number(n))?Number(n).toLocaleString('en-US'):'未提供';
const pretty=value=>JSON.stringify(value,null,2);
const rawBlock=(title,data,open=false)=>`<details${open?' open':''}><summary>${escapeHTML(title)}</summary><pre>${escapeHTML(pretty(data))}</pre></details>`;
const displayValue=value=>value===null?'null · 源记录显式空值':typeof value==='string'?value:pretty(value);
const levelNames={definition:'定义',configured_instance:'配置实例',runtime_record:'运行记录类型 · 不代表已执行',source_record:'源记录',configuration:'配置关系',runtime:'运行关系',cross_level:'跨层关系'};
export function createApp({document=globalThis.document,fetchImpl=globalThis.fetch.bind(globalThis),Renderer=GraphRenderer,manifestURL=new URL('../data/manifest.json',globalThis.location?.href||'http://localhost/ui/').href}={}) {
  const $=id=>document.getElementById(id),state={manifest:null,scenarios:[],loaded:[],index:makeIndex([]),searchIndex:[],searchReady:false,selected:null,focus:null,page:0,pageSize:40,scene:null,flat:false,loadToken:0,abort:null,relationPage:40,history:[],globalResults:false};
  let searchTimer;
  const setStatus=text=>{$('load-status').textContent=text};
  const showError=error=>{$('error').hidden=false;$('error').textContent=String(error?.message||error)};
  const clearError=()=>{$('error').hidden=true;$('error').textContent=''};
  const renderer=new Renderer($('graph'),{onSelect:hit=>hit.type==='node'?selectNode(hit.id):selectEdge(hit.id),onHover:(hit,point)=>showTooltip(hit,point),onDraw:stats=>{$('render-status').textContent=`视窗内 ${stats.viewportNodes??'—'} 节点 · ${stats.nodeLabels} 个节点标签 · ${stats.edgeLabels} 个边标签 · ${stats.milliseconds.toFixed(1)} ms / 绘制`;}});
  async function fetchJSON(path,signal){const url=safeDataURL(path,manifestURL);const response=await fetchImpl(url,{signal,credentials:'same-origin'});if(!response.ok)throw new Error(`读取失败 (${response.status}): ${new URL(url).pathname}`);return response.json();}
  function counts(){const c=state.manifest?.counts||state.manifest?.totals||{},n=c.nodes??c.node_count??c.after_canonical_nodes??c.canonical_nodes??c.total_nodes??c.unique_nodes,e=c.edges??c.edge_count??c.after_resolved_edges??c.canonical_edges??c.total_edges??c.unique_edges;return{n,e};}
  function renderScenarioOptions(){const selected=$('scenario').value,domain=$('domain').value,q=$('activity').value.toLowerCase().trim();const list=state.scenarios.filter(s=>(!domain||s.domain===domain)&&(!q||[s.id,s.label,s.activity,scalar(s)].join(' ').toLowerCase().includes(q)));$('scenario').innerHTML=list.map(s=>`<option value="${escapeHTML(s.id)}">${escapeHTML(s.label||s.id)} · ${escapeHTML(s.id)}</option>`).join('');if(list.some(s=>s.id===selected))$('scenario').value=selected;$('scenario-summary').textContent=`${list.length} / ${state.scenarios.length} 个场景符合目录过滤。图谱仍显示最近一次载入范围。`;}
  function fillOptions(id,entries,caption){const old=$(id).value;$(id).innerHTML=`<option value="">${caption}</option>`+[...entries].sort((a,b)=>a[0].localeCompare(b[0])).map(([key,count])=>`<option value="${escapeHTML(key)}">${escapeHTML(key)} (${fmt(count)})</option>`).join('');if([...entries].some(([key])=>key===old))$(id).value=old;}
  function updateFacets(){const types=new Map(),levels=new Map();for(const n of state.searchReady?state.searchIndex:state.index.nodes.values()){types.set(kindOf(n),(types.get(kindOf(n))||0)+1);levels.set(n.semantic_level||'unspecified',(levels.get(n.semantic_level||'unspecified')||0)+1);}fillOptions('type',types,state.searchReady?'所有全集类型':'所有已加载类型');fillOptions('level',levels,state.searchReady?'所有全集语义层':'所有已加载语义层');fillOptions('relation',state.index.relations,'所有原始关系');$('type-count').textContent=`· ${types.size} 种${state.searchReady?' / 全集':' / 已加载'}`;}
  function activeCaseIds(){return new Set(state.loaded.map(g=>g.scenario.id));}
  function filteredNodes(){let nodes=queryNodes(state.index,filters());const step=state.steps?.[Number($('step').value)];if($('step').value!==''&&step){const ids=new Set(step.node_ids||[]);nodes=nodes.filter(n=>ids.has(n.id));}return nodes;}
  function filters(){return{query:$('search').value,type:$('type').value,level:$('level').value,caseIds:activeCaseIds()};}
  function globalRows(){const q=$('search').value.trim().toLowerCase().split(/\s+/).filter(Boolean),type=$('type').value,level=$('level').value;return state.searchIndex.filter(n=>(!type||kindOf(n)===type)&&(!level||n.semantic_level===level)&&q.every(t=>n._search.includes(t)));}
  function renderResults(){const useGlobal=$('global-search').checked&&state.searchReady;state.globalResults=!!useGlobal;const rows=useGlobal?globalRows():filteredNodes();state.results=rows;const pages=Math.max(1,Math.ceil(rows.length/state.pageSize));state.page=Math.min(state.page,pages-1);$('results-count').textContent=`(${fmt(rows.length)})`;$('page-info').textContent=`${state.page+1} / ${pages}`;$('previous-page').disabled=state.page===0;$('next-page').disabled=state.page+1>=pages;$('results-scope').textContent=useGlobal?'跨全部已接受实例的索引结果。点击后载入对应源场景并定位；画布仍只显示已载入范围。':'当前载入范围的全部匹配实例；分页只限制列表渲染，不删除源数据。';
    const slice=rows.slice(state.page*state.pageSize,(state.page+1)*state.pageSize);$('results').innerHTML=slice.length?slice.map(n=>`<button class="result-row${state.selected?.id===n.id?' selected':''}" data-result="${escapeHTML(n.id)}"><span><span class="result-title">${escapeHTML(textLabel(n.label)||n.id)}</span><span class="result-id">${escapeHTML(n.id)}</span></span><span class="result-kind">${escapeHTML(kindOf(n))}<br>${escapeHTML(levelNames[n.semantic_level]||n.semantic_level||'语义层未提供')}</span></button>`).join(''):'<p class="muted">没有匹配记录。可清除类型或语义层过滤后重试。</p>';
  }
  function renderScene({fit=true}={}){const matches=filteredNodes();state.scene=chooseScene(state.index,{matches,focus:state.focus,hops:Number($('hops').value),limit:Number($('budget').value),edgeLimit:900,relation:$('relation').value,caseIds:activeCaseIds()});renderer.labels=$('edge-labels').checked;renderer.setScene(state.scene,{fit});renderer.setSelection(state.selected);$('empty-scene').hidden=state.scene.nodes.length>0;$('loaded-count').textContent=`${fmt(state.index.nodes.size)} 节点 · ${fmt(state.index.edges.size)} 边`;$('visible-count').textContent=`${state.scene.nodes.length} 节点 · ${state.scene.edges.length} 边`;
    const notes=[state.focus?`以选中实例为中心的 ${$('hops').value} 跳邻域`:'按类型轮流抽取的有界预览',`匹配 ${fmt(matches.length)} 个已加载节点`];if(state.scene.omittedNodes)notes.push(`${fmt(state.scene.omittedNodes)} 个候选节点因上限未绘制`);if(state.scene.omittedEdges)notes.push(`${fmt(state.scene.omittedEdges)} 条内部边因上限未绘制`);if(state.scene.boundaryEdges)notes.push(`${fmt(state.scene.boundaryEdges)} 条边通向画布外节点`);if(state.scene.focusOutsideFilter)notes.push('焦点不满足当前过滤，单独保留并标明');if(state.index.dangling.length)notes.push(`${fmt(state.index.dangling.length)} 条边存在未载入 / 缺失端点，未补造节点`);notes.push('图形布局不表示地理位置；标签为避让可暂隐，精确关系见详情');$('omissions').textContent=notes.join(' · ');
    $('legend').innerHTML=[...new Set(state.scene.nodes.map(classify))].map(g=>`<span><i class="group-${Object.keys(COLORS).indexOf(g)}"></i>${escapeHTML(g)}</span>`).join('');
  }
  function render(options){renderResults();renderScene(options);}
  async function loadCases(ids,{target=null,keepFilters=false}={}){const token=++state.loadToken;state.abort?.abort();const controller=new AbortController();state.abort=controller;clearError();$('cancel-load').hidden=false;const requested=ids.map(id=>state.scenarios.find(s=>s.id===id)).filter(Boolean),loaded=[];if(!requested.length){showError('所选范围没有可读取场景。');$('cancel-load').hidden=true;return false;}setStatus(`读取 ${requested.length} 个场景，0 / ${requested.length}…`);let cursor=0;
    try{await Promise.all(Array.from({length:Math.min(3,requested.length)},async()=>{while(cursor<requested.length){const scenario=requested[cursor++];if(!scenario.path)throw new Error(`场景 ${scenario.id} 未提供数据路径。`);const data=await fetchJSON(scenario.path,controller.signal);if(token!==state.loadToken)return;loaded.push({data,scenario});setStatus(`读取 ${requested.length} 个场景，${loaded.length} / ${requested.length}…`);}}));if(token!==state.loadToken)return false;
      state.loaded=loaded;state.index=makeIndex(loaded);state.selected=null;state.focus=null;state.page=0;state.history=[];state.steps=loaded.flatMap(g=>(g.data.steps||[]));$('step').innerHTML='<option value="">当前范围全部步骤</option>'+state.steps.map((step,i)=>`<option value="${i}">${escapeHTML(step.activity_name||'')} / ${escapeHTML(step.step_index)}. ${escapeHTML(step.source_step||step.imported_step||'未命名')}</option>`).join('');$('scenario-evidence').innerHTML=loaded.map(g=>rawBlock(g.scenario.label,{scenario:g.scenario,metadata:g.data.metadata,steps:g.data.steps,unsupported:g.data.unsupported})).join('');if(!keepFilters){$('type').value='';$('level').value='';$('relation').value='';$('search').value='';}updateFacets();const scope=requested.length===1?requested[0].label:`${requested.length} 个场景 · 聚合只读视图`;$('scene-title').textContent=scope;const c=counts();setStatus(`已载入 ${loaded.length} / ${state.scenarios.length} 个场景 · ${fmt(state.index.nodes.size)} 个独立 ID · ${fmt(state.index.edges.size)} 条关系。全集 ${fmt(c.n)} 节点 / ${fmt(c.e)} 边。`);render();renderDetail();if(target&&state.index.nodes.has(target))selectNode(target);else if(target)showError(`目标 ${target} 不在所载入场景中；没有替换或补造记录。`);return true;
    }catch(error){if(error.name==='AbortError'){if(token===state.loadToken)setStatus('载入已取消，保留上一次完整载入范围。');return false;}if(token===state.loadToken){controller.abort();showError(error);setStatus('载入失败，保留上一次完整载入范围。');}return false;}finally{if(token===state.loadToken){$('cancel-load').hidden=true;state.abort=null;}}
  }
  async function selectNode(id,{fromGlobal=false}={}){if(!state.index.nodes.has(id)){const entry=state.searchIndex.find(n=>n.id===id),cases=entry?.case_ids||entry?.cases||[];if(cases.length){await loadCases([typeof cases[0]==='object'?cases[0].id:cases[0]],{target:id,keepFilters:true});return;}showError(`该实例未在已载入范围或全局索引中找到：${id}`);return;}if(state.selected&&state.selected.id!==id)state.history.push(state.selected);state.selected={type:'node',id};state.focus=id;state.relationPage=40;render({fit:true});renderDetail();$('live').textContent=`已选中 ${textLabel(state.index.nodes.get(id).label)||id}`;}
  function selectEdge(id){if(!state.index.edges.has(id))return;if(state.selected&&state.selected.id!==id)state.history.push(state.selected);state.selected={type:'edge',id};renderer.setSelection(state.selected);renderDetail();$('live').textContent=`已选中关系 ${relationOf(state.index.edges.get(id))}`;}
  function kv(values){return'<dl class="kv">'+Object.entries(values).map(([k,v])=>`<dt>${escapeHTML(k)}</dt><dd>${escapeHTML(v===undefined?'未提供':displayValue(v))}</dd>`).join('')+'</dl>';}
  function sourceHTML(record){const sources=record.source_records||[];return `<h3>来源与原始引用 · ${sources.length}</h3>`+(sources.length?sources.map((s,i)=>rawBlock(`来源 ${i+1} · ${s.artifact||'artifact 未提供'} ${s.pointer||''}`,s)).join(''):'<p class="warning-note">此记录没有 source_records，无法验证原始字段位置。</p>')+rawBlock('provenance · 原样',record.provenance??null);}
  function astHTML(value,path='payload',depth=0){if(value===null||typeof value!=='object')return`<span class="ast-leaf">${escapeHTML(path)} = ${escapeHTML(JSON.stringify(value))}</span>`;const entries=Object.entries(value);return`<details class="ast-node"${depth<2?' open':''}><summary>${escapeHTML(path)} · ${Array.isArray(value)?`有序数组 [${entries.length}]`:`对象 {${entries.length}}`}</summary>${entries.map(([k,v])=>astHTML(v,Array.isArray(value)?`[${k}]`:k,depth+1)).join('')}</details>`;}
  function findAST(payload){const found=[];function walk(v,path,depth){if(depth>8||!v||typeof v!=='object')return;for(const [k,value]of Object.entries(v)){const next=`${path}.${k}`;if(/^(definition_ast|ast|ast_value|applicability_ast|expression|expression_ast|rule_ast)$/.test(k))found.push({path:next,value});else if(value&&typeof value==='object'&&!Array.isArray(value))walk(value,next,depth+1);}}walk(payload,'payload',0);return found;}
  function renderDetail(){$('back-selection').disabled=state.history.length===0;const selection=state.selected;if(!selection){$('detail').innerHTML='<h2>点击任一节点或关系</h2><p class="muted">实例索引可访问画布外所有已载入节点。查看关系详情后，可沿原始方向进入端点。</p>';return;}
    if(selection.type==='edge'){const e=state.index.edges.get(selection.id);$('detail').innerHTML=`<div class="tag-row"><span class="tag">有向关系</span><span class="tag">${escapeHTML(levelNames[e.semantic_level]||e.semantic_level||'层未提供')}</span></div><h2>${escapeHTML(relationOf(e))}</h2>${kv({'ID':e.id,'原始关系':e.raw_relation,'方向':'source → target','角色':e.role,'关系变体':e.contract_variant})}<div class="relation-other"><button data-node="${escapeHTML(e.source)}">${escapeHTML(e.source)}</button><span>→</span><button data-node="${escapeHTML(e.target)}">${escapeHTML(e.target)}</button></div>${rawBlock('完整原始关系字段 · 条件 / 角色 / 顺序',e.payload??e,true)}${sourceHTML(e)}${rawBlock('完整规范关系 JSON',e)}`;return;}
    const n=state.index.nodes.get(selection.id),fields=factFields(n),p=n.payload||{},incident=(state.index.adjacent.get(n.id)||[]).filter(e=>[...(state.index.edgeCases.get(e.id)||[])].some(id=>activeCaseIds().has(id))),asts=findAST(p),cases=[...(state.index.nodeCases.get(n.id)||[])];
    const expectationKeys=Object.keys(p).filter(k=>/expected|fixture|desired|target|actual|accept|truth|approval|receipt|missing|unknown|applicab|status/.test(k));for(const key of expectationKeys)if(!Object.hasOwn(fields,key))fields[key]=p[key];
    const semanticHTML=n.semantics?rawBlock('规范化语义投影 · 原始字段仍保留',n.semantics,true):'';
    const relationRows=incident.slice(0,state.relationPage).map(e=>{const outgoing=e.source===n.id,other=outgoing?e.target:e.source,otherN=state.index.nodes.get(other);return`<div class="relation-row"><button class="relation-label" data-edge="${escapeHTML(e.id)}">${outgoing?'→':'←'} ${escapeHTML(relationOf(e))}</button><p class="relation-role">role: ${escapeHTML(e.role??'未提供')} · ${escapeHTML(e.semantic_level||'层未提供')}</p><div class="relation-other"><button data-node="${escapeHTML(other)}">${escapeHTML(otherN?textLabel(otherN.label)||other:other+' · 端点缺失')}</button></div></div>`}).join('');
    $('detail').innerHTML=`<div class="tag-row"><span class="tag">${escapeHTML(kindOf(n))}</span><span class="tag">${escapeHTML(levelNames[n.semantic_level]||n.semantic_level||'语义层未提供')}</span></div><h2>${escapeHTML(textLabel(n.label)||n.id)}</h2>${kv({'ID':n.id,'原始 ID':n.original_id??p.id,'原始类型':n.raw_kind,'集合':n.source_collection,'AST 路径':p.ast_path,'场景':cases.join(', ')})}<div class="detail-actions"><button data-action="flat-focus">平面聚焦</button><button data-action="two-hop">展开 2 跳</button><button data-action="clear-focus">返回范围</button></div><div class="trace-chain"><span>状态 / 事实</span>→<span>规则 / AST</span>→<span>谓词</span>→<span>事件</span></div><p class="boundary-note">此阅读路径仅为导航提示。下方只列源数据实际存在的关系；没有直接关系时不会补画连接。</p><h3>值、单位、时间与状态</h3>${Object.keys(fields).length?kv(fields):'<p class="muted">此记录未提供可直接展示的 value / unit / time / truth 字段，完整原始字段见下方。</p>'}${semanticHTML}<h3>身份、别名与缺失</h3>${rawBlock('identity · 不对 generation / epoch 作类型转换',n.identity??{status:'未提供'},true)}${rawBlock('aliases · 仅展示源记录',n.aliases??p.aliases??{canonical_id:n.id,original_id:n.original_id??p.id,occurrence_ids:n.occurrence_ids??[],source_ids:(n.source_records||[]).map(s=>s.source_id)})}${asts.length?'<h3>源原生 AST · 保留对象、字面量和顺序</h3>'+asts.map(a=>astHTML(a.value,a.path)).join(''):'<p class="fine">此记录没有明确的 AST 字段。可沿关系进入规则 / 表达式节点，或检查完整原始记录。</p>'}<h3>真实相邻关系 · ${incident.length}</h3>${relationRows||'<p class="muted">当前已载入范围没有相邻关系。</p>'}${incident.length>state.relationPage?`<button data-action="more-relations">再显示 40 条 · 剩余 ${incident.length-state.relationPage}</button>`:''}${sourceHTML(n)}${rawBlock('完整原始记录 · 无字段省略',p)}${rawBlock('完整规范节点 JSON',n)}`;
  }
  function showTooltip(hit,point){const tip=$('tooltip');if(!hit){tip.hidden=true;return;}let html;if(hit.type==='node'){const n=state.index.nodes.get(hit.id);html=`<div class="kind">${escapeHTML(kindOf(n))} · ${escapeHTML(n.semantic_level)}</div><strong>${escapeHTML(textLabel(n.label)||n.id)}</strong><div>${escapeHTML(n.id)}</div><div>${state.index.adjacent.get(n.id)?.length||0} 条已载入相邻关系 · 点击查看值、单位、时间和来源</div>`;}else{const e=state.index.edges.get(hit.id);html=`<div class="kind">${escapeHTML(relationOf(e))}</div><strong>${escapeHTML(e.source)} → ${escapeHTML(e.target)}</strong><div>role: ${escapeHTML(e.role??'未提供')}</div>`;}tip.innerHTML=html;tip.hidden=false;const wrap=$('canvas-wrap');tip.style.left=`${Math.max(8,Math.min(point.x+14,wrap.clientWidth-tip.offsetWidth-8))}px`;tip.style.top=`${Math.max(8,Math.min(point.y+14,wrap.clientHeight-tip.offsetHeight-8))}px`;}
  async function renderCoverage(){const c=counts(),offlineNote=globalThis.p08OfflineData?'<p class="boundary-note">离线 HTML 包含完整规范图、别名和来源清单，用于查看与导出。原始输入文档快照及逐字节重建工具在配套私有源码 ZIP 中。</p>':'';$('coverage-content').innerHTML=offlineNote+`<p>已接受源目录的只读投影。结构通过、场景分支已写入、夹具检查通过，都不等于原生执行、领域验证或现实许可成立。</p><div class="summary-grid"><div><strong>${fmt(c.n)}</strong><span>全集规范节点</span></div><div><strong>${fmt(c.e)}</strong><span>全集关系</span></div><div><strong>${state.scenarios.length}</strong><span>可加载场景</span></div><div><strong>${state.index.dangling.length} / ${state.index.conflicts.length}</strong><span>已加载缺失端点 / ID 冲突</span></div></div>${rawBlock('完整清单 · 源目录与统计口径',state.manifest,true)}${rawBlock('已加载诊断 / unsupported / gaps',state.index.diagnostics)}${rawBlock('已加载 ID 冲突 · 未静默覆盖',state.index.conflicts)}${rawBlock('未解析端点关系 · 未补造节点',state.index.dangling)}<div id="coverage-extra"></div>`;if($('coverage-dialog').showModal)$('coverage-dialog').showModal();else $('coverage-dialog').setAttribute('open','');const files=state.manifest?.files||{};$('coverage-extra').innerHTML='<h3>完整数据文件</h3><div class="catalog-links">'+Object.entries(files).map(([key,path])=>`<a href="${escapeHTML(safeDataURL(path,manifestURL))}" download>${escapeHTML(key)} JSON</a>`).join('')+'</div>';$('coverage-extra').insertAdjacentHTML('beforeend','<h3>领域审查与测试设计</h3><p class="fine">设计场景与静态检查不等于已执行结果。城市模板分支、许可来源、专业验收和真实物理执行的未验证边界保留在审查记录中。</p><div class="catalog-links"><a href="../review/domain/VERDICT.md">领域审查结论</a><a href="../review/domain/coverage-ledger.json" download>35 项业务 / 20 项机器活动账本</a><a href="../review/domain/resolution-ledger.json" download>问题与保留缺口</a><a href="../review/domain/adversarial-scenarios.json" download>140 项未执行测试设计</a></div>');const extras=state.manifest?.coverage_files||[files.conflicts].filter(Boolean);for(const entry of extras){try{const path=typeof entry==='string'?entry:entry.path;if(!path)continue;const data=await fetchJSON(path);$('coverage-extra').insertAdjacentHTML('beforeend',rawBlock(path,data));}catch(error){$('coverage-extra').insertAdjacentHTML('beforeend',`<p class="warning-note">${escapeHTML(error.message)}</p>`);}}
  }
  async function loadSearch(){try{const entry=state.manifest.search_index||state.manifest.search_index_path||'search-index.json',data=await fetchJSON(typeof entry==='string'?entry:entry.path);const rows=Array.isArray(data)?data:data.nodes||data.entries||data.items||[];state.searchIndex=rows.map(n=>({...n,_search:[n.id,textLabel(n.label),kindOf(n),scalar(n.raw_ids),scalar(n.aliases),scalar(n.case_ids),n.semantic_level].join(' ').toLowerCase()}));state.searchReady=true;updateFacets();$('index-status').textContent=`全局索引已载入：${fmt(rows.length)} 个节点。输入查询以跨场景查找。`;renderResults();}catch(error){$('index-status').textContent=`全局索引不可用：${error.message}。仍可逐场景或加载全部检索。`;}}
  async function start(){try{state.manifest=await fetchJSON(manifestURL);state.scenarios=scenariosOf(state.manifest);if(!state.scenarios.length)throw new Error('清单中没有可加载场景。');$('domain').innerHTML='<option value="">所有领域</option>'+[...new Set(state.scenarios.map(s=>s.domain))].sort().map(d=>`<option value="${escapeHTML(d)}">${escapeHTML(d)}</option>`).join('');renderScenarioOptions();const c=counts();$('accepted-count').textContent=`${fmt(c.n)} 节点 · ${fmt(c.e)} 边`;$('catalog-counts').textContent=`源业务 ${state.manifest.counts?.source_activities??'未提供'} 项 / ${state.manifest.counts?.source_steps??'未提供'} 步 · 机器活动 ${state.manifest.counts?.machine_examples??'未提供'} 项。所有场景可从上方目录选择。`;const requested=new URL(globalThis.location?.href||manifestURL).searchParams.get('scenario'),first=state.scenarios.find(s=>s.id===requested)||state.scenarios.find(s=>s.category==='authored'&&s.edge_count>0)||state.scenarios[0];$('scenario').value=first.id;loadSearch();await loadCases([first.id],{target:new URL(globalThis.location?.href||manifestURL).searchParams.get('node')});}catch(error){showError(error);setStatus('数据清单不可读取。请确认已运行数据导出，并通过本地 HTTP 服务打开 ui/。');}}
  $('scenario').addEventListener('change',()=>loadCases([$('scenario').value]));$('domain').addEventListener('change',renderScenarioOptions);$('activity').addEventListener('input',renderScenarioOptions);$('load-all').addEventListener('click',()=>loadCases(state.scenarios.map(s=>s.id)));$('cancel-load').addEventListener('click',()=>state.abort?.abort());
  for(const id of ['type','level','relation','hops','budget','global-search','step'])$(id).addEventListener('change',()=>{state.page=0;render()});$('search').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.page=0;render()},140)});$('edge-labels').addEventListener('change',()=>{renderer.labels=$('edge-labels').checked;renderer.schedule()});
  $('mode-3d').addEventListener('click',()=>setMode(false));$('mode-flat').addEventListener('click',()=>setMode(true));function setMode(flat){state.flat=flat;$('mode-3d').setAttribute('aria-pressed',String(!flat));$('mode-flat').setAttribute('aria-pressed',String(flat));renderer.setMode(flat);}
  $('back-selection').addEventListener('click',()=>{const previous=state.history.pop();if(!previous)return;state.selected=previous;if(previous.type==='node')state.focus=previous.id;render();renderDetail();});
  $('fit').addEventListener('click',()=>renderer.fit());$('zoom-in').addEventListener('click',()=>renderer.zoom(1.25));$('zoom-out').addEventListener('click',()=>renderer.zoom(.8));$('clear-selection').addEventListener('click',()=>{state.selected=null;state.focus=null;render();renderDetail()});$('clear-filters').addEventListener('click',()=>{for(const id of ['type','level','relation','search','step'])$(id).value='';state.focus=null;state.page=0;render()});$('previous-page').addEventListener('click',()=>{state.page--;renderResults()});$('next-page').addEventListener('click',()=>{state.page++;renderResults()});
  $('results').addEventListener('click',event=>{const button=event.target.closest('[data-result]');if(button)selectNode(button.dataset.result,{fromGlobal:state.globalResults})});$('detail').addEventListener('click',event=>{const node=event.target.closest('[data-node]'),edge=event.target.closest('[data-edge]'),action=event.target.closest('[data-action]')?.dataset.action;if(node)selectNode(node.dataset.node);else if(edge)selectEdge(edge.dataset.edge);else if(action==='flat-focus')setMode(true);else if(action==='two-hop'){$('hops').value='2';render()}else if(action==='clear-focus'){state.focus=null;render()}else if(action==='more-relations'){state.relationPage+=40;renderDetail()}});
  $('coverage').addEventListener('click',renderCoverage);$('close-coverage').addEventListener('click',()=>{$('coverage-dialog').close?.();$('coverage-dialog').removeAttribute('open')});$('export').addEventListener('click',()=>{const data={schema_version:SCHEMA,read_only_export:true,scope:{case_ids:[...activeCaseIds()],source_manifest:state.manifest,counts:{nodes:state.index.nodes.size,edges:state.index.edges.size}},nodes:[...state.index.nodes.values()],edges:[...state.index.edges.values()],diagnostics:state.index.diagnostics,conflicts:state.index.conflicts};const blob=new Blob([pretty(data)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='p08-loaded-graph.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('live').textContent='导出完整已加载范围，未按画布上限截断。'});
  return {state,renderer,start,loadCases,selectNode,selectEdge,render,renderDetail,renderCoverage,destroy(){state.abort?.abort();clearTimeout(searchTimer);renderer.destroy();}};
}
if(globalThis.document && !globalThis.__P08_TEST__) {const app=createApp();globalThis.p08GraphApp=app;app.start();}
