import {makeIndex,kindOf,relationOf,textLabel,TYPES,DOMAINS,groupOf,domainOf,matches,nodeText,overviewScene,localScene} from './model.js';
import {displayNodeLabel,displayEdgeLabel,displayLabels} from './display.js';
import {StarRenderer} from './renderer.js';
import {BRANCH_LABELS,caseSummary,keyFacets,timeText,truthText,scalarText} from './coherent.js';
const format=n=>Number(n||0).toLocaleString('en-US');
export function createApp({document:doc=globalThis.document,fetchImpl=globalThis.fetch,Renderer=StarRenderer,initialSource='coherent'}={}){
 const $=id=>doc.getElementById(id),state={source:initialSource,coherentManifest:null,coherentSupplements:null,caseOptions:[],coherentCase:null,branch:'normal',explain:false,mode:'overview',native:null,nativeIndex:null,index:null,fullCaseIndex:null,manifest:null,globalSearch:null,scenario:null,step:'',domain:'',type:'',kind:'',relation:'',query:'',page:0,focus:null,selected:null,hops:1,budget:160,scene:null,history:[],loadVersion:0,detailVersion:0,neighborsLimit:30,ready:false},cleanups=[],chunkCache=new Map(),caseCache=new Map();
 const h=(tag,props={},children=[])=>{const el=doc.createElement(tag);for(const [k,v]of Object.entries(props)){if(k==='text')el.textContent=v;else if(k==='class')el.className=v;else if(k==='click')el.addEventListener('click',v);else if(k==='style')Object.assign(el.style,v);else if(k==='disabled')el.disabled=v;else el.setAttribute(k,String(v));}for(const child of Array.isArray(children)?children:[children])if(child)el.append(typeof child==='string'?doc.createTextNode(child):child);return el;};
 function nodeName(n){if(!n)return '';const has=state.index?.nodes.has(n.id),value=n.payload?n:has?state.index.nodes.get(n.id):n;return displayNodeLabel(value,has?state.index:undefined);}
 async function copyId(id,button){try{const clipboard=doc.defaultView?.navigator?.clipboard;if(clipboard?.writeText)await clipboard.writeText(id);else{const input=h('textarea',{text:id});input.style.position='fixed';input.style.opacity='0';doc.body.append(input);input.select();const copied=doc.execCommand?.('copy');input.remove();if(!copied)throw new Error('Clipboard unavailable');}button.textContent='已复制';status('已复制原始节点/关系 ID');}catch{status('无法自动复制，请选择下方完整 ID 复制。');}}
 function idBlock(id,original){return h('div',{class:'identity-block'},[h('div',{class:'identity-heading'},[h('span',{text:'ID'}),h('button',{class:'text-button copy-id','data-copy-id':id,click:event=>copyId(id,event.currentTarget),text:'复制 ID'})]),h('div',{class:'node-id',text:id}),...(original&&original!==id?[h('div',{class:'source-id',text:'源 ID · '+original})]:[])]);}
 const on=(id,event,fn)=>{$(id).addEventListener(event,fn);cleanups.push(()=>$(id).removeEventListener(event,fn));};
 const nativeCounts=()=>{const c=state.native?.counts||state.coherentManifest?.catalog_counts||{},k=c.by_kind||{};return{predicates:k.predicate_definition||0,events:k.event_definition||0,states:c.authored_state_fields||k.state_specification||k.state_definition||0,runtime:c.runtime_exported_state_fields??state.native?.nodes.filter(n=>['state_definition','state_specification'].includes(n.kind)&&n.runtime_used!==false).length??0,declarationOnly:c.declaration_only_state_fields??state.native?.nodes.filter(n=>['state_definition','state_specification'].includes(n.kind)&&n.declaration_only).length??0};};
 const setError=error=>{$('error').hidden=!error;$('error').textContent=error?String(error.message||error):'';};
 const status=text=>{$('load-status').textContent=text;};
 const fetchJSON=async path=>{const response=await fetchImpl(new URL(path,doc.baseURI));if(!response.ok)throw new Error(`数据读取失败 ${response.status}: ${path}`);return response.json();};
 const detailRecord=async record=>{if(!record?.detail_path)return record;const path=record.detail_path;if(!chunkCache.has(path))chunkCache.set(path,fetchJSON('../data/'+path).catch(error=>{chunkCache.delete(path);throw error;}));const chunk=await chunkCache.get(path);const full=chunk.nodes?.[record.id]||chunk.edges?.[record.id]||chunk.records?.[record.id]||(Array.isArray(chunk.nodes)?chunk.nodes.find(n=>n.id===record.id):null)||(Array.isArray(chunk.edges)?chunk.edges.find(e=>e.id===record.id):null)||record;if(full.payload_from){const original=await detailRecord(full.payload_from),{payload_from,...metadata}=full;return{...metadata,payload:original.payload};}return full;};
 const renderer=new Renderer($('graph'),{onNode:id=>selectNode(id),onEdge:id=>selectEdge(id),onGroup:domain=>{state.domain=domain;$('domain').value=domain;state.focus=null;state.selected=null;state.mode='overview';render();renderDetail();},onHover:(hit,point)=>{const tooltip=$('tooltip');tooltip.hidden=!hit;if(!hit)return;const record=hit.type==='node'?state.index.nodes.get(hit.id):hit.type==='edge'?state.index.edges.get(hit.id):null;tooltip.replaceChildren(h('strong',{text:hit.type==='node'?nodeName(record):hit.type==='edge'?displayEdgeLabel(record):DOMAINS[hit.id]||hit.id}),h('span',{text:hit.type==='node'?TYPES[groupOf(record)].label+' · '+kindOf(record):hit.type==='edge'?'点击查看方向、来源与绑定上下文':'进入此领域的真实节点预览'}),h('small',{text:record?.original_id||record?.id||''}));const width=$('canvas-wrap').clientWidth||800,height=$('canvas-wrap').clientHeight||600;tooltip.style.left=Math.max(8,Math.min(point.x+15,width-290))+'px';tooltip.style.top=Math.max(10,Math.min(point.y+15,height-115))+'px';}});
 function populateSelect(id,items,all='全部'){const control=$(id),old=control.value;control.replaceChildren(h('option',{value:'',text:all}),...items.map(([value,label])=>h('option',{value,text:label})));if(items.some(([value])=>value===old))control.value=old;}
 function prepareFacets(){if(!state.index)return;const allNodes=[...state.index.nodes.values()],counts=new Map();for(const n of allNodes){const key=groupOf(n);counts.set(key,(counts.get(key)||0)+1);}const domains=[...new Set(allNodes.map(domainOf))].sort();populateSelect('domain',domains.map(d=>[d,DOMAINS[d]||d]),'全部领域');$('domain').value=state.domain;populateSelect('kind',[...state.index.types].sort(([a],[b])=>a.localeCompare(b)).map(([k,n])=>[k,`${k} · ${format(n)}`]),'全部原始类型');$('kind').value=state.kind;populateSelect('relation',[...state.index.relations].sort(([a],[b])=>a.localeCompare(b)).map(([r,n])=>[r,`${r} · ${format(n)}`]),'全部真实关系');$('relation').value=state.relation;
 $('type-filters').replaceChildren(...Object.entries(TYPES).filter(([key])=>counts.has(key)).map(([key,value])=>h('button',{class:'type-filter','aria-pressed':state.type===key,click:()=>{state.type=state.type===key?'':key;state.kind='';state.page=0;render();renderSearch();}},[h('span',{},[h('i',{class:'type-symbol '+value.shape,style:{'--type-color':value.color}}),value.label]),h('small',{text:format(counts.get(key))})])));}
 function saveHistory(){if(state.selected)state.history.push({source:state.source,scenario:state.scenario?.id,coherentCase:state.coherentCase?.id,branch:state.branch,explain:state.explain,focus:state.focus,selected:{...state.selected},hops:state.hops,domain:state.domain,type:state.type,kind:state.kind,relation:state.relation});if(state.history.length>30)state.history.shift();$('back').disabled=!state.history.length;}
 async function start(){await switchSource(initialSource);state.ready=!!state.index;}
 async function ensureCoherentManifest(){if(!state.coherentManifest)state.coherentManifest=await fetchJSON('../data/coherent/manifest.json');if(!state.coherentSupplements)state.coherentSupplements=await fetchJSON('../data/supplements/manifest.json');state.caseOptions=[...state.coherentManifest.cases,...state.coherentSupplements.cases];populateSelect('coherent-case',state.caseOptions.map(c=>[c.id,c.id+(c.is_supplement?' · 补充':'')+' · '+c.title]),'选择连贯案例');}
 async function loadCoherentCase(id,branch,{version=state.loadVersion}={}){
  const entry=state.caseOptions.find(c=>c.id===id),variant=entry?.branches[branch];if(!variant)throw new Error('未找到案例分支 '+id+'/'+branch);
  const key='coherent:'+id+':'+branch;if(!caseCache.has(key))caseCache.set(key,fetchJSON('../data/coherent/'+(entry.base_path||'')+variant.path).catch(error=>{caseCache.delete(key);throw error;}));const data=await caseCache.get(key);let supplementalEvidence=null;if(entry.explanation_paths){const base='../data/coherent/'+entry.base_path;const [probes,lifecycle]=await Promise.all([fetchJSON(base+entry.explanation_paths.probes),fetchJSON(base+entry.explanation_paths.lifecycle)]);supplementalEvidence={probes,lifecycle};}
  if(version!==state.loadVersion||state.source!=='coherent')return false;
  state.coherentCase={...entry,...variant,data,id,supplementalEvidence};state.branch=branch;state.index=makeIndex([{data,scenario:{id:id+':'+branch}}]);state.fullCaseIndex=state.index;state.scenario=null;state.focus=variant.default_focus;state.selected={type:'node',id:state.focus};state.hops=2;state.explain=true;state.mode='local';state.domain='';state.type='';state.kind='';state.relation='';$('coherent-case').value=id;$('branch').value=branch;return true;
 }
 async function changeCoherentCase(id,branch){const version=++state.loadVersion;state.detailVersion++;saveHistory();$('loading').hidden=false;setError(null);try{if(await loadCoherentCase(id,branch,{version})){render();renderSearch();await renderDetail();status(`${id} · ${BRANCH_LABELS[branch]}分支 · live provider 绑定待接入`);}}catch(error){if(version===state.loadVersion){setError(error);if(state.coherentCase){$('coherent-case').value=state.coherentCase.id;$('branch').value=state.branch;}}}finally{if(version===state.loadVersion)$('loading').hidden=true;}}
 async function loadCase(id,{version=state.loadVersion}={}){const scenario=state.manifest.scenarios.find(s=>s.id===id);if(!scenario)throw new Error('未找到场景 '+id);if(!caseCache.has(id))caseCache.set(id,fetchJSON('../data/instances/'+scenario.path).catch(e=>{caseCache.delete(id);throw e;}));const data=await caseCache.get(id);if(version!==state.loadVersion||state.source!=='instances')return false;state.scenario={...scenario,data};const projected={...data,nodes:data.nodes.map(n=>({...n,view_domain:scenario.domain}))};state.fullCaseIndex=makeIndex([{data:projected,scenario}]);state.index=state.fullCaseIndex;state.step='';state.focus=null;state.selected=null;state.mode='overview';$('scenario').value=id;populateSelect('step',(data.steps||[]).map((s,i)=>[String(i),`${s.step_index||i+1}. ${s.source_step||s.imported_step||'步骤'}`]),'全部步骤');$('scope-summary').textContent=`${scenario.label} · ${format(data.nodes.length)} 节点 / ${format(data.edges.length)} 关系`;return true;}
 async function switchSource(source){
  if(source===state.source&&state.index)return;
  const prior={source:state.source,index:state.index,scenario:state.scenario,coherentCase:state.coherentCase,branch:state.branch},version=++state.loadVersion;state.detailVersion++;state.source=source;state.domain='';state.type='';state.kind='';state.relation='';state.query='';state.page=0;state.focus=null;state.selected=null;state.hops=1;state.explain=false;$('search').value='';$('loading').hidden=false;$('loading').textContent='正在载入所选数据…';setError(null);
  try{
   if(source==='native'){
    if(!state.nativeIndex){const data=await fetchJSON('../data/typed-index.json');if(version!==state.loadVersion)return;state.native=data;state.nativeIndex=makeIndex([{data,scenario:{id:'native'}}]);}state.index=state.nativeIndex;
   }else if(source==='coherent'){
    await ensureCoherentManifest();if(version!==state.loadVersion)return;const id=state.coherentCase?.id||state.coherentManifest.default_case,branch=state.branch||state.coherentManifest.default_branch;if(!await loadCoherentCase(id,branch,{version}))return;
   }else{
    if(!state.manifest){const [manifest,search]=await Promise.all([fetchJSON('../data/instances/manifest.json'),fetchJSON('../data/instances/search-index.json')]);if(version!==state.loadVersion)return;state.manifest=manifest;state.globalSearch=search.nodes;}
    populateSelect('scenario',state.manifest.scenarios.map(s=>[s.id,s.label+' · '+s.id]),'选择旧实例场景');const first=state.manifest.scenarios.find(s=>s.id==='DLV-A26-001')||state.manifest.scenarios?.find(s=>s.edge_count>0);if(!await loadCase(first.id,{version}))return;
   }
   if(version!==state.loadVersion)return;render();renderSearch();await renderDetail();status(source==='coherent'?'连贯案例已载入 · live provider 绑定待接入':source==='native'?'共享原始定义 · 类型桥接保留源声明':'旧实例集 · 与新编写案例独立');
  }catch(error){if(version===state.loadVersion){Object.assign(state,prior);if(state.index)render();setError(error);}}finally{if(version===state.loadVersion)$('loading').hidden=true;}
 }
 async function selectNode(id,{history=true}={}){if(!state.index)return;if(history)saveHistory();try{if(!state.index.nodes.has(id)&&state.source==='instances'){const row=state.globalSearch.find(n=>n.id===id),caseId=row?.case_ids?.[0];if(!caseId)throw new Error('该节点没有可加载的场景来源');const version=++state.loadVersion;$('loading').hidden=false;const ok=await loadCase(caseId,{version});if(version===state.loadVersion)$('loading').hidden=true;if(!ok)return;state.domain='';state.type='';state.kind='';state.relation='';}if(!state.index.nodes.has(id))throw new Error('当前数据源不存在该节点');state.explain=false;state.focus=id;state.selected={type:'node',id};state.mode='local';state.hops=1;state.neighborsLimit=30;render();await renderDetail();status('已聚焦 · 点击关系查看原始方向');}catch(error){$('loading').hidden=true;setError(error);}}
 async function selectEdge(id,{history=true}={}){if(!state.index?.edges.has(id))return;if(history)saveHistory();state.explain=false;state.selected={type:'edge',id};renderer.setSelected(id);await renderDetail();}
 function render(){if(!state.index)return;prepareFacets();$('source-coherent').classList.toggle('active',state.source==='coherent');$('source-coherent').setAttribute('aria-pressed',state.source==='coherent');$('coherent-control').hidden=state.source!=='coherent';$('branch-strip').hidden=state.source!=='coherent';if(state.source==='coherent'){for(const branch of Object.keys(BRANCH_LABELS))$('branch-'+branch).classList.toggle('active',state.branch===branch);$('case-caption').textContent=state.coherentCase.id+' · '+BRANCH_LABELS[state.branch]+(state.coherentCase.is_supplement?' · 独立补充':' · 编写配置');}$('source-native').classList.toggle('active',state.source==='native');$('source-instances').classList.toggle('active',state.source==='instances');$('source-native').setAttribute('aria-pressed',state.source==='native');$('source-instances').setAttribute('aria-pressed',state.source==='instances');$('scenario-control').hidden=state.source!=='instances';$('back').disabled=!state.history.length;state.scene=state.focus?localScene(state.index,{focus:state.focus,hops:state.hops,limit:state.budget,domain:state.domain,type:state.type,kind:state.kind,relation:state.relation}):overviewScene(state.index,{domain:state.domain,type:state.type,kind:state.kind,relation:state.relation,limit:Math.min(280,state.budget+80)});state.mode=state.scene.mode;state.scene.displayLabels=displayLabels(state.index);renderer.setScene(state.scene,{preserve:state.focus===renderer.scene?.focus&&state.mode==='local'});renderer.setSelected(state.selected?.id);$('empty').hidden=state.scene.nodes.length>0;$('visible-count').textContent=format(state.scene.nodes.length);$('edge-count').textContent=format(state.scene.edges.length);$('graph-title').textContent=state.source==='coherent'?state.coherentCase.id+' · '+(state.explain?'多域任务解释链':nodeName(state.index.nodes.get(state.focus))||state.coherentCase.title):state.focus?nodeName(state.index.nodes.get(state.focus)):state.source==='native'?(state.domain?(DOMAINS[state.domain]||state.domain)+' · 关系星群':'原始目录 · 领域星群'):'场景实例 · '+(state.scenario?.label||'关系星群');$('graph-subtitle').textContent=state.source==='coherent'?'共享原始定义与案例绑定分离 · live provider 绑定待接入':state.focus?`以当前节点为中心 · ${state.hops} 跳关系 · 箭头保留源数据方向`:'真实节点组成的分组预览 · 点击节点进入邻域';$('view-status').textContent=state.focus?`${state.hops} 跳邻域`:'领域概览';$('expand').hidden=!state.focus;$('expand').disabled=state.hops>=4;$('expand').textContent=state.hops>=4?'已展开至 4 跳':`展开第 ${state.hops+1} 跳 ↗`;$('breadcrumb-current').textContent=state.focus?TYPES[groupOf(state.index.nodes.get(state.focus))].label:state.domain?(DOMAINS[state.domain]||state.domain):'';$('breadcrumb-separator').hidden=!$('breadcrumb-current').textContent;
 const total=state.index.nodes.size;$('omissions').textContent=state.focus?`邻域候选 ${format(state.scene.candidateCount)} · 上限外 ${format(state.scene.omittedNodes)} 个节点 / ${format(state.scene.omittedEdges)} 条关系 · ${format(state.scene.boundaryEdges)} 条边指向画布外`:`已载入 ${format(total)} 个节点，当前预览 ${format(state.scene.nodes.length)} 个。分组标签是导航汇总，不是新增语义节点。`;
 if(state.source==='coherent')$('scope-summary').textContent=`${state.coherentCase.title} · ${format(state.index.nodes.size)} 节点 / ${format(state.index.edges.size)} 关系`;if(state.source==='native')$('scope-summary').textContent=`${format(state.native.counts.by_kind.predicate_definition)} 个谓词 · ${format(state.native.counts.by_kind.event_definition)} 个事件 · 完整可检索`;
 $('total-summary').textContent=state.source==='coherent'?`${state.coherentCase.id} / ${BRANCH_LABELS[state.branch]} · ${format(state.index.nodes.size)} 节点 · ${format(state.index.edges.size)} 关系 · ${state.coherentCase.definition_mappings} 个共享定义` :state.source==='native'?`原始目录：${format(nativeCounts().predicates)} 谓词 · ${format(nativeCounts().events)} 事件 · ${format(nativeCounts().states)} 原始字段 / ${format(nativeCounts().runtime)} 导出字段`:`场景目录：20,201 节点 · 64,978 关系 · 当前载入 ${format(total)} 节点`;
 $('cluster-list').replaceChildren(...state.scene.groups.map(g=>h('button',{click:()=>{state.domain=g.id;$('domain').value=g.id;render();}},[g.label,h('span',{text:format(g.count)})])));}
 function searchRows(){const query=state.query.trim().toLowerCase();if(state.source==='instances'){const terms=query.split(/\s+/).filter(Boolean);return (state.globalSearch||[]).filter(n=>(!state.type||groupOf(n)===state.type)&&(!state.kind||kindOf(n)===state.kind)&&terms.every(t=>[n.id,n.original_id,textLabel(n.label),n.kind,...(n.raw_ids||[])].join(' ').toLowerCase().includes(t)));}const terms=query.split(/\s+/).filter(Boolean);return matches(state.index,{domain:state.domain,type:state.type,kind:state.kind}).filter(n=>terms.every(t=>(nodeText(n)+' '+nodeName(n)).toLowerCase().includes(t)));}
 function renderSearch(){const show=!!state.query.trim();$('search-results').hidden=!show;$('search-pages').hidden=!show;if(!show||!state.index)return;const rows=searchRows(),size=12,pages=Math.max(1,Math.ceil(rows.length/size));state.page=Math.min(state.page,pages-1);$('search-results').replaceChildren(...rows.slice(state.page*size,(state.page+1)*size).map(n=>h('button',{class:'search-item',click:()=>selectNode(n.id)},[h('strong',{text:nodeName(n)||n.original_id||n.id}),h('small',{text:n.original_id||n.id}),h('span',{text:kindOf(n)})])));if(!rows.length)$('search-results').append(h('p',{class:'fine',text:'没有找到匹配节点'}));$('search-page').textContent=`${format(rows.length)} 项 · ${state.page+1}/${pages}`;$('search-prev').disabled=state.page===0;$('search-next').disabled=state.page>=pages-1;}
 function jsonBlock(title,value){return h('details',{class:'data-block'},[h('summary',{text:title}),h('pre',{text:JSON.stringify(value,null,2)})]);}
 function symbol(n){const style=TYPES[groupOf(n)];return h('i',{class:'type-symbol '+style.shape,style:{'--type-color':style.color}});}
 function introDetail(){if(state.source==='coherent')return renderCaseExplanation();const data=state.source==='native'?state.native:null;const byKind=data?.counts.by_kind;const available=[...state.index.nodes.values()];const examples=state.source==='native'?['he.e.camera.saturation_episode','mn.p.network.connected','dt.predicate.observation_binding_ready','engine.predicate.low_pressure'].map(id=>available.find(n=>n.original_id===id)).filter(Boolean):available.filter(n=>['predicate','event','entity'].includes(groupOf(n))).slice(0,4);return h('div',{class:'inspect-intro'},[h('div',{class:'intro-star',text:'✧'}),h('h2',{text:'让关系自己说话'}),h('p',{text:'每个星点都是一个有类型的真实记录。点击节点查看定义、原始 AST 与来源；点击连线检查关系方向和绑定上下文。'}),h('div',{class:'metric-grid'},(state.source==='native'?[[byKind?.predicate_definition,'谓词定义'],[byKind?.event_definition,'事件定义'],[byKind?.state_specification||byKind?.state_definition,'状态字段'],[byKind?.rule_definition,'规则根节点']]:[[state.index.nodes.size,'当前节点'],[state.index.edges.size,'当前关系'],[20201,'全局节点'],[75,'场景分块']]).map(([number,label])=>h('div',{class:'metric'},[h('strong',{text:format(number)}),h('span',{text:label})]))),h('div',{class:'section-title',text:'推荐起点'}),...examples.map(n=>h('button',{class:'journey-item',click:()=>selectNode(n.id)},[symbol(n),h('span',{},[h('strong',{text:textLabel(n.label)}),h('small',{text:n.original_id||n.id})])])),h('div',{class:'warning',text:state.source==='native'?'共享目录定义保持独立；显式主体绑定在各自编写案例中查看。声明角色仍按原类型保留。':'场景来源和原始字段保持不变。配置、样例期望与实际执行证据分别保留；没有在这里执行规则。'})]);}
 function appendSemanticDetail(container,n){
  const original=n.id.startsWith('native:');if(n.raw_kind&&n.raw_kind!==n.kind)container.append(jsonBlock('节点类型映射',{kind:n.kind,raw_kind:n.raw_kind,bridge:n.bridge}));container.append(h('span',{class:'source-badge'+(original?'':' authored'),text:original?'共享原始定义':'案例编写 / 保留源记录'}));
  if(n.source_storage_aliases?.length)container.append(jsonBlock('原始存储别名',n.source_storage_aliases));
  if(original&&state.source==='coherent'){
   const overlays=(state.coherentCase.data.catalog_instance_binding_overlays||[]).filter(b=>b.canonical_id===n.id);
   if(overlays.length)container.append(h('div',{class:'case-binding'},[h('p',{text:state.coherentCase.id+' / '+BRANCH_LABELS[state.branch]+' 的编写绑定，与共享目录元数据分开保存'}),jsonBlock('本案例绑定覆盖',overlays)]));
   container.append(h('button',{class:'explain-button',text:'查看共享目录定义 ↗',click:async()=>{saveHistory();await switchSource('native');await selectNode(n.id,{history:false});}}));
  }
  const facets=keyFacets(n);if(facets.length){container.append(h('div',{class:'facet-list'},facets.slice(0,14).map(f=>{const value=f.status==='known'?f.value:f.reason||f.status;const text=f.status==='known'&&/time|availability|cutoff|validity|interval/.test(f.key)?timeText(value):scalarText(value);return h('div',{class:'facet-entry'},[h('div',{},[h('span',{text:f.label}),h('small',{text:f.status})]),h('pre',{text}),...(f.status==='known'&&value?.node_id&&state.index.nodes.has(value.node_id)?[h('button',{class:'text-button',text:'定位引用 ↗',click:()=>selectNode(value.node_id)})]:[])]);})));container.append(jsonBlock('完整语义槽与原始状态',n.facets||n.semantics?.facets));}
  if(n.semantic_obligations)container.append(jsonBlock('语义要求与证据状态',n.semantic_obligations));
  if(n.kind==='event_occurrence'&&(n.payload?.emitted===false||n.facets?.emitted?.value===false||/candidate/.test(n.payload?.status||'')))container.append(h('p',{class:'warning',text:'这是候选事件。emitted、源时间字段和可用时间分别保留；评估记录不表示真实事件已经发出。'}));
 }
 function renderConcurrencyExplanation(){
  const current=state.coherentCase,data=current.data,scenario=data.nodes.find(n=>n.kind==='scenario_definition'),spec=scenario?.payload?.case||{},evidence=current.supplementalEvidence||{},probes=evidence.probes?.[state.branch]||[],lifecycle=evidence.lifecycle||{},box=h('div',{class:'case-explanation'});
  const link=(id,label)=>state.index.nodes.has(id)?h('button',{class:'journey-item',click:()=>selectNode(id)},[symbol(state.index.nodes.get(id)),h('span',{},[h('strong',{text:label||textLabel(state.index.nodes.get(id).label)}),h('small',{text:id})])]):h('p',{class:'detail-note',text:label||id});
  box.append(h('span',{class:'source-badge authored',text:'C13 独立补充 · '+BRANCH_LABELS[state.branch]}),h('h2',{class:'trace-header',text:'同一架无人机，两笔订单'}),h('div',{class:'warning',text:'范围：编写的固定预算准入与账本回放。Live provider 绑定待接入；PX4、原生 Atlas 与真实硬件调度尚未验证。原12案例及48分支保持不变。'}));
  box.append(h('div',{class:'section-title',text:'01 · 同一 UAV，独立任务目标'}),link('C13:entity:uav','同一主体 C13:entity:uav'));
  for(const order of spec.orders||[])box.append(h('div',{class:'trace-summary'},[h('strong',{text:order.order_id+' · '+order.task}),h('p',{text:'派单方 '+order.dispatcher+' · 截止 '+order.deadline_s+' s'}),h('p',{text:'期望目标 ENU '+scalarText(order.desired_target_enu_m)}),link('C13:task:'+order.task,'查看任务主体与绑定')]));
  box.append(h('p',{class:'detail-note',text:'任务期望目标、已下发目标与实际位姿分别建模。相机预览不表示已经到达巡检位置或完成巡检订单。'}));
  for(const n of data.nodes.filter(n=>n.kind==='fact'&&/actual_pose|commanded_target/.test(n.payload?.field_id||'')).slice(0,3))box.append(link(n.id,n.payload.field_id+' = '+scalarText(n.payload.value)));
  box.append(h('div',{class:'section-title',text:'02 · 独占飞控，基准顺序'}));
  for(const assignment of spec.control_assignments||[])box.append(h('p',{class:'detail-note',text:assignment.order_id+' · ['+assignment.start+', '+assignment.end+') s · flight_control 1槽'}));
  box.append(h('p',{class:'detail-note',text:'容量只有1个飞控槽。同一 UAV 的相冲突飞行目标按准入规则排序；当前补充没有执行真实调度。'}),jsonBlock('原始仲裁规则',spec.arbitration));
  box.append(h('div',{class:'section-title',text:'03 · 相机 / GNSS / 无线电并行预算'}));
  probes.forEach((probe,i)=>{const result=probe.result||{},truth=truthText(result.truth),decision='C13:'+state.branch+':policy:'+i+':decision',rows=probe.rows||[],budget=h('div',{class:'metadata-fields'});for(const [resource,unit]of [['flight_control','槽'],['power_w','W'],['cpu_millicores','millicores'],['uplink_bps','bit/s']])budget.append(h('div',{},[h('span',{text:resource}),h('strong',{text:scalarText(result.aggregate?.peaks?.[resource])+' / '+scalarText(result.capacities?.[resource])+' '+unit})]));
   box.append(h('div',{class:'trace-summary'},[h('span',{class:'truth-chip '+(truth==='False'?'false':truth==='Unknown'?'unknown':''),text:truth+' · '+(result.decision||'未声明')}),link(decision,probe.name),h('p',{text:'活动分配：'+rows.map(row=>row.id).join(' · ')}),budget,h('p',{text:'已花费 '+scalarText(result.aggregate?.spent_wh)+' Wh；未来承诺 '+scalarText(result.aggregate?.future_energy_wh)+' Wh'}),h('p',{text:'能源观测 '+scalarText(result.energy?.remaining_wh)+' Wh；误差 '+scalarText(result.energy?.error_wh)+' Wh；保留 '+scalarText(result.energy?.reserve_wh)+' Wh'}),link('C13:'+state.branch+':probe:'+i+':ledger','查看逐区间合计与来源账本'),jsonBlock('完整准入探针',probe)]));
  });
  box.append(h('div',{class:'section-title',text:'04 · 补充取消回放与资源释放'}),h('p',{class:'detail-note',text:'在 '+scalarText(lifecycle.cancel_at_s)+' s 取消巡检：'+(lifecycle.released||[]).join('、')+'。已发生的能耗继续计入账本。'}),h('p',{class:'detail-note',text:'保留的既有任务/流：'+(lifecycle.incumbent_streams||[]).join('、')}),h('p',{class:'detail-note',text:'重复取消不重复释放：'+scalarText(lifecycle.repeated_cancel_unchanged)+'；陈旧释放被接受：'+scalarText(lifecycle.stale_release_accepted)}),h('p',{class:'warning',text:'这些是候选分配和账本回放。没有真实停止确认、资源预订或命令派发。'}),jsonBlock('完整取消与代际令牌记录',lifecycle));
  const events=data.nodes.filter(n=>n.kind==='event_occurrence');box.append(h('div',{class:'section-title',text:'05 · 候选事件与扩展规则'}));for(const n of events.slice(0,4))box.append(link(n.id,'候选事件 · '+(n.payload.probe||n.label)));for(const n of data.nodes.filter(n=>n.kind==='predicate_definition'&&n.id.startsWith('C13:predicate:')))box.append(link(n.id,'编写扩展 · '+(n.payload.name||n.id)));
  box.append(jsonBlock('补充范围与版本',{manifest_sha256:current.manifest_sha256,scope:current.supplement_scope,policy_version:spec.policy_version,claim_limit:data.claim_limit,original12_unchanged:true}),jsonBlock('完整原始案例配置',spec));return box;
 }

 function renderCaseExplanation(){
  if(state.coherentCase.is_supplement&&state.coherentCase.id==='C13')return renderConcurrencyExplanation();const data=state.coherentCase.data,summary=caseSummary(data),outcome=summary.outcome,box=h('div',{class:'case-explanation'}),truth=truthText(outcome.technical_actual);
  box.append(h('span',{class:'source-badge authored',text:summary.caseId+' · '+BRANCH_LABELS[summary.branch]+' · 编写配置'}),h('h2',{class:'trace-header',text:summary.title}),h('div',{class:'trace-summary'},[h('span',{class:'truth-chip '+(truth==='False'?'false':truth==='Unknown'?'unknown':''),text:truth}),h('p',{text:'夹具技术结果 · '+(outcome.policy_status||'未声明策略状态')}),h('p',{text:'Live provider 绑定待接入；真实授权与物理执行尚未建立。事件发出状态独立核对。'})]));
  const reference=(n,label)=>h('button',{class:'journey-item',click:()=>selectNode(n.id)},[symbol(n),h('span',{},[h('strong',{text:label||textLabel(n.label)}),h('small',{text:n.id})])]);
  box.append(h('div',{class:'section-title',text:'01 · 主体与原始定义 · '+summary.actors.length+' 个主体'}));for(const n of summary.actors.slice(0,4))box.append(reference(n));box.append(h('p',{class:'detail-note',text:`${summary.sharedDefinitions} 个目录定义使用原始 native: ID；案例主体绑定与目录声明分离。`}));
  box.append(h('div',{class:'section-title',text:'02 · 谓词、证据与可用时间 · '+summary.results.length+' 项结果'}));for(const n of summary.results.slice(0,6))box.append(reference(n,truthText(n.payload?.truth)+' · '+(n.facets?.definition?.value?.node_id||textLabel(n.label))));for(const n of summary.timeContexts.slice(0,2))box.append(reference(n,'查询 '+timeText(n.payload?.query)+' / 截止 '+timeText(n.payload?.available_cutoff)));
  box.append(h('div',{class:'section-title',text:'03 · 约束与决策 · '+summary.constraints.length+' 项检查'}));if(summary.decision)box.append(reference(summary.decision,summary.decision.payload?.technical_status||textLabel(summary.decision.label)));for(const n of summary.constraints.slice(0,3))box.append(reference(n,`${n.payload?.truth||'未提供'} · ${n.payload?.decision||textLabel(n.label)}`));
  box.append(h('div',{class:'section-title',text:'04 · 编写的阶段顺序'}));summary.spec.stages?.forEach((stage,i)=>{const id=outcome.behavior_execution_ids?.[i],n=state.index.nodes.get(id);if(n)box.append(h('div',{class:'trace-stage'},[h('span',{text:String(i+1).padStart(2,'0')}),h('button',{click:()=>selectNode(n.id)},[stage,h('small',{text:'夹具效果 '+truthText(outcome.stage_effect_values?.[i])+' · 保留显式依赖关系'})])]));});
  box.append(h('div',{class:'section-title',text:'05 · 资源与时空要求'}));for(const n of summary.allocations.slice(0,4)){const p=n.payload||{},amount=p.amount;box.append(reference(n,amount?`${amount.dimension}: ${amount.value} ${amount.unit} · ${p.status||'编写要求'}`:'时空分配要求（未承诺实际占用）'));}if(summary.allocations.length>4)box.append(h('p',{class:'detail-note',text:`另有 ${summary.allocations.length-4} 条分配记录，可从资源类型过滤查看。`}));
  box.append(h('div',{class:'section-title',text:'06 · 事件与反馈'}));if(summary.event)box.append(reference(summary.event,'候选事件 · emitted = '+scalarText(summary.event.payload?.emitted)));box.append(h('p',{class:'detail-note',text:'候选事件可用时间、发生时间、技术结果与真正执行分开保存。'}),jsonBlock('源策略与范围',summary.spec.policy),jsonBlock('失败 / 恢复动作', {failure:summary.spec.failure,recovery:summary.spec.recovery}),jsonBlock('完整业务结果记录',outcome),jsonBlock('源 readiness 与证据边界',data.readiness),jsonBlock('冻结案例快照',{source_snapshot:state.coherentManifest.source_snapshot,frozen_manifest_sha256:state.coherentManifest.frozen_manifest_sha256,release_gate:state.coherentManifest.release_gate,live_provider_binding:state.coherentManifest.live_provider_binding}),jsonBlock('案例共享定义映射',data.catalog_identity_bridge));
  return box;
 }

 async function renderDetail(){const version=++state.detailVersion,container=$('detail');if(!state.index)return;if(state.source==='coherent'&&state.explain){container.replaceChildren(renderCaseExplanation());return;}if(!state.selected){container.replaceChildren(introDetail());return;}const selection={...state.selected},record=selection.type==='node'?state.index.nodes.get(selection.id):state.index.edges.get(selection.id);if(!record)return;container.replaceChildren(h('p',{class:'detail-note',text:'正在读取原始记录…'}));try{const full=await detailRecord(record);if(version!==state.detailVersion)return;container.replaceChildren();if(selection.type==='node'){
 const n=full,style=TYPES[groupOf(n)],priority={has_rule:0,uses_rule:0,reads_definition:4,declares_state_signature:5,has_applicability_rule:1,references_predicate:2,references_event:3,reads_state:4,declares_state:5,declared_owner:6,source_declared_owner:6},adj=[...(state.index.adjacent.get(n.id)||[])].sort((a,b)=>(priority[relationOf(a)]??7)-(priority[relationOf(b)]??7)||relationOf(a).localeCompare(relationOf(b)));container.append(h('span',{class:'selection-kind'},[symbol(n),style.label]),h('h2',{class:'node-title',text:nodeName(n)||n.original_id||n.id}),idBlock(n.id,n.original_id),h('div',{class:'node-meta'},[kindOf(n),n.semantic_level,DOMAINS[domainOf(n)]||domainOf(n),n.family].filter(Boolean).map(text=>h('span',{class:'meta-tag',text}))),h('p',{class:'detail-note',text:groupOf(n)==='role'?'原始目录声明的 owner 角色词汇，不是运行时实体实例。':n.semantic_level==='definition'?'定义记录 · 当前显示不代表已满足条件或发生事件。':'完整保留原始语义层、来源与记录值。'}),h('div',{class:'detail-actions'},[h('button',{click:()=>{state.hops=Math.min(4,state.hops+1);render();},text:'展开关系 ↗'}),h('button',{click:()=>renderer.fit(),text:'居中此邻域'})]));
 const payload=n.payload||{};appendSemanticDetail(container,n);
 if(['state_definition','state_specification'].includes(n.kind)){
  const declarations=payload.declarations||[];const fields=['type','unit','input_category','state_quantity','owner','frame','shape','enum','enum_values','allowed_values','missing_semantics'];const visible=fields.map(key=>[key,[...new Set(declarations.map(d=>d.payload?.[key]).filter(v=>v!==undefined).map(v=>typeof v==='object'?JSON.stringify(v):String(v)))]]).filter(([,values])=>values.length);
  if(n.declaration_only||n.runtime_used===false)container.append(h('p',{class:'warning',text:'仅原始目录声明：未进入打包运行时导出，也不表示已采集或观测。'}));
  if(visible.length)container.append(h('div',{class:'metadata-fields'},visible.map(([key,values])=>h('div',{},[h('span',{text:key}),h('strong',{text:values.join(' / ')})]))));
  if(declarations.some(d=>/ground_truth|latent_true/i.test(JSON.stringify([d.payload?.input_category,d.payload?.state_quantity]))))container.append(h('p',{class:'warning',text:'源目录含 latent_true / ground_truth 真值分类，按原语义保留，不作为已观测输入。'}));
  if(payload.export_metadata?.[0]==='unknown'&&declarations.some(d=>d.payload?.type&&d.payload.type!=='unknown'))container.append(h('p',{class:'warning',text:'原始打包导出类型为 unknown；全局字段声明提供了明确类型。两份来源分别保留。'}));
  if(payload.export_metadata)container.append(jsonBlock('打包导出元数据（保留原值）',payload.export_metadata));
  if(declarations.length)container.append(jsonBlock('原始字段声明及全部来源',declarations));
 }
 if(payload.interpretation)container.append(h('p',{class:'detail-note',text:payload.interpretation}));if(payload.rule)container.append(jsonBlock('规则 AST（原始结构）',payload.rule));if(payload.applicability_rule)container.append(jsonBlock('适用条件 AST',payload.applicability_rule));if(n.kind==='rule_definition')container.append(jsonBlock('规则 AST（原始结构）',payload));const literalFields={};for(const key of ['value','unit','type','owner','owner_field','timestamp_ns','valid_time_ns','available_time_ns','truth','truth_status','status'])if(Object.hasOwn(payload,key))literalFields[key]=payload[key];else if(payload.properties&&Object.hasOwn(payload.properties,key))literalFields['properties.'+key]=payload.properties[key];if(Object.keys(literalFields).length)container.append(jsonBlock('字段、值与时间',literalFields));
 container.append(h('div',{class:'section-title'},['关联关系',h('span',{class:'fine',text:format(adj.length)+' 条原始边'})]));for(const e of adj.slice(0,state.neighborsLimit)){const outgoing=e.source===n.id,other=state.index.nodes.get(outgoing?e.target:e.source);container.append(h('div',{class:'relation-item'},[h('div',{class:'relation-top'},[h('button',{class:'relation-name',title:relationOf(e),click:()=>selectEdge(e.id),text:displayEdgeLabel(e)}),h('span',{class:'relation-direction',text:outgoing?'↗':'↙'})]),h('button',{class:'relation-target',click:()=>selectNode(other.id),text:(outgoing?'→ ':'← ')+(nodeName(other)||other?.original_id||e.target)})]));}if(adj.length>state.neighborsLimit)container.append(h('button',{class:'neighbor-more',click:()=>{state.neighborsLimit+=30;renderDetail();},text:`再显示 30 条（剩余 ${format(adj.length-state.neighborsLimit)}）`}));container.append(jsonBlock('原始完整 payload',payload),jsonBlock('来源与记录指针',n.source_records||n.provenance||{}),jsonBlock('完整规范记录',n));
 }else{const e=full,a=state.index.nodes.get(e.source),b=state.index.nodes.get(e.target);container.append(h('span',{class:'selection-kind',text:'有向关系'}),h('h2',{class:'node-title',text:displayEdgeLabel(e)}),idBlock(e.id),h('p',{class:'detail-note',text:'原始关系类型 · '+relationOf(e)}),h('div',{class:'edge-direction'},[h('button',{class:'text-button',click:()=>selectNode(e.source),text:nodeName(a)||e.source}),h('div',{text:'↓ '+displayEdgeLabel(e)+(e.role?' · '+e.role:'')}),h('button',{class:'text-button',click:()=>selectNode(e.target),text:nodeName(b)||e.target})]),h('p',{class:'detail-note',text:'端点和方向按记录保留；规范关系、原始关系名与类型映射分别列出。平行边保留独立 ID。'}),jsonBlock('关系类型映射',{relation:e.relation,raw_relation:e.raw_relation,contract_variant:e.contract_variant,bridge:e.bridge,canonical_overlay:e.canonical_overlay}),jsonBlock('绑定上下文',e.binding_context||{}),jsonBlock('来源与 AST 指针',e.source_records||e.provenance||{}),jsonBlock('关系 payload',e.payload||{}),jsonBlock('完整关系记录',e));}
 }catch(error){if(version===state.detailVersion)container.replaceChildren(h('p',{class:'warning',text:'详情未能载入：'+error.message}),h('button',{click:()=>renderDetail(),text:'重试详情'}));}}
 function reset(){state.explain=state.source==='coherent';state.domain='';state.type='';state.kind='';state.relation='';state.focus=null;state.selected=null;state.hops=1;state.query='';state.page=0;$('search').value='';render();renderSearch();renderDetail();}
 on('source-coherent','click',()=>switchSource('coherent'));on('coherent-case','change',()=>{if($('coherent-case').value)changeCoherentCase($('coherent-case').value,state.branch);});on('branch','change',()=>changeCoherentCase(state.coherentCase.id,$('branch').value));for(const branch of Object.keys(BRANCH_LABELS))on('branch-'+branch,'click',()=>changeCoherentCase(state.coherentCase.id,branch));on('explain-case','click',()=>{state.explain=true;render();renderDetail();});on('source-native','click',()=>switchSource('native'));on('source-instances','click',()=>switchSource('instances'));on('search','input',()=>{state.query=$('search').value;state.page=0;renderSearch();});on('search-prev','click',()=>{state.page--;renderSearch();});on('search-next','click',()=>{state.page++;renderSearch();});on('domain','change',()=>{state.domain=$('domain').value;render();renderSearch();});on('kind','change',()=>{state.kind=$('kind').value;render();renderSearch();});on('relation','change',()=>{state.relation=$('relation').value;render();});on('budget','change',()=>{state.budget=Number($('budget').value);render();});on('reset-filters','click',reset);on('overview','click',()=>{state.focus=null;state.selected=null;state.domain='';render();renderDetail();});on('clear-selection','click',()=>{state.selected=null;renderer.setSelected(null);renderDetail();});on('expand','click',()=>{state.hops=Math.min(4,state.hops+1);render();});on('fit','click',()=>renderer.fit());on('zoom-in','click',()=>renderer.zoom(1.2));on('zoom-out','click',()=>renderer.zoom(1/1.2));on('labels','change',()=>{renderer.labels=$('labels').checked;renderer.dirty=true;});on('edge-labels','change',()=>{renderer.edgeLabels=$('edge-labels').checked;renderer.dirty=true;});on('auto-rotate','click',()=>{renderer.autoRotate=!renderer.autoRotate;$('auto-rotate').setAttribute('aria-pressed',renderer.autoRotate);});
 on('scenario','change',async()=>{if(!$('scenario').value)return;const version=++state.loadVersion;$('loading').hidden=false;try{if(await loadCase($('scenario').value,{version})){state.domain='';state.type='';state.kind='';state.relation='';render();renderDetail();}}catch(error){setError(error);}finally{if(version===state.loadVersion)$('loading').hidden=true;}});
 on('step','change',()=>{state.step=$('step').value;state.focus=null;state.selected=null;state.index=state.fullCaseIndex;if(state.step!==''){const step=state.scenario.data.steps[Number(state.step)],ids=new Set(step.node_ids),data={nodes:[...state.fullCaseIndex.nodes.values()].filter(n=>ids.has(n.id)),edges:[...state.fullCaseIndex.edges.values()].filter(e=>ids.has(e.source)&&ids.has(e.target))};state.index=makeIndex([{data,scenario:state.scenario}]);}render();renderDetail();});
 on('back','click',async()=>{const item=state.history.pop();if(!item)return;if(item.source!==state.source)await switchSource(item.source);if(item.coherentCase&&state.source==='coherent'&&(item.coherentCase!==state.coherentCase?.id||item.branch!==state.branch))await loadCoherentCase(item.coherentCase,item.branch);if(item.scenario&&state.source==='instances'&&item.scenario!==state.scenario?.id)await loadCase(item.scenario);Object.assign(state,{focus:item.focus,selected:item.selected,explain:item.explain,hops:item.hops,domain:item.domain,type:item.type,kind:item.kind||'',relation:item.relation});render();renderDetail();});
 on('provenance-button','click',()=>{const box=$('provenance-content');box.replaceChildren(h('p',{text:'此原型包含 12 个新编写连贯案例的四类分支，按审核后的 native: ID 共享原始目录定义。案例绑定单独保存。旧 75 个场景分块仍独立保留，不按相似名称合并。'}),h('p',{text:`原始目录共 ${format(nativeCounts().states)} 个状态字段，其中 ${format(nativeCounts().runtime)} 个进入打包运行时导出，另 ${format(nativeCounts().declarationOnly)} 个仅在目录中声明。导出元数据与完整原始声明的差异分别保留；不把目录声明当作已观测事实。`}),h('p',{text:'声明 owner 只构成词汇角色节点。星群标签和空间坐标是阅读辅助，不创建实例、绑定或因果关系。规则未在此界面执行。'}),jsonBlock('完整数据清单',state.native?.counts||state.coherentManifest?.catalog_counts||{}),jsonBlock('导入诊断',state.native?.diagnostics||[]),jsonBlock('源文件与哈希',state.native?.provenance||state.native?.sources||{}));$('provenance-dialog').showModal();});on('close-provenance','click',()=>$('provenance-dialog').close());
 on('export','click',async()=>{const snapshot=state.scene,source=state.source,button=$('export');button.disabled=true;try{const nodes=await Promise.all(snapshot.nodes.map(detailRecord)),edges=await Promise.all(snapshot.edges.map(detailRecord));const payload={schema_version:'p08.star-view-export/v1',source,view:{mode:snapshot.mode,focus:snapshot.focus,omitted_nodes:snapshot.omittedNodes,omitted_edges:snapshot.omittedEdges,boundary_edges:snapshot.boundaryEdges},nodes,edges,notice:'Read-only view. Navigation clusters and coordinates are not semantic nodes or edges. Catalog bindings remain separate from case-authored overlays. No live provider, physical execution or authority is asserted.'};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=h('a',{href:url,download:'P08-visible-relations.json'});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('已导出当前画布的完整原始记录');}catch(error){setError(error);}finally{button.disabled=false;}});
 const keyHandler=e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(doc.activeElement?.tagName)){e.preventDefault();$('search').focus();}if(e.key==='Escape'&&!$('provenance-dialog').open){state.selected=null;renderer.setSelected(null);renderDetail();}};doc.addEventListener('keydown',keyHandler);cleanups.push(()=>doc.removeEventListener('keydown',keyHandler));
 return{state,renderer,start,switchSource,changeCoherentCase,selectNode,selectEdge,render,renderDetail,renderSearch,detailRecord,destroy(){state.loadVersion++;state.detailVersion++;renderer.destroy();for(const cleanup of cleanups)cleanup();}};
}
if(!globalThis.__P08_TEST__&&globalThis.document){globalThis.p08=createApp();globalThis.p08.start();}
