"""Tests for the 414-building render scale-out and its fail-closed policy.

Subjects (checked-in artifacts under
``validation/building-render-scaleout-mimo-20260929/``):

  * the standalone validator must pass every check, including a full
    byte-identical regeneration into a temp sandbox;
  * exactly one GLB exists per ``object_id`` for all 414 buildings, and the
    catalog fragment pins each one's real sha256 under the strict
    ``CatalogBuildingRender`` contract (glTF content is ``asset_local``;
    a WGS84 label is rejected);
  * the style/atlas policy is deterministic for any input order and only
    ever uses styles that survived the seam audit;
  * the fail-closed paths really fail: non-simple polygons, missing
    texture/material, size mismatch and count mismatch all raise instead of
    skipping a building.

No fake GLBs are used anywhere: every generated byte in these tests comes
from the real BigCity atlases and the real compiled-scene footprints.
"""

from __future__ import annotations

import copy
import json
import sys
from pathlib import Path

import pytest

VALIDATION_DIR = (
    Path(__file__).resolve().parents[2]
    / "validation/building-render-scaleout-mimo-20260929"
)
if str(VALIDATION_DIR) not in sys.path:
    sys.path.insert(0, str(VALIDATION_DIR))

import generate_building_renders as gen  # noqa: E402
import validate_building_renders as validate  # noqa: E402
from aero_bench.world.scene_authoring import CatalogBuildingRender  # noqa: E402

RENDER_MEDIA_TYPE = "model/gltf-binary"
FRAGMENT_PATH = VALIDATION_DIR / "building-render-catalog-fragment.json"
MANIFEST_PATH = VALIDATION_DIR / "manifest.json"
PERFORMANCE_PATH = VALIDATION_DIR / "performance.json"
ASSET_DIR = VALIDATION_DIR / "assets"


def _objects() -> dict:
    return json.loads(validate.OBJECTS_PATH.read_text(encoding="utf-8"))


def _manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def _fragment() -> dict:
    return json.loads(FRAGMENT_PATH.read_text(encoding="utf-8"))


def _sample_building() -> dict:
    return _objects()["buildings"][0]


@pytest.fixture(scope="module")
def styles() -> dict:
    derived, _audit = gen.derive_styles()
    return derived


# --------------------------------------------------------------------------
# Validator + counts
# --------------------------------------------------------------------------


def test_validator_passes_all_checks() -> None:
    report = validate.run_checks()  # includes byte-identical regeneration
    assert report.failures == [], "\n".join(report.failures)
    assert report.passed > 10000


def test_exactly_one_glb_per_object_id() -> None:
    objects = _objects()
    manifest = _manifest()
    records = manifest["buildings"]
    scene_ids = {b["object_id"] for b in objects["buildings"]}
    record_ids = [r["object_id"] for r in records]

    assert len(scene_ids) == 414
    assert len(record_ids) == 414
    assert len(set(record_ids)) == 414
    assert set(record_ids) == scene_ids

    on_disk = {p.stem for p in ASSET_DIR.glob("*.glb")}
    assert on_disk == scene_ids
    assert len(on_disk) == 414

    for record in records:
        path = VALIDATION_DIR / record["glb"]
        assert path.name == f"{record['object_id']}.glb"
        assert path.stat().st_size == record["glb_bytes"]


def test_fail_closed_exception_log_is_empty() -> None:
    exceptions = json.loads(gen.EXCEPTIONS_PATH.read_text(encoding="utf-8"))
    assert exceptions["checked"] == 414
    assert exceptions["exception_count"] == 0
    assert exceptions["exceptions"] == []


def test_manifest_has_no_run_timings_but_performance_does() -> None:
    """The manifest must stay byte-reproducible; timings live elsewhere."""

    manifest = _manifest()
    assert "timing" not in manifest
    assert "generation_seconds" not in manifest
    perf = json.loads(PERFORMANCE_PATH.read_text(encoding="utf-8"))
    assert perf["glb_count"] == 414
    assert perf["generation_seconds"] > 0
    assert perf["per_glb_ms_mean"] > 0
    assert perf["glb_bytes_total"] == manifest["totals"]["glb_bytes"]


def test_manifest_totals_match_real_bytes() -> None:
    manifest = _manifest()
    records = manifest["buildings"]
    total = sum((VALIDATION_DIR / r["glb"]).stat().st_size for r in records)
    assert manifest["totals"]["glb_count"] == 414
    assert manifest["totals"]["glb_bytes"] == total
    assert manifest["totals"]["glb_bytes_min"] == min(
        r["glb_bytes"] for r in records
    )
    assert manifest["totals"]["glb_bytes_max"] == max(
        r["glb_bytes"] for r in records
    )


# --------------------------------------------------------------------------
# Catalog contract
# --------------------------------------------------------------------------


def test_catalog_fragment_satisfies_strict_contract() -> None:
    fragment = _fragment()
    entries = fragment["building_render"]
    assert len(entries) == 414
    assert fragment["schema_version"] == "aero-bench.urban-world-authoring/v1"
    assert fragment["section"] == "building_render"

    for entry in entries:
        model = CatalogBuildingRender.model_validate(entry)
        assert model.source_frame == "asset_local"
        assert model.media_type == RENDER_MEDIA_TYPE
        assert model.path == f"world/building-render/{model.object_id}.glb"
        assert (VALIDATION_DIR / model.file).is_file()
        assert model.provenance.runtime_download is False
        assert model.provenance.source_kind == "bundled_offline"


def test_catalog_rejects_gltf_labelled_wgs84() -> None:
    entry = dict(_fragment()["building_render"][0])
    entry["source_frame"] = "WGS84"
    with pytest.raises(ValueError):
        CatalogBuildingRender.model_validate(entry)


def test_glb_digests_pin_real_bytes() -> None:
    fragment = _fragment()
    digests = fragment["glb_digests"]
    manifest = {r["object_id"]: r for r in _manifest()["buildings"]}
    assert len(digests) == 414
    for object_id, digest in digests.items():
        path = VALIDATION_DIR / manifest[object_id]["glb"]
        assert validate.sha256_file(path) == digest["sha256"]
        assert path.stat().st_size == digest["bytes"]
        assert digest["style_id"] == manifest[object_id]["style_id"]


# --------------------------------------------------------------------------
# Style policy
# --------------------------------------------------------------------------


def test_only_audited_styles_are_used(styles: dict) -> None:
    manifest = _manifest()
    usage = manifest["style_usage"]
    audit = {r["style_id"]: r for r in manifest["style_audit"]}
    assert manifest["totals"]["styles_used"] == sum(1 for c in usage.values() if c)
    for style_id, count in usage.items():
        assert count > 0
        assert audit[style_id]["status"] == "accepted"
        assert style_id in styles
        assert audit[style_id]["wrap_seam_ratio"] <= gen.GATES["seam_ratio_max"]
    # the rejected cell is recorded, never referenced by any building
    rejected = [s for s, r in audit.items() if r["status"] == "rejected"]
    assert rejected, "expected at least one cell to fail the seam audit by design"
    for style_id in rejected:
        assert style_id not in usage
        for record in manifest["buildings"]:
            assert record["style_id"] != style_id


def test_assignment_obeys_height_pools(styles: dict) -> None:
    manifest = _manifest()
    pools = {name: set(pool) for name, _, pool in gen.HEIGHT_POOLS}
    for record in manifest["buildings"]:
        assert record["style_id"] in pools[record["height_class"]]


def test_assignment_is_order_independent(styles: dict) -> None:
    buildings = _objects()["buildings"]
    baseline = gen.assign_styles(buildings, styles)
    assert len(baseline) == 414
    for permutation in (
        list(reversed(buildings)),
        sorted(buildings, key=lambda b: b["object_id"], reverse=True),
        sorted(buildings, key=lambda b: b["object_id"]),
    ):
        assert gen.assign_styles(permutation, styles) == baseline
    # and it matches the manifest for every building
    for record in _manifest()["buildings"]:
        expect = baseline[record["object_id"]]
        assert record["style_id"] == expect["style_id"]
        assert record["height_class"] == expect["height_class"]


def test_embedded_glb_style_blocks_match_policy(styles: dict) -> None:
    manifest = {r["object_id"]: r for r in _manifest()["buildings"]}
    assignment = gen.assign_styles(_objects()["buildings"], styles)
    for object_id, record in list(manifest.items())[:24]:
        doc, _binary, _stats = validate.parse_glb(VALIDATION_DIR / record["glb"])
        extras = doc["asset"]["extras"]
        style = styles[record["style_id"]]
        expect = assignment[object_id]
        assert extras["style"]["style_id"] == record["style_id"]
        assert extras["style"]["region_px"] == style["region_px"]
        assert extras["style"]["wrap_seam_ratio"] == style["wrap_seam_ratio"]
        assert extras["style"]["assignment"]["height_class"] == expect["height_class"]
        assert extras["style"]["assignment"]["pool_index"] == expect["pool_index"]
        assert extras["style"]["assignment"]["rule"] == gen.ASSIGNMENT_RULE
        assert extras["source_frame"] == "asset_local"
        assert doc["nodes"][0]["name"] == object_id


def test_explicit_scene_reference_is_embedded(styles: dict, tmp_path: Path) -> None:
    building = _sample_building()
    assignment = gen.assign_styles([building], styles)[building["object_id"]]
    scene_reference = "validation/region/jingan/interchange-5dcc716a"
    glb = gen.generate_glb(
        object_id=building["object_id"],
        footprint=[tuple(point) for point in building["footprint_enu_m"]],
        base_up=float(building["base_enu_up_m"]),
        top_up=float(building["top_enu_up_m"]),
        style=styles[assignment["style_id"]],
        assignment=assignment,
        scene_origin=_objects()["origin"],
        height_source=building["height_source"],
        objects_sha256=validate.sha256_file(validate.OBJECTS_PATH),
        scene_reference=scene_reference,
    )
    path = tmp_path / "building.glb"
    path.write_bytes(glb)
    doc, _binary, _stats = validate.parse_glb(path)
    assert doc["asset"]["extras"]["scene"]["scene_root"] == scene_reference


def test_all_glbs_use_standard_pbr_fields() -> None:
    manifest = _manifest()
    for record in manifest["buildings"]:
        doc, _binary, _stats = validate.parse_glb(VALIDATION_DIR / record["glb"])
        problems = validate._pbr_problems(doc["materials"])
        assert problems == [], f"{record['object_id']}: {problems}"


def test_pbr_check_rejects_the_invalid_key() -> None:
    """Negative control: the non-spec key must be flagged, not ignored."""

    doc, _binary, _stats = validate.parse_glb(
        VALIDATION_DIR / _manifest()["buildings"][0]["glb"]
    )
    materials = copy.deepcopy(doc["materials"])
    assert validate._pbr_problems(materials) == []

    materials[0]["pbrMetallicRoughness"]["metallicRoughnessFactor"] = [0.0, 0.5]
    problems = validate._pbr_problems(materials)
    assert any("metallicRoughnessFactor" in p for p in problems)

    materials = copy.deepcopy(doc["materials"])
    materials[0]["pbrMetallicRoughness"]["metallicFactor"] = 1.0
    problems = validate._pbr_problems(materials)
    assert any("metallicFactor" in p for p in problems)

    materials = copy.deepcopy(doc["materials"])
    materials[1]["pbrMetallicRoughness"]["roughnessFactor"] = 1.0
    problems = validate._pbr_problems(materials)
    assert any("roughnessFactor" in p for p in problems)


# --------------------------------------------------------------------------
# Fail-closed paths (negative tests, no fake assets)
# --------------------------------------------------------------------------


def test_non_simple_footprints_are_rejected() -> None:
    open_ring = [(0.0, 0.0), (10.0, 0.0), (10.0, 10.0), (0.0, 10.0)]
    with pytest.raises(gen.ScaleoutError, match="non_simple_polygon"):
        gen.validate_footprint("test.open", open_ring)

    spike = [(0.0, 0.0), (10.0, 0.0), (10.0, 10.0), (5.0, -4.0), (0.0, 10.0), (0.0, 0.0)]
    with pytest.raises(gen.ScaleoutError, match="non_simple_polygon"):
        gen.validate_footprint("test.spike", spike)

    bowtie = [(0.0, 0.0), (10.0, 10.0), (10.0, 0.0), (0.0, 10.0), (0.0, 0.0)]
    with pytest.raises(gen.ScaleoutError, match="non_simple_polygon"):
        gen.validate_footprint("test.bowtie", bowtie)

    duplicate = [(0.0, 0.0), (10.0, 0.0), (0.0, 0.0), (10.0, 10.0), (0.0, 0.0)]
    with pytest.raises(gen.ScaleoutError, match="non_simple_polygon"):
        gen.validate_footprint("test.duplicate", duplicate)

    # the validator's independent detector agrees
    assert validate._footprint_simple(spike)[0] is False
    assert validate._footprint_simple(bowtie)[0] is False
    assert validate._footprint_simple(open_ring)[0] is False
    assert validate._footprint_simple([(0.0, 0.0), (10.0, 0.0), (10.0, 10.0), (0.0, 10.0), (0.0, 0.0)])[0] is True

    # every real footprint passes both detectors
    for building in _objects()["buildings"]:
        ring = [tuple(p) for p in building["footprint_enu_m"]]
        gen.validate_footprint(building["object_id"], ring)
        assert validate._footprint_simple(ring)[0] is True


def _glb_kwargs(building: dict) -> dict:
    ring = [tuple(p) for p in building["footprint_enu_m"]]
    return {
        "object_id": building["object_id"],
        "footprint": ring,
        "base_up": float(building["base_enu_up_m"]),
        "top_up": float(building["top_enu_up_m"]),
        "style": {
            "style_id": "probe_style",
            "atlas_set": "modern",
            "label": "probe crop (region under test)",
            "cell_px": [0, 0, 330, 333],
            "region_px": [16, 16, 256, 256],
            "wrap_seam_ratio": 0.5,
        },
        "assignment": {
            "style_id": "probe_style",
            "height_class": "low_lt20",
            "pool_index": 0,
            "pool_size": 5,
        },
        "scene_origin": _objects()["origin"],
        "height_source": building["height_source"],
        "objects_sha256": validate.sha256_file(validate.OBJECTS_PATH),
    }


def test_missing_texture_fails_closed(tmp_path, monkeypatch) -> None:
    monkeypatch.setattr(gen, "IMAGE_DIR", tmp_path)  # no atlases here
    with pytest.raises(gen.ScaleoutError, match="missing_texture"):
        gen.generate_glb(**_glb_kwargs(_sample_building()))
    assert list(tmp_path.iterdir()) == []


def test_missing_material_fails_closed(tmp_path, monkeypatch) -> None:
    # atlases are present, the Unity .mat file is not
    monkeypatch.setattr(gen, "MATERIAL_DIR", tmp_path)
    with pytest.raises(gen.ScaleoutError, match="missing_material"):
        gen.generate_glb(**_glb_kwargs(_sample_building()))


def test_size_mismatch_fails_closed() -> None:
    building = _sample_building()
    ring = [tuple(p) for p in building["footprint_enu_m"]]
    sdf_text = validate.SDF_PATH.read_text(encoding="utf-8")
    sdf = validate._sdf_entry(sdf_text, building["object_id"])
    base = float(building["base_enu_up_m"])
    top = float(building["top_enu_up_m"])

    doc, binary, _stats = validate.parse_glb(
        VALIDATION_DIR / f"assets/{building['object_id']}.glb"
    )
    positions = validate._gltf_positions(doc, binary)
    mins, maxs = validate._bbox(positions)

    # ground truth agrees
    assert validate._bbox_problems(
        building["object_id"], ring, base, top, sdf, mins, maxs
    ) == []
    gen.cross_check_bbox(building["object_id"], building, sdf, (mins, maxs))

    # a 5 cm taller GLB must be rejected
    scaled_maxs = list(maxs)
    scaled_maxs[1] += 0.05
    problems = validate._bbox_problems(
        building["object_id"], ring, base, top, sdf, mins, scaled_maxs
    )
    assert problems and any("Y/top" in p for p in problems)
    with pytest.raises(gen.ScaleoutError, match="size_mismatch"):
        gen.cross_check_bbox(
            building["object_id"], building, sdf, (mins, scaled_maxs)
        )

    # an SDF collision that disagrees with objects.json must be rejected
    bad_sdf = dict(sdf)
    bad_sdf["height"] = sdf["height"] + 0.05
    problems = validate._bbox_problems(
        building["object_id"], ring, base, top, bad_sdf, mins, maxs
    )
    assert problems and any("SDF height" in p for p in problems)
    with pytest.raises(gen.ScaleoutError, match="size_mismatch"):
        gen.cross_check_bbox(building["object_id"], building, bad_sdf, (mins, maxs))

    # a footprint whose polyline drifted must be rejected
    bad_sdf = dict(sdf)
    drift = list(sdf["points"])
    drift[0] = (drift[0][0] + 0.05, drift[0][1])
    bad_sdf["points"] = drift
    problems = validate._bbox_problems(
        building["object_id"], ring, base, top, bad_sdf, mins, maxs
    )
    assert problems and any("polyline" in p for p in problems)


def test_count_mismatch_fails_closed(tmp_path, monkeypatch) -> None:
    """A scene that is not 414 buildings aborts before any GLB is written."""

    monkeypatch.setattr(gen, "EXPECTED_BUILDING_COUNT", 413)
    with pytest.raises(gen.ScaleoutError, match="count_mismatch"):
        gen.generate(tmp_path / "assets", artifact_dir=tmp_path)
    assets = tmp_path / "assets"
    assert (list(assets.glob("*.glb")) if assets.exists() else []) == []
    # checked-in artifacts are untouched (the run wrote into the sandbox)
    assert json.loads(gen.EXCEPTIONS_PATH.read_text(encoding="utf-8"))[
        "exception_count"
    ] == 0


def test_unknown_sdf_model_fails_closed() -> None:
    objects = _objects()
    object_ids = [b["object_id"] for b in objects["buildings"]]
    sdf_text = validate.SDF_PATH.read_text(encoding="utf-8")
    # an unexpected Gazebo model name can never be silently accepted
    with pytest.raises(gen.ScaleoutError, match="size_mismatch"):
        gen.parse_sdf(sdf_text + '<model name="not_a_building"><collision>'
                      '<geometry><polyline><height>1.0</height>'
                      '<point>0.0 0.0</point></polyline></geometry>'
                      '</collision></model>', object_ids)
