"""Extend the single scenario projection with explicitly authored space-time authority."""
def extend(ns,node,edge,N,E,kinds):
 kinds.update({'spatial_zone':('空域/航道','Airspace/corridor','world','spatial_zones'),'route_plan':('航线计划','Route plan','decision',None),'lease_request':('航道时隙申请','Corridor lease request','decision','lease_requests'),'lease_approval':('航道审批记录','Corridor approval','decision','lease_approvals'),'space_time_allocation':('空间-时间分配','Space-time allocation','rules','space_time_allocations'),'delivery_receipt':('通信送达回执','Message delivery receipt','feedback','delivery_receipts')})
 node('type.edge_server','entity_type','边缘服务器类型','Edge-server type','world','物理计算设备类型。','Physical computing-device class.')
 node('edge_server','entity','边缘服务器 E','Edge server E','world','物理承载设备，不等于航道管理代理或计算模块。','Physical host, distinct from its corridor-management agent and compute module.',entity_type=ns+'type.edge_server')
 edge('edge_server','type.edge_server','instance_of','class')
 node('edge_agent','agent','边缘航道管理代理','Edge corridor-management agent','decision','独立决策者。按演练范围审核无人机申请，分配空间和时间；紧急情况不自动提升优先级。','Independent decision-maker. Reviews the UAV request and allocates space and time under the exercise scope. No automatic emergency priority.',authority={'actor':ns+'edge_agent','target':ns+'corridor','operations':['approve','deny','allocate_time_window'],'source':ns+'policy','valid_s':[0,120]})
 node('edge_strategy','strategy','航道时隙审批策略','Corridor-slot approval strategy','decision','检查禁飞区、容量、方向、有效时间和请求范围。批准决定与通信送达分别记录。','Checks no-fly geometry, capacity, direction, validity and request scope. Approval and delivered authorization remain separate.')
 edge('edge_agent','edge_strategy','calls_strategy','corridor_admission');edge('edge_agent','edge_server','hosted_on','physical_host',extension=True)
 node('corridor','spatial_zone','航道 C · 分时使用','Corridor C · time allocated','world','虚构 ENU 航道，多边形覆盖合法绕飞路径；高度 12–18 m，双向定义、每次分配单向、容量 1，必须有审批。','Fictional ENU corridor around the legal detour: altitude 12–18 m, bidirectional definition with direction-scoped leases, capacity 1, approval required.',kind_detail='corridor',geometry={'frame':'ENU','axis_order':'east_north','unit':'m','geometry_type':'polygon','coordinates':[[-3,-3],[3,-3],[3,12],[33,12],[33,18],[-3,18],[-3,-3]]},altitude={'min_m':12,'max_m':18},time_windows=[{'start_ns':'0','end_ns':'120000000000'}],direction='bidirectional',access='approval_required',authority_agent_ids=[ns+'edge_agent'],capacity_slots=1,source_id=ns+'policy')
 node('no_fly','spatial_zone','禁飞区 N · 禁止进入','No-fly zone N · prohibited','world','虚构禁飞多边形，0–50 m，高度和时间范围都有效。异常记录不允许穿越。','Fictional prohibited polygon, altitude 0–50 m and active interval. Incident response does not authorize crossing.',kind_detail='no_fly_zone',geometry={'frame':'ENU','axis_order':'east_north','unit':'m','geometry_type':'polygon','coordinates':[[15,0],[23,0],[23,8],[15,8],[15,0]]},altitude={'min_m':0,'max_m':50},time_windows=[{'start_ns':'0','end_ns':'120000000000'}],direction='bidirectional',access='prohibited',authority_agent_ids=[ns+'edge_agent'],capacity_slots=0,source_id=ns+'policy')
 node('route','route_plan','合法绕飞航线 · 计划','Legal detour · planned route','decision','计划绕过禁飞区，经有时隙授权的航道到达观察区域。计划不等于实际飞行证据。','Planned detour avoids no-fly geometry and uses the allocated corridor to reach the observation region. A plan is not actual motion.',frame='local_ENU',unit='m',waypoints=[[0,0,15],[0,15,15],[30,15,15],[35,12,15]],planned_interval_s=[16,20],actual_motion_ref=ns+'fact.pose',rejected_direct_path=[[0,0,15],[35,12,15]],geometry_verification='static 2D synthetic geometry test only; not trajectory physics')
 edge('route','corridor','uses_corridor','authorized_transit',extension=True);edge('route','no_fly','avoids_zone','prohibited_geometry',extension=True)
 node('request','lease_request','上报异常 + 申请改道','Report incident + request reroute','decision','无人机代理通过通信模块上报计算推断并申请航道时段。发出申请不等于已获授权。','UAV agent reports the computed observation over communications and requests a corridor interval. Sending is not approval.',record_kind='fixture_lease_request',agent_id=ns+'agent',entity_ids=[ns+'uav'],zone_id=ns+'corridor',requested_window={'start_ns':'16000000000','end_ns':'22000000000'},requested_altitude={'min_m':12,'max_m':18},direction='forward',issued_at_ns='12200000000',purpose='synthetic incident capture from safe region',source_id=ns+'policy')
 node('report_receipt','delivery_receipt','上报已到达边缘端','Report delivered to edge','feedback','13 s 的合成网络送达回执，仅证明请求到达，不是航道许可。','Synthetic delivery at 13 s proves request arrival, not corridor authorization.',receipt_kind='message_delivery',sender_entity_id=ns+'uav',receiver_entity_id=ns+'edge_server',status='acknowledged',emitted_at_ns='12200000000',received_at_ns='13000000000',message_ref=ns+'request',source_id=ns+'evidence')
 node('approval','lease_approval','边缘批准 · 16–22 s','Edge approval · 16–22 s','decision','14 s 作出审批，只对该无人机、航道、方向、高度和时窗有效。未收到批准、过期或拒绝都不能改道。','Approval at 14 s is scoped to this UAV, corridor, direction, altitude and interval. Missing, expired or denied approval never permits diversion.',record_kind='fixture_lease_approval',request_id=ns+'request',authority_agent_id=ns+'edge_agent',decision='approved',approved_window={'start_ns':'16000000000','end_ns':'22000000000'},approved_altitude={'min_m':12,'max_m':18},constraint_ids=[ns+'constraint.airspace',ns+'constraint.lease'],issued_at_ns='14000000000',evidence_receipt_ids=[ns+'report_receipt'],source_id=ns+'policy')
 node('grant_receipt','delivery_receipt','批准已收到 @15 s','Grant received @15 s','feedback','确认无人机收到完整、有作用域的批准消息。服务器批准本身不能代替通信到达。','The UAV has received the complete scoped grant. A server-side approval cannot replace delivery evidence.',receipt_kind='message_delivery',sender_entity_id=ns+'edge_server',receiver_entity_id=ns+'uav',status='acknowledged',emitted_at_ns='14100000000',received_at_ns='15000000000',message_ref=ns+'approval',source_id=ns+'evidence')
 node('allocation','space_time_allocation','空间-时间分配 · 槽 1','Space-time allocation · slot 1','rules','C 航道在 [16,22) s 内分配给 UAV A，高度 12–18 m、正向、1 个容量槽；相邻预约不得被覆盖。','Corridor C allocated to UAV A in [16,22) s, altitude 12–18 m, forward, one slot. Neighboring reservations cannot be overwritten.',record_kind='fixture_space_time_allocation',approval_id=ns+'approval',zone_id=ns+'corridor',entity_ids=[ns+'uav'],window={'start_ns':'16000000000','end_ns':'22000000000'},altitude={'min_m':12,'max_m':18},direction='forward',slots=1,status='declared',source_id=ns+'policy',interval_boundary='left_closed_right_open')
 for id,zh,en,desc in [('constraint.airspace','禁飞区 / 航道几何检查','No-fly / corridor geometry','Route must avoid no-fly geometry and use valid direction/altitude.'),('constraint.lease','批准已达 + 时窗内','Grant received + inside window','Require matching received approval and current allocation. Before 16 s wait; at or after 22 s cannot enter.'),('constraint.vehicle','飞行能力 + 返航能量','Flight capability + return energy','Require support, single motion slot and reserved return energy; a corridor grant alone proves none of these.')]:
  node(id,'constraint',zh,en,'rules',{'constraint.airspace':'第一道门：几何、禁飞范围和适用权限；不因异常自动豁免。','constraint.lease':'第二道门：正确主体收到审批、时窗有效、方向和高度匹配、容量无冲突。','constraint.vehicle':'第三道门：无人机能力、资源和能量；航道获批不证明飞机一定可飞。'}[id],desc,source=ns+'policy',applicability='applicable',enforcement='authored prestart/continuation guard')
  edge(id,'policy','based_on_policy','authored_exercise_source',extension=True);edge(id,'strategy','input_to','applicable_constraint');edge('check',id,'uses_constraint','pre_diversion_and_continuation',level='runtime');edge('behavior.approach',id,'constrained_by','hard_gate');edge(id,'edge_strategy','input_to','applicable_constraint')
 edge('agent','perception','calls_module','compute_incident_inference',extension=True);edge('perception','fact.incident','produces_observation','reported_fall_confidence',level='runtime',extension=True)
 edge('agent','request','submits_request','corridor_reroute',level='runtime',extension=True);edge('request','ns3','transmitted_by','incident_report_and_application',extension=True)
 edge('report_receipt','request','receipt_for_message','request_transport',level='runtime',extension=True);edge('report_receipt','edge_agent','feeds_back','delivered_application',level='runtime',extension=True)
 edge('request','edge_strategy','input_to','request',level='runtime');edge('edge_strategy','approval','produces_approval','authored_decision',level='runtime',extension=True);edge('approval','request','responds_to','corridor_request',level='runtime',extension=True)
 edge('approval','allocation','authorizes_allocation','scoped_window',level='runtime',extension=True);edge('allocation','corridor','allocates','space_time_capacity',level='runtime',extension=True);edge('allocation','uav','assigned_to','authorized_vehicle',level='runtime',extension=True)
 edge('grant_receipt','approval','receipt_for_message','approval_transport',level='runtime',extension=True);edge('grant_receipt','agent','feeds_back','received_permission',level='runtime',extension=True)
 edge('check','grant_receipt','requires_receipt','received_approval',level='runtime',extension=True);edge('check','allocation','requires_allocation','current_corridor_lease',level='runtime',extension=True);edge('route','allocation','requires_allocation','space_time_transit',extension=True)
 edge('command','route','follows_plan','requested_motion_path',level='runtime',extension=True);edge('behavior.approach','allocation','requires_allocation','admitted_transit',extension=True)
 # Failure recovery is separately authorized; initial outbound approval never covers return.
 node('return_request','lease_request','失败后申请返航时隙','Request return slot after failure','decision','42.1 s 重新申请反向航道，不复用过期的去程批准。','Request reverse transit at 42.1 s; never reuse the expired outbound grant.',record_kind='fixture_lease_request',agent_id=ns+'agent',entity_ids=[ns+'uav'],zone_id=ns+'corridor',requested_window={'start_ns':'44000000000','end_ns':'78000000000'},requested_altitude={'min_m':12,'max_m':18},direction='reverse',issued_at_ns='42100000000',purpose='return parcel after failed incident upload',source_id=ns+'policy',active_branch='failure')
 node('return_approval','lease_approval','返航另获批准','Separate return approval','decision','42.5 s 对反向 [44,78) s 授权；这是新的审批，不是紧急豁免。','New approval at 42.5 s for reverse [44,78) s. Not an emergency exception.',record_kind='fixture_lease_approval',request_id=ns+'return_request',authority_agent_id=ns+'edge_agent',decision='approved',approved_window={'start_ns':'44000000000','end_ns':'78000000000'},approved_altitude={'min_m':12,'max_m':18},constraint_ids=[ns+'constraint.airspace',ns+'constraint.lease'],issued_at_ns='42500000000',evidence_receipt_ids=[],source_id=ns+'policy',active_branch='failure')
 node('return_grant_receipt','delivery_receipt','返航批准收到 @43 s','Return grant received @43 s','feedback','合成回执确认新返航许可已送达；仍须等到 44 s 才进入航道。','Synthetic receipt confirms the new grant. Entry still waits until 44 s.',receipt_kind='message_delivery',sender_entity_id=ns+'edge_server',receiver_entity_id=ns+'uav',status='acknowledged',emitted_at_ns='42600000000',received_at_ns='43000000000',message_ref=ns+'return_approval',source_id=ns+'evidence',active_branch='failure')
 node('return_allocation','space_time_allocation','返航时隙 · 44–78 s','Return slot · 44–78 s','rules','新反向预约与 [16,22) s 去程不重叠，保留原记录，不覆盖。','New reverse reservation does not overlap [16,22) s outbound allocation. Preserve both records.',record_kind='fixture_space_time_allocation',approval_id=ns+'return_approval',zone_id=ns+'corridor',entity_ids=[ns+'uav'],window={'start_ns':'44000000000','end_ns':'78000000000'},altitude={'min_m':12,'max_m':18},direction='reverse',slots=1,status='declared',source_id=ns+'policy',active_branch='failure')
 edge('return_approval','return_request','responds_to','new_return_request',level='runtime',extension=True);edge('return_approval','return_allocation','authorizes_allocation','new_reverse_window',level='runtime',extension=True);edge('return_allocation','corridor','allocates','reverse_transit',level='runtime',extension=True);edge('return_grant_receipt','return_approval','receipt_for_message','return_grant_transport',level='runtime',extension=True);edge('exec.return','return_grant_receipt','requires_receipt','new_received_grant',level='runtime',extension=True);edge('exec.return','return_allocation','requires_allocation','reverse_space_time_window',level='runtime',extension=True)
 # Fix earlier samples and labels to the grant-gated timeline.
 for n in N:
  id=n['id'].removeprefix(ns)
  if id=='fact.target':n.update(valid_time_s=16,available_time_s=16.1,valid_until_s=38)
  if id=='decision':n.update(chosen_at_s=16,description={'zh':'收到审批且进入时窗后三重检查放行，再替换唯一运动目标；13 s 已暂停原配送任务。','en':'After grant receipt and opening of the time window, three gates permit one replacement motion target. Delivery was paused at 13 s.'})
  if id=='invocation':n.update(label={'zh':'获批后重规划 @16 s','en':'Replan after grant @16 s'},query_s=16,available_cutoff_s=16,description={'zh':'接收批准与有效时窗是本次调用的输入；12.1 s 初次判断只发申请，不能提前改道。','en':'Received grant and valid interval are inputs. The initial 12.1 s review only requests approval; no early diversion.'})
  if id=='check':n['checks']=[{'at_s':15,'scope':'before_window','verdict':'BLOCK','reason':'not_yet_valid'},{'at_s':16,'scope':'before_approach','verdict':'PERMIT','requires':[ns+'grant_receipt',ns+'allocation',ns+'constraint.airspace',ns+'constraint.vehicle']},{'at_s':20.1,'scope':'before_capture_outside_transit_corridor','verdict':'PERMIT','fact_ref':ns+'fact.separation'},{'at_s':22.1,'scope':'before_upload_and_hold_outside_corridor','verdict':'PERMIT','authorization_ref':ns+'policy'}]
  if id=='receipt':
   n['records'][0]={'operation':'approach','accepted_s':16,'applied_s':16.1,'complete_s':20};n['description']={'zh':'先收到审批，再在 16 s 接受观察点目标，20 s 到达走廊外观察点；22 s 完成拍摄；上传需等接收回执。','en':'Receive the grant, accept the target at 16 s and reach an observation point outside the transit corridor at 20 s. Capture completes at 22 s; upload needs acknowledgement.'}
  if id=='fact.pose':n['outside_transit_corridor']=True
  if id=='command':n['issued_at_s']=16
 # Decision invocation reads the actual approval delivery separately from the observation.
 edge('invocation','grant_receipt','reads_receipt','received_grant',level='runtime',extension=True)
 return {
 'granted':{'zh':'授权内绕飞','en':'Granted detour','verdict':'PERMIT','at_s':16,'approval':'approved','receipt':'acknowledged','allocation':'valid','description_zh':'上报 13 s 到达 → 14 s 批准 → 15 s 收到 → 16 s 时窗打开 → 合法绕飞 → 20 s 到观察点。','description_en':'Report arrives 13 s → approved 14 s → grant received 15 s → window opens 16 s → legal detour → observation point 20 s.','may_divert':True},
 'before_window':{'zh':'尚未到时窗','en':'Before window','verdict':'BLOCK','at_s':15.5,'approval':'approved','receipt':'acknowledged','allocation':'not_yet_valid','description_zh':'15.5 s 已收到批准，但 [16,22) s 时窗未开始。配送暂停，禁止进入航道；这不是许可失败。','description_en':'Grant received at 15.5 s, but [16,22) s has not begun. Delivery paused; corridor entry blocked. Approval itself has not failed.','may_divert':False},
 'denied':{'zh':'边缘拒绝 / 无可达航线','en':'Denied / unreachable route','verdict':'BLOCK','at_s':15,'approval':'rejected','receipt':'acknowledged','allocation':'none','description_zh':'边缘端拒绝改道：当前没有满足禁飞区与容量的可达航线。不拍摄、不新增上传；保留包裹，按既有授权安全重规划。','description_en':'Edge denies reroute: no reachable route satisfies no-fly and capacity constraints. No capture or new upload. Keep the parcel and replan within existing authority.','may_divert':False},
 'missing':{'zh':'批准消息未到','en':'Grant message missing','verdict':'UNKNOWN','at_s':16,'approval':'approved_server_side_only','receipt':'UNKNOWN','allocation':'not_usable','description_zh':'服务器已批准，但无人机没有可靠送达回执。UNKNOWN 不放行；原配送暂停，禁止把服务器记录当作已知权限。','description_en':'Server approval exists, but UAV has no reliable delivery receipt. UNKNOWN does not admit diversion. Delivery paused; server state is not known authority.','may_divert':False},
 'expired':{'zh':'时隙已过期','en':'Lease expired','verdict':'BLOCK','at_s':22,'approval':'approved','receipt':'acknowledged','allocation':'expired','description_zh':'22 s 已到右开区间终点，旧授权不可再次进入。不覆盖其他时隙预约；需新申请和新的送达证据。','description_en':'At 22 s the half-open interval has ended. No new entry on the old grant. Do not overwrite other reservations; require a new application and delivery evidence.','may_divert':False}}
