import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Alert, Button, Card, Checkbox, Dropdown, Input, InputNumber, Modal, Select, Space, Tag, Tooltip } from 'antd';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useConsoleNotice } from '../console/Notifications';
import { PageHeader, PageState } from '../console/PageState';
import { Details } from '../console/Details';
import { ConceptHelp } from '../console/ConceptHelp';
import { StudioApi, type Workspace, type TypeRow } from './api';
import { ScenePreview } from './ScenePreview';
import { RegionMap } from './RegionMap';
import type { EngineDescriptor } from './PluginOwnershipPanel';
import { EntitiesStep } from './steps/EntitiesStep';
import { DomainPluginsStep } from './steps/DomainPluginsStep';
import { PredicatesStep } from './steps/PredicatesStep';
import { RulesStep } from './steps/RulesStep';
import { AgentsStep } from './steps/AgentsStep';
import { parseAuthoringJson } from '../feeds/lossless-json';
import { recentWorkspaces, workspaceUpdated } from './workspace-list';
import { issueStep, readableName, studioSteps, validationIssues, type StudioStep, type StudioIssue } from './guided-model';
import './studio.css';
import './guided.css';

const stepHelp: Record<StudioStep,{description:string;guide:string}> = {
 scene:{description:'The scene binds geographic geometry and actor placement to the simulation views.',guide:'console.md'},
 entities:{description:'Entities have AeroGraph types, inherited state fields and typed relationships.',guide:'console.md'},
 plugins:{description:'Domain plugins are replaceable engines; each state field has exactly one writer.',guide:'RUNTIME.md'},
 predicates:{description:'Predicates evaluate typed conditions that can trigger behaviour transitions.',guide:'predicates.md'},
 rules:{description:'Bindings start event chains; guarded transitions advance them and execute actions.',guide:'behaviours.md'},
 agents:{description:'Decision agents propose actions through the same commands and ownership rules as other plugins.',guide:'langgraph.md'},
 validate:{description:'Validation checks the complete draft before creating a run with its own recorded timeline.',guide:'console.md'},
};
interface Catalog {demo_profiles?:Record<string,Record<string,unknown>>;extracts:Array<{id:string;name:string;bounds:number[]}>;engines:EngineDescriptor[]}
export default function StudioPage() {
 const location=useLocation(),navigate=useNavigate(),notify=useConsoleNotice();
 const base=new URLSearchParams(location.search).get('api') ?? window.location.origin;
 const api=useMemo(()=>new StudioApi(base),[base]);
 const [catalog,setCatalog]=useState<Catalog>(),[workspaces,setWorkspaces]=useState<Workspace[]>([]),[workspace,setWorkspace]=useState<Workspace>();
 const [types,setTypes]=useState<TypeRow[]>([]),[fields,setFields]=useState<Record<string,unknown>[]>([]),[relations,setRelations]=useState<Record<string,unknown>[]>([]);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[step,setStep]=useState<StudioStep>('scene'),[visited,setVisited]=useState<Set<StudioStep>>(new Set(['scene']));
 const [validity,setValidity]=useState<Record<string,boolean>>({}),[dirty,setDirty]=useState(false),[yaml,setYaml]=useState(''),[raw,setRaw]=useState(''),[rawError,setRawError]=useState('');
 const [issuesOpen,setIssuesOpen]=useState(false),[focusIssue,setFocusIssue]=useState<StudioIssue>();
 const [extract,setExtract]=useState<string>(),[bounds,setBounds]=useState<number[]>([]),[alt,setAlt]=useState(0),[levelHeight,setLevelHeight]=useState(3),[layers,setLayers]=useState(['ground','buildings','roads','entities','airspace']);
 const [placeId,setPlaceId]=useState(''),[placeType,setPlaceType]=useState<string>(),[placeEngine,setPlaceEngine]=useState<string>(),[position,setPosition]=useState([0,0,10]);
 const launch=useRef<string>();
 const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(problem){const message=String(problem);setError(message);notify({kind:'error',message});}finally{setBusy(false);}};
 const apply=(next:Workspace)=>{setWorkspace(next);setRaw(JSON.stringify(next.scenario,null,2));setRawError('');setDirty(false);if(next.region){setExtract(next.region.extract);setBounds(next.region.bounds);setAlt(next.region.alt);setLevelHeight(next.region.level_height_m);}setWorkspaces(previous=>recentWorkspaces([...previous.filter(row=>row.id!==next.id),next]));};
 const onChange=(scenario:Record<string,any>)=>{setWorkspace(current=>current?{...current,scenario,validation:undefined}:current);setRaw(JSON.stringify(scenario,null,2));setRawError('');setDirty(true);};
 const behaviourValidity=useCallback((valid:boolean)=>setValidity(current=>({...current,rules:valid})),[]);
 const predicateValidity=useCallback((valid:boolean)=>setValidity(current=>({...current,predicates:valid})),[]);
 const pluginValidity=useCallback((valid:boolean)=>setValidity(current=>({...current,plugins:valid})),[]);
 const chooseStep=(id:StudioStep)=>{setStep(id);setVisited(current=>new Set([...current,id]));setFocusIssue(undefined);};
 const openIssue=(issue:StudioIssue)=>{chooseStep(issueStep(issue));setFocusIssue(issue);setIssuesOpen(false);};
 const buffersValid=Object.values(validity).every(Boolean)&&!rawError;
 const save=async():Promise<Workspace>=>{if(!workspace)throw Error('Open a workspace first');if(!buffersValid)throw Error('Correct the invalid editor content before saving');const next=await api.request<Workspace>(`/v1/studio/workspaces/${workspace.id}`,{name:workspace.name,scenario:workspace.scenario});apply(next);return next;};
 const openDemo=async()=>{const created=await api.request<Workspace>('/v1/studio/workspaces',{name:'Traffic accident (demo)'});apply(await api.request<Workspace>(`/v1/studio/workspaces/${created.id}/templates/traffic-accident`,{console:true,capture_mode:'city'}));setValidity({});chooseStep('scene');};
 useEffect(()=>{let active=true;void Promise.all([api.request<Catalog>('/v1/studio/catalog'),api.request<Workspace[]>('/v1/studio/workspaces'),api.request<{types:TypeRow[];fields:Record<string,unknown>[];relations:Record<string,unknown>[]}>('/v1/studio/types?q=')]).then(([c,w,t])=>{if(!active)return;setCatalog(c);setWorkspaces(previous=>recentWorkspaces([...w,...previous]));setTypes(t.types);setFields(t.fields);setRelations(t.relations);}).catch(problem=>{if(active)setError(String(problem));});return()=>{active=false;};},[api]);
 useEffect(()=>{const query=new URLSearchParams(location.search),target=query.get('workspace'),key=`${base}/${location.search}`;if(launch.current===key||(!target&&query.get('template')!=='traffic-accident'))return;launch.current=key;void action(async()=>{if(target){const next=await api.request<Workspace>(`/v1/studio/workspaces/${encodeURIComponent(target)}`),entity=query.get('entity');if(entity&&!next.scenario.entities?.some((row:{id:string})=>row.id===entity))throw Error('The linked entity is absent from this workspace');apply(next);if(entity)chooseStep('entities');}else await openDemo();setValidity({});});},[api,location.search]);
 const scenario=workspace?.scenario;
 const mergeRows=<T extends {id:string}>(...rows:T[][]):T[]=>[...new Map(rows.flat().map(row=>[row.id,row])).values()];
 const allTypes=mergeRows(types,workspace?.registry_catalog?.types ?? [],scenario?.registry?.types ?? []);
 const allFields=mergeRows(fields as Array<Record<string,unknown>&{id:string}>,workspace?.registry_catalog?.fields ?? [],scenario?.registry?.fields ?? []);
 const allRelations=mergeRows(relations as Array<Record<string,unknown>&{id:string}>,scenario?.registry?.relations ?? []);
 const issues=validationIssues(workspace?.validation),currentStep=studioSteps.find(item=>item.id===step)!;
 const validate=async()=>{if(!workspace)throw Error('Open a workspace first');if(!buffersValid)throw Error('Correct the invalid editor content before validation');const result=await api.request<NonNullable<Workspace['validation']>>(`/v1/studio/workspaces/${workspace.id}/validate`,{scenario:workspace.scenario});const next=await api.request<Workspace>(`/v1/studio/workspaces/${workspace.id}`);apply({...next,validation:result});notify({kind:result.valid?'success':'error',message:result.valid?'Scenario valid. Ready to run.':'Validation found authoring errors.'});if(!result.valid){chooseStep('validate');}};
 const run=async()=>{if(!workspace?.validation?.valid||!buffersValid||dirty)throw Error('Validate this draft before starting a run');const receipt=await api.request<{id:string}>('/v1/runs',{scenario:workspace.scenario,studio_workspace:workspace.id});notify({kind:'success',message:'Run started.'});navigate(`/runs/${encodeURIComponent(receipt.id)}?api=${encodeURIComponent(base)}&mode=live`);};
 const selectedExtract=catalog?.extracts.find(item=>item.id===extract);
 const bindingsValid=workspace?.validation?.valid===true&&!dirty&&buffersValid;
 const issueList=(group:StudioStep)=><div className="guided-issues">{issues.filter(issue=>issueStep(issue)===group).map((issue,index)=><button key={index} className="guided-issue" onClick={()=>openIssue(issue)}><strong>{issue.message}</strong><span>Edit {studioSteps.find(item=>item.id===group)!.label.toLowerCase()}</span></button>)}</div>;
 const common=workspace?{workspace,api,save,onApply:apply,onChange}:undefined;
 return <div className="console-page guided-studio" data-testid="guided-studio">
  <PageHeader eyebrow="Studio · configuration" title={scenario?(scenario.title ?? (scenario.id==='traffic-accident'?'Traffic accident':readableName(scenario.id))):'Build a scenario'} description="Configure one AeroGraph scenario, validate its rules, and run it on the shared runtime." />
  {error&&<Alert type="error" showIcon message="Studio could not complete the request" description={error} closable onClose={()=>setError('')} />}
  <div className="guided-workspace-header">
   <div className="guided-workspace-name"><span className="guided-label">Workspace</span>{workspace?<Input aria-label="Workspace name" value={workspace.name} onChange={event=>{setWorkspace({...workspace,name:event.target.value});setDirty(true);}}/>:<strong>Select or create a workspace</strong>}<span className="guided-muted">{workspace?`${workspaceUpdated(workspace)}${dirty?' · Unsaved changes':''}`:'A saved draft holds the complete scenario.'}</span></div>
   <Space wrap><Dropdown trigger={['click']} menu={{items:recentWorkspaces(workspaces).map(item=>({key:item.id,label:<span className="guided-picker-item"><strong>{item.name}</strong><small>{workspaceUpdated(item)}</small></span>})),onClick:({key})=>void action(async()=>{apply(await api.request<Workspace>(`/v1/studio/workspaces/${key}`));setValidity({});chooseStep('scene');})}}><Button disabled={!workspaces.length||busy} data-testid="workspace-picker">Switch workspace ▾</Button></Dropdown>
    {!workspace&&<Button disabled={busy} onClick={()=>void action(openDemo)}>Open traffic demo</Button>}
    <Button disabled={!workspace||busy||!buffersValid} onClick={()=>void action(async()=>{await save();notify({kind:'success',message:'Workspace saved.'});})}>Save workspace</Button>
    <Button disabled={!workspace||busy||!buffersValid} onClick={()=>void action(validate)}>Validate</Button>
    <Tooltip title={!bindingsValid ? 'Validate first' : undefined}><span><Button type="primary" disabled={busy||!bindingsValid} onClick={()=>void action(run)}>Run now</Button></span></Tooltip>
   </Space>
  </div>
  {!workspace&&catalog&&<PageState kind="empty" title="Start with a scenario" description="Open the traffic accident demo, choose a saved workspace or create an empty draft." action={<Button onClick={()=>void action(async()=>{apply(await api.request<Workspace>('/v1/studio/workspaces',{name:'New research scenario'}));chooseStep('scene');})}>Create workspace</Button>}/>}
  {!catalog&&!error&&<PageState kind="loading" title="Loading configuration tools" description="Reading the AeroGraph catalog and installed domain engines."/>}
  {workspace&&catalog&&scenario&&common&&<>
   <div className="guided-studio-layout" key={workspace.id}>
    <nav className="guided-step-rail" aria-label="Configuration steps">{studioSteps.map((item,index)=>{const hasIssues=issues.some(issue=>issueStep(issue)===item.id);const status=hasIssues?'issues':bindingsValid?'valid':visited.has(item.id)?'opened':'pending';return <button key={item.id} data-testid={`studio-step-${item.id}`} aria-current={step===item.id?'step':undefined} onClick={()=>chooseStep(item.id)}><span className={`guided-status-dot guided-status-${status}`} aria-label={status}/><span><small>0{index+1}</small>{item.label}</span>{hasIssues&&<Tag color="error">{issues.filter(issue=>issueStep(issue)===item.id).length}</Tag>}</button>;})}<div className="guided-rail-footer"><button className="guided-validation-badge" data-testid="validation-status" onClick={()=>setIssuesOpen(true)}><Tag color={bindingsValid?'success':issues.length?'error':'default'}>{bindingsValid?'Validated':issues.length?`${issues.length} authoring issue${issues.length===1?'':'s'}`:'Not validated'}</Tag><span>Review scenario checks →</span></button><Details title="Scenario source" buttonLabel="YAML & details"><Space wrap><Button onClick={()=>void action(async()=>{const saved=await save();setYaml(await api.export(saved.id));})}>Export YAML</Button><Button disabled={!yaml||busy} onClick={()=>void action(async()=>{apply(await api.request<Workspace>(`/v1/studio/workspaces/${workspace.id}/import`,{yaml}));})}>Import YAML</Button></Space><Input.TextArea aria-label="Scenario YAML" rows={18} value={yaml} onChange={event=>setYaml(event.target.value)}/><h3>Scenario JSON</h3><Input.TextArea aria-label="Scenario editor" rows={16} value={raw} onChange={event=>{setRaw(event.target.value);setDirty(true);setWorkspace({...workspace,validation:undefined});try{const value=parseAuthoringJson(event.target.value);if(!value||Array.isArray(value)||typeof value!=='object')throw Error('Scenario must be an object');setWorkspace({...workspace,scenario:value as Record<string,any>,validation:undefined});setRawError('');}catch(problem){setRawError(String(problem));}}}/>{rawError&&<Alert type="error" message={rawError}/>}<pre>{JSON.stringify({workspace:workspace.id,validation:workspace.validation},null,2)}</pre></Details></div></nav>
    <main className="guided-step-content" aria-busy={busy}>
     <header className="guided-step-heading"><div><span className="guided-label">Step {studioSteps.findIndex(item=>item.id===step)+1} of 7</span><h2>{currentStep.label}<ConceptHelp topic={currentStep.label} description={stepHelp[step].description} guide={stepHelp[step].guide}/></h2><p>{currentStep.description}</p></div><Tag>{scenario.entities?.length ?? 'No'} entities</Tag></header>
     {focusIssue&&<Alert type="error" message={focusIssue.message} description={<Details title="Authored diagnostic"><pre>{focusIssue.path}</pre></Details>}/>}
     {visited.has('scene')&&<section hidden={step!=='scene'} data-testid="studio-panel-scene">
      <div className="guided-scene-layout"><Card title="Scene preview">{step==='scene'&&<ScenePreview workspace={workspace} api={base} layers={layers}/>}<Checkbox.Group aria-label="Visible scene layers" value={layers} options={['ground','buildings','roads','entities','airspace'].map(value=>({value,label:readableName(value)}))} onChange={values=>setLayers(values as string[])}/><p className="guided-muted">{workspace.scene?'Selected geographic region':workspace.demo_console?.city_available?'Traffic demo · original city geometry':'Draft scene · local east / north / up coordinates'}</p></Card>
       <Card title="Place an entity"><div className="guided-form"><label>Entity name<Input aria-label="Entity ID" value={placeId} onChange={event=>setPlaceId(event.target.value)} placeholder="e.g. survey-uav"/></label><label>AeroGraph type<Select aria-label="Placement type" showSearch optionFilterProp="label" value={placeType} onChange={setPlaceType} options={allTypes.map(row=>({value:row.id,label:row.name ?? readableName(row.id),disabled:row.abstract}))}/></label><label>Writer partition<Select aria-label="Placement engine" value={placeEngine} onChange={setPlaceEngine} options={Object.entries(scenario.engines ?? {}).filter(([,value]:any)=>['kinematic','workflow'].includes(value.plugin)).map(([id])=>({value:id,label:readableName(id)}))}/></label><div className="guided-coordinate-row">{['East','North','Up'].map((label,index)=><label key={label}>{label} (m)<InputNumber aria-label={label} value={position[index]} onChange={value=>{if(value!==null)setPosition(position.map((old,i)=>i===index?value:old));}}/></label>)}</div><Button disabled={!placeId||!placeType||!placeEngine||busy} onClick={()=>void action(async()=>{await save();apply(await api.request<Workspace>(`/v1/studio/workspaces/${workspace.id}/place`,{id:placeId,type:placeType,kind:'entity',engine:placeEngine,position,facts:{}}));setPlaceId('');})}>Place entity</Button><p className="guided-muted">Placement uses the selected engine’s authored template. Review its fields in Entities before validation.</p></div></Card></div>
      <Card title="Region map"><Space wrap><Select aria-label="Local extract" placeholder="Choose a geographic extract" value={extract} options={catalog.extracts.map(row=>({value:row.id,label:row.name}))} onChange={id=>{setExtract(id);setBounds(catalog.extracts.find(row=>row.id===id)!.bounds);}}/><Button disabled={!selectedExtract||busy} onClick={()=>void action(async()=>{await save();apply(await api.request<Workspace>(`/v1/studio/workspaces/${workspace.id}/region`,{extract,bounds,alt,level_height_m:levelHeight}));})}>Select region</Button></Space>{selectedExtract&&bounds.length===4?<><RegionMap source={selectedExtract.bounds} bounds={bounds} scene={workspace.scene} onChange={setBounds}/><div className="guided-coordinate-row">{['West','South','East bound','North bound'].map((label,index)=><label key={label}>{label}<InputNumber aria-label={label} value={bounds[index]} step={0.0001} onChange={value=>{if(value!==null)setBounds(bounds.map((old,i)=>i===index?value:old));}}/></label>)}<label>Altitude (m)<InputNumber value={alt} onChange={value=>{if(value!==null)setAlt(value);}}/></label><label>Metres per level<InputNumber min={0.1} value={levelHeight} onChange={value=>{if(value!==null)setLevelHeight(value);}}/></label></div></>:<p className="guided-muted">No geographic extract selected. The traffic demo uses its authored local city scene.</p>}{workspace.region&&<Button onClick={()=>void action(async()=>{await save();await api.request(`/v1/studio/workspaces/${workspace.id}/network`,{});apply(await api.request<Workspace>(`/v1/studio/workspaces/${workspace.id}`));})}>Generate SUMO road network</Button>}</Card>
     </section>}
     {visited.has('entities')&&<section hidden={step!=='entities'} data-testid="studio-panel-entities"><EntitiesStep key={`${workspace.id}/${new URLSearchParams(location.search).get('entity')??''}`} initialEntityId={new URLSearchParams(location.search).get('entity')??undefined} scenario={scenario} onChange={onChange} api={api} types={allTypes} fields={allFields} schemas={workspace.registry_catalog?.schemas}/></section>}
     {visited.has('plugins')&&<section hidden={step!=='plugins'} data-testid="studio-panel-plugins"><DomainPluginsStep key={workspace.id} scenario={scenario} onChange={onChange} engines={catalog.engines} onValidityChange={pluginValidity}/></section>}
     {visited.has('predicates')&&<section hidden={step!=='predicates'} data-testid="studio-panel-predicates"><PredicatesStep {...common} scenario={scenario} types={allTypes} fields={allFields} relations={allRelations} onValidityChange={predicateValidity}/></section>}
     {visited.has('rules')&&<section hidden={step!=='rules'} data-testid="studio-panel-rules"><RulesStep {...common} scenario={scenario} types={allTypes} fields={allFields} relations={allRelations} onValidityChange={behaviourValidity}/></section>}
     {visited.has('agents')&&<section hidden={step!=='agents'} data-testid="studio-panel-agents"><AgentsStep {...common} profiles={catalog.demo_profiles}/></section>}
     {step==='validate'&&<section data-testid="studio-panel-validate"><Card title="Scenario checks"><p>The compiler checks AeroGraph fields and ancestry, single writers, predicates, behaviour chains and plugin capabilities.</p>{!workspace.validation?<PageState kind="empty" title="Ready for validation" description="Validate the entire draft to see authored errors grouped by configuration step."/>:bindingsValid?<Alert type="success" showIcon message="Scenario valid" description="The current saved draft passed the real runtime compiler. You can start a new run."/>:<><Alert type="error" showIcon message={`${issues.length} authoring issues`}/>{studioSteps.filter(item=>issues.some(issue=>issueStep(issue)===item.id)).map(item=><div key={item.id}><h3>{item.label}</h3>{issueList(item.id)}</div>)}</>}<div className="guided-run-actions"><Button disabled={busy||!buffersValid} onClick={()=>void action(validate)}>Validate draft</Button><Button type="primary" disabled={busy||!bindingsValid} onClick={()=>void action(run)}>Start run</Button></div></Card></section>}
     <footer className="guided-step-footer"><Button disabled={step==='scene'} onClick={()=>chooseStep(studioSteps[studioSteps.findIndex(item=>item.id===step)-1].id)}>Previous step</Button><span className="guided-muted">Changes apply to the next run.</span><Button disabled={step==='validate'} onClick={()=>chooseStep(studioSteps[studioSteps.findIndex(item=>item.id===step)+1].id)}>Next step</Button></footer>
    </main>
   </div>
   <Modal title="Scenario validation" open={issuesOpen} onCancel={()=>setIssuesOpen(false)} footer={<Button onClick={()=>{chooseStep('validate');setIssuesOpen(false);}}>Open validation step</Button>}>{bindingsValid?<Alert type="success" message="No authoring issues"/>:issues.length?studioSteps.filter(item=>issues.some(issue=>issueStep(issue)===item.id)).map(item=><section key={item.id}><h3>{item.label}</h3>{issueList(item.id)}</section>):<p>Validate the draft to check its authored fields, plugin ownership and event rules.</p>}</Modal>
  </>}
  <Link className="guided-bottom-link" to={`/runs?api=${encodeURIComponent(base)}`}>Browse runs →</Link>
 </div>;
}
