"""Print a compact Markdown timeline from two completed, immutable run journals."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any, cast

from aerokernel.codec import decode_record
from aerokernel.compact import expand_record
from aerokernel.journal import iter_records
from aerokernel.values import thaw

from aeroagentsim.observations.artifacts import ArtifactStore
from aeroagentsim.services.storage import RunStorage


def read_events(path: Path) -> list[tuple[int, str, dict[str, Any]]]:
    """Read committed event proposals, excluding their enqueue/dispatch copies."""
    if RunStorage(path).metadata()["status"] != "completed":
        raise ValueError(f"timeline requires a completed run: {path}")
    result = []
    # Stream either wire codec, then expand compact semantic fact rows.
    for raw in iter_records(path / "journal.jsonl"):
        record = expand_record(raw)
        for item in record.get("items", []):
            if "proposal" not in item or "message" not in item:
                continue
            message = decode_record(item["message"])
            if message.kind == "event":
                result.append(
                    (
                        message.at.ns,
                        message.schema_id,
                        cast(dict[str, Any], thaw(message.payload)),
                    )
                )
    return result


def first(
    rows: list[tuple[int, str, dict[str, Any]]],
    schema: str,
    **matches: Any,
) -> int:
    return min(
        ns
        for ns, key, payload in rows
        if key == schema and all(payload.get(k) == v for k, v in matches.items())
    )


def render(timer: Path, operator: Path) -> str:
    rows = [read_events(timer), read_events(operator)]
    labels: tuple[tuple[str, str, dict[str, Any]], ...] = (
        ("Accident activated; stop commands issued", "traffic.incident.activated", {}),
        ("Stopped/proximity predicate → detection", "traffic.incident.detected", {}),
        ("Reporter proposal → report sent", "traffic.report.sent", {}),
        ("Edge broadcasts capture task", "traffic.broadcast", {}),
        (
            "Alpha refuses its non-interruptible task",
            "traffic.proposal.bid",
            {"accept": False},
        ),
        (
            "Bravo offers its interruptible patrol",
            "traffic.proposal.bid",
            {"accept": True},
        ),
        ("Eligible minimum ETA → award proposed", "traffic.award.proposed", {}),
        ("Actual stop receipt → award committed", "traffic.award.committed", {}),
        (
            "Goto receipt → hold command",
            "aas.behaviour.transitioned",
            {
                "op": "assert",
                "templateId": "traffic.capture_execute",
                "transitionId": "hold",
            },
        ),
        (
            "Hold receipt → dwelling",
            "aas.behaviour.transitioned",
            {
                "op": "assert",
                "templateId": "traffic.capture_execute",
                "transitionId": "dwell",
            },
        ),
        ("Sampled 3 s dwell → capture requested", "traffic.capture.requested", {}),
        ("Real PNG persisted", "traffic.capture.stored", {}),
        ("Stored bytes verified; edge accepts", "traffic.capture.accepted", {}),
        (
            "Receipt-backed capture chain completes",
            "aas.behaviour.completed",
            {"op": "assert", "templateId": "traffic.capture_execute"},
        ),
    )
    output = [
        "<!-- Generated by scenarios/demos/traffic-accident/timeline.py; times are sim seconds. -->",
        "| Event / chain transition | Authored timer (s) | HTTP injection (s) |",
        "| --- | ---: | ---: |",
    ]
    for label, schema, matches in labels:
        times = [first(records, schema, **matches) for records in rows]
        formatted = [f"{ns // 1_000_000_000}.{ns % 1_000_000_000:09d}" for ns in times]
        output.append(f"| {label} | {formatted[0]} | {formatted[1]} |")
    for label, path in (("Timer", timer), ("HTTP", operator)):
        package = json.loads((path / "behaviour.ir.json").read_text())["packages"][0]
        capture = ArtifactStore(path).get("incident-capture-01/episode-0")
        digest = hashlib.sha256()
        with (path / "journal.jsonl").open("rb") as stream:
            for chunk in iter(lambda: stream.read(1 << 20), b""):
                digest.update(chunk)
        output.extend(
            (
                "",
                (
                    f"{label} run `{path.name}`: journal SHA-256 `{digest.hexdigest()}`; "
                    f"PNG SHA-256 `{capture['digest']}`; camera cut `{capture['request']['source_cut']}`."
                ),
                f"Pinned package `{package['digest']}`, IR `{package['ir_digest']}`.",
            )
        )
    return "\n".join(output) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("timer", type=Path)
    parser.add_argument("operator", type=Path)
    args = parser.parse_args()
    print(render(args.timer, args.operator), end="")
