import { createRequire } from 'node:module';
import { mkdirSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
const require = createRequire(new URL('../../frontend/package.json', import.meta.url));
const { chromium } = require('@playwright/test');
const api = 'http://127.0.0.1:8002';
const response = await fetch(`${api}/v1/runs`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ scenario_path: 'scenarios/p1-slice.yaml' }) });
if (!response.ok) throw Error(await response.text());
const run = await response.json();
let status;
for (let attempt = 0; attempt < 300; attempt++) {
  status = (await (await fetch(`${api}/v1/runs`)).json()).find(item => item.id === run.id);
  if (status.status === 'completed') break;
  if (status.status === 'faulted') throw Error(JSON.stringify(status));
  await new Promise(resolve => setTimeout(resolve, 200));
}
if (status.status !== 'completed') throw Error('Run did not complete');
const recorded = await (await fetch(`${api}/v1/runs/${run.id}/commits?from=1&limit=4096`)).json();
if (!recorded.commits.some(commit => commit.edges.length)) throw Error('No actual relation edges');
const expected = recorded.commits.length;
const browser = await chromium.launch({ executablePath: join(homedir(), '.cache/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-linux64/chrome-headless-shell'), headless: true, args: ['--no-sandbox', '--enable-unsafe-swiftshader', '--use-angle=swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
page.on('pageerror', error => errors.push(error.message));
await page.goto(`${api}/runs`);
await page.getByRole('heading', { name: 'AeroAgentSim Runs' }).waitFor();
await page.getByRole('link', { name: run.id, exact: true }).click();
await page.getByTestId('viewport').waitFor();
await page.getByText('completed', { exact: true }).waitFor();
await page.waitForFunction(count => [...document.querySelectorAll('footer span')].some(el => (el.textContent ?? '').endsWith(`${count} commits`)), expected, { timeout: 60000 });
const slider = page.getByRole('slider');
await slider.focus(); await page.keyboard.press('End');
await page.waitForTimeout(800);
mkdirSync('frontend/test-results', { recursive: true });
await page.screenshot({ path: 'frontend/test-results/p1-slice-replay.png', fullPage: true });
const lastPageStart = Math.floor((expected - 1) / 256) * 256 + 1;
const livePage = page.waitForResponse(response => response.url().includes(`/commits?from=${lastPageStart}&`));
await page.locator('div[aria-label="Feed mode"]').click();
await page.getByText('Live', { exact: true }).last().click();
await livePage;
await page.waitForFunction(count => [...document.querySelectorAll('footer span')].some(el => (el.textContent ?? '').endsWith(`${count} commits`)), expected, { timeout: 60000 });
await page.waitForTimeout(1000);
await page.screenshot({ path: 'frontend/test-results/p1-slice-live.png', fullPage: true });
if (errors.length) throw Error(`Browser errors: ${JSON.stringify(errors)}`);
console.log(JSON.stringify({ run: run.id, status: status.status, console_errors: errors.length, screenshots: ['frontend/test-results/p1-slice-replay.png', 'frontend/test-results/p1-slice-live.png'] }));
await browser.close();
