"""Independent, domain-neutral conservative simulation kernel."""

from .binding import BindingManifest, BindingRule, ExactBinding, LifecycleRule
from .coordinator import Kernel
from .engine import Batch, Dependency, Engine, Horizon, Partition, RunContext, Timing
from .errors import (
    KernelError,
    MicrostepLimitExceeded,
    ResourceLimit,
    SynchronizationDeadlock,
)
from .ids import EntityRef, FieldKey, FramePrefix, ItemRef, LocalCause
from .ingress import IngressPolicy, IngressReceipt, IngressStream, IngressWait
from .journal import Journal, iter_records, replay
from .messages import (
    ActionState,
    CancelDecision,
    CancelRequestResult,
    CommandRequest,
    Delivery,
    Dirty,
    Emit,
    Feedback,
    Message,
    Receipt,
    RequestCancel,
)
from .operations import (
    Activate,
    ActivateObligation,
    AssertEdge,
    CancelEdge,
    CancelObligation,
    CancelTimer,
    CloseEdge,
    Create,
    EndObligation,
    FactWrite,
    LifecycleReady,
    Remove,
    RetractFact,
    SampleFrame,
    ScheduleTimer,
)
from .registry import (
    FieldDescriptor,
    MemoryRegistry,
    MessageDescriptor,
    Registry,
    TypeDescriptor,
)
from .relations import (
    Cardinality,
    Edge,
    Obligation,
    ObligationRule,
    RelationDependency,
    RelationDescriptor,
    RelationRule,
)
from .rpc_transport import PausePolicy
from .sampling import RecordedFrame, SampleSpec
from .state import ABSENT, Absent, Fact, Retraction, StateView
from .time import ClockMapping, Cut, Instant, Interval, Stamp
from .values import (
    ResourceBudget,
    canonical_json,
    freeze,
    normalize,
    parse_json,
    thaw,
    typed_equal,
)

__version__ = "0.2.0.dev0"

__all__ = [
    "ABSENT",
    "Absent",
    "ActionState",
    "Activate",
    "AssertEdge",
    "CloseEdge",
    "CancelEdge",
    "ActivateObligation",
    "EndObligation",
    "CancelObligation",
    "Cardinality",
    "RelationDescriptor",
    "RelationRule",
    "ObligationRule",
    "RelationDependency",
    "Edge",
    "Obligation",
    "Batch",
    "BindingManifest",
    "BindingRule",
    "CancelDecision",
    "CancelRequestResult",
    "CancelTimer",
    "ClockMapping",
    "CommandRequest",
    "Create",
    "Cut",
    "Delivery",
    "Dependency",
    "Dirty",
    "Emit",
    "Engine",
    "EntityRef",
    "ExactBinding",
    "Fact",
    "FactWrite",
    "Feedback",
    "FieldDescriptor",
    "FieldKey",
    "FramePrefix",
    "Horizon",
    "Instant",
    "IngressPolicy",
    "IngressReceipt",
    "IngressStream",
    "IngressWait",
    "Interval",
    "ItemRef",
    "Journal",
    "iter_records",
    "Kernel",
    "KernelError",
    "LifecycleReady",
    "LifecycleRule",
    "LocalCause",
    "MemoryRegistry",
    "Message",
    "MessageDescriptor",
    "MicrostepLimitExceeded",
    "Partition",
    "PausePolicy",
    "Receipt",
    "Registry",
    "Remove",
    "RequestCancel",
    "ResourceBudget",
    "ResourceLimit",
    "RetractFact",
    "Retraction",
    "RunContext",
    "ScheduleTimer",
    "SampleFrame",
    "SampleSpec",
    "RecordedFrame",
    "Stamp",
    "StateView",
    "SynchronizationDeadlock",
    "Timing",
    "TypeDescriptor",
    "canonical_json",
    "freeze",
    "normalize",
    "parse_json",
    "replay",
    "thaw",
    "typed_equal",
]
