#!/usr/bin/env python3
"""Independent, non-mutating review of accepted stage-one catalogues.
Counterexamples are authored review scenarios, never source observations or laws.
"""
import json, hashlib, pathlib, collections
ROOT=pathlib.Path('/workspace/shared/p02_stage1')
OUT=pathlib.Path(__file__).resolve().parent
FILES={'agriculture':'agriculture/agriculture-instances.json','city':'city/city-activity-instances.json','delivery':'delivery/delivery-activity-instances.json','network':'network/network-instance-catalog.json'}
D={k:json.loads((ROOT/v).read_text()) for k,v in FILES.items()}
CAT=json.loads((ROOT/'sources/original_activity_catalog_35.json').read_text())['activities']
# Each tuple is independently authored: activity, salient steps, normal evidence,
# abnormal, conflict, recovery. A pass here is not native execution coverage.
CASES=[
(1,[3,4,5,6,7,8],'Filtered batch 19.8 L and retained 0.2 L remain separate; tank 19.8→7.8 L is release evidence only.','Nozzle blocks after calibration while flight track completes; dose and efficacy stay unresolved.','Tank loss says 12 L but independent collection says 8 L; retain both with scope and uncertainty.','New nozzle calibration and same-batch refill create a new attempt; retain overlap mask and later paired outcome review.'),
(2,[1,3,4,5,6,7],'Batch SEED02, discharge calibration and transverse distribution samples reference the same lot and strip.','Hopper loses 5.9 kg but wind carries seed outside B04; mass released does not prove distribution acceptance.','Refill labelled SEED02 actually has a different batch identity; do not merge by material name.','Bind the replacement lot, recalibrate and resample affected transverse strips before revising acceptance.'),
(3,[1,2,3,4,5,6],'POLLEN03 preparation, sampled viability, flower coverage and day-21 fruit-set follow-up have distinct evidence times.','Viability evidence expired before suspension was applied; 94% coverage cannot establish viable pollination.','Two samples with different storage histories report different viability; do not select the larger ratio.','Retest the exact stored lot and bind new preparation time; preserve original treatment and later outcome cohorts.'),
(4,[1,3,4,5,6],'Calibrated image candidates and six ground checks remain separate, linked to exact grid and sample.','Blurred imagery loses disease evidence even though capture count is complete.','Classifier suggests pest damage while microscopy supports a different cause; no automatic intervention.','Acquire clear matched imagery and independent sample review, then issue a versioned recommendation only.'),
(5,[2,3,4,5,6],'Signed RX05-v2 references tree identities and PATH05-v4; publication acknowledgement identifies both hashes.','35 unique trees cannot justify a 36-entry path without resolving the unmatched crown.','Same prescription label points to different tree-boundary revision; label equality is not version equivalence.','Resolve the unmatched tree, re-sign affected prescription and rebind path; old publication remains historical.'),
(6,[2,3,4,5,6],'JOB06 preserves ten field outcomes, including nine accepted and one awaiting evidence.','Ten recorded decisions are misread as ten accepted fields; the unresolved field remains unresolved.','Treatment logs and remeasurement disagree on sample identity; paired count alone is insufficient.','Reconcile exact sample/field identities, preserve exclusions and reviewer reasons, then update only affected outcome.'),
(7,[3,4,5,7,8,9],'Rigger, sling lock, positive sling load support, ground contact, release and custody are independently recorded.','Aircraft accepts lift command but sling support is unknown; cannot infer lift from command receipt.','Cargo touches ground while sling still supports load and receiver has not accepted custody.','Confirm load transfer and release with fresh evidence, then obtain exact-item custody acknowledgement before return.'),
(8,[1,2,4,5,6,7],'Load plan and route are versioned; any special-permission record remains separate from physical capability.','Permission source absent while rigging is sound; later plan steps are counterfactual, not authorized execution.','Two lift coordinators issue incompatible commands to the same actuator/time scope.','Named command authority resolves the conflict; a fresh scoped grant and start checks precede a new attempt.'),
(9,[2,3,4,5,6],'Forest samples have exact plot/tree identities, sealed containers, named human operator and read-only review.','Terminal receipt of sampling request cannot prove a forester reached S09-03 or collected twelve samples.','Image discoloration suggests insects while field samples indicate drought; preserve both reports.','Use an alternate observation or laboratory test with new specimen evidence; retain pending diagnosis until resolved.'),
(10,[2,3,4,5,6],'Thermal candidate, verified target, position uncertainty and commander receipt remain four distinct claims.','Hot machinery produces thermal anomaly without fire evidence; do not escalate anomaly to confirmed fire.','Delayed location update conflicts with fresh ground report in a different coordinate frame.','Resolve clock/frame mapping and target identity, publish a new bounded-location report and track separate receipt.'),
(11,[2,3,4,5],'SEEDBALL11 package mass, release, ground landing and day-30/day-90 growth remain separate endpoints.','1.95 kg payload loss occurs but landing is outside R11-04; release is not successful restoration.','GPS landing estimate overlaps restricted drainage boundary while ground observer reports inside target.','Reconcile boundary and landing uncertainty; record authorized remedial plan separately and retain original ecological cohort.'),
(12,[2,3,4,5],'Feed balance is 20=19.6+0.3+0.1 kg; water/leftover observations do not prove fish consumption.','Replace released quantity with 19.9 kg while residual stays zero; inconsistent balance must be detected or flagged.','Scale reports loss but shore observation shows off-pond spill; released mass differs from delivered feed.','Reweigh remainder and cleanout with calibration/source records; revise balance and pond-delivery assessment separately.'),
(13,[1,3,4,5,6],'Six water specimens and one blank have seven distinct bottles, seal IDs and custodians.','Bottle S13-04 loses its seal while aggregate sample count stays seven; traceability is incomplete.','Laboratory result uses S13-04 label but a different bottle generation; do not join by label.','Recollect affected sample with new seal and custody chain; retain invalid result and do not assign pollution liability.'),
(14,[1,2,3,4,5,6,7],'Survey boundary, vertical datum, independent checkpoints and delivered model revision are all explicit.','Control points used for fitting are reused as independent validation; low error does not establish independence.','Two equal numeric heights use different vertical datums; exact units alone do not make comparable values.','Acquire withheld checkpoints and explicit datum transform, rebuild affected model and deliver new reviewed revision.'),
(15,[1,2,3,4,5],'Volume difference binds common boundary/baseline and uncertainty; engineering approval is a separate unknown record.','Uncertainty 4 m3 <= illustrative 5 m3 is incorrectly turned into engineering acceptance.','Current surface and baseline use different excavation boundaries; numeric difference cannot be accepted.','Align verified baseline and boundary, recompute uncertainty and obtain independent engineering decision.'),
(16,[1,2,3,4,5,6],'BIM16-r7, capture, alignment, deviation candidate and human review remain version-bound.','Occluded component is absent from imagery; absence is not proof of missing construction.','Reviewer accepts DEV16-04 under r7 while an update targets r8 with changed component identity.','Rebase evidence and review to exact revision, preserve candidate history and apply only reviewed change.'),
(17,[2,3,4,5,6],'Multiview crack candidate retains scale/calibration, geometry uncertainty and exact asset component.','0.4 mm candidate threshold is met but image scale is uncalibrated; no confirmed defect or repair proof.','Two views of different bridge components share a crack label; do not fuse measurements.','Reacquire calibrated views for the same component, obtain review and hand over a versioned work order.'),
(18,[1,2,3,4,5,6],'Asset operating state, clearance, calibrated thermal observation and reviewed maintenance evidence are distinct.','Hotspot delta exceeds authored threshold but load state is missing; defect conclusion remains unsupported.','Operational-state revision changes after route planning; previous clearance check cannot cover changed equipment state.','Refresh state and geometry, recheck allowed route, reacquire paired evidence and link reinspection to the same defect.'),
(19,[1,2,3,4,5,6],'Gas background, wind, plume candidate and review retain sampling time, direction and position uncertainty.','High reading occurs downwind of another source; anomaly is not proof of pipeline leakage.','Wind direction report and gas sample are in incompatible clocks or stale windows.','Recalibrate, repeat synchronized upwind/downwind sampling and seek exact-location review before handover.'),
(20,[1,2,3,4,5,6],'Candidate seepage or debris remains linked to exact embankment segment and geolocated review.','Turbid-water image alone is treated as embankment leakage; physical condition remains unknown.','Two reports attach one candidate label to opposite riverbanks.','Resolve segment/position evidence, dispatch the reviewed issue and compare follow-up to the original location.'),
(21,[1,2,3,4,5,6,7],'Department requests retain separate owners and objectives through AI candidate, human review and work order.','Work-order ACK or closed enum is mistaken for independently verified remediation.','Two departments assign conflicting priorities or destinations to the same vehicle and time scope.','Resolve scoped command ownership, keep each request and verify actual remediation before closing only matched items.'),
(22,[1,2,3,4,5,6],'Incident report, scoped access permission, scene observations and commander handoff are distinct records.','Traffic image is stale after lanes reopen; previous congestion cannot be current command evidence.','Incident commander requests landing while facility authority denies occupied-pad access.','Refresh scene and scoped permission, resolve authority conflict and hand off versioned assessment without inventing emergency override.'),
(23,[2,3,4,5,6,7],'Search candidate has uncertainty; verified person location, rescue authority and kit handover each have separate proof.','Classifier confidence .91 cannot prove person identity or authorization to drop a kit.','Two rescuers report different locations for the same candidate; no latest-arrival-wins.','Resolve identity/location via fresh independent review, obtain scoped rescue authorization and verify exact-recipient delivery.'),
(24,[1,2,3,4,5,6,7],'Command authorization, recon, media release/guidance receipt and effect/reignition monitoring remain distinct.','Guidance message ACK is incorrectly treated as extinguishing-media delivery or extinguishment.','Extinguishing-support command conflicts with occupied airspace and separate incident authority.','Resolve authority and airspace, recheck fresh risk evidence and continue effect monitoring until explicit release evidence.'),
(25,[1,2,3,4,5,6,7],'Road-width candidate binds vehicle width, reconstruction uncertainty and versioned reviewed disaster map.','Width 1.0 m is interpreted as blocked for every vehicle without its dimensions and uncertainty.','New flood imagery conflicts with previously published road availability.','Acquire current map evidence, review changed segments and publish a superseding version without deleting old provenance.'),
(26,[2,3,4,5,6],'Sender→carrier loading, carrier→receiver receipt and professional acceptance remain separate and exact-item scoped.','Temperature 5 degC is used as universal medical-quality proof despite missing allowable profile and professional decision.','Signed package receipt identifies different container or custody direction.','Reconcile sealed item identity, retain temperature history and request qualified acceptance; received time stays unknown until receipt.'),
(27,[2,3,4,5,6],'Station custody, recipient pickup and final proof refer to the same retail parcel and order.','Aircraft arrival or upload ACK occurs while the parcel remains in locker; final delivery is incomplete.','Duplicate pickup receipt has same order label but different parcel generation/recipient.','Verify locker custody and exact recipient, record one logical handover and retain duplicate attempts without duplicate delivery.'),
(28,[1,2,3,4,5,6],'Origin handover, cargo movement, transfer vehicle and final receiver have separate route/slot bindings.','Declared alternate site is occupied on arrival; plan availability is not current capacity.','Transfer vehicle and aircraft reserve the same loading bay during overlapping intervals.','Obtain a fresh compatible site/slot and transfer plan, preserving custody while rechecking remaining task deadline.'),
(29,[2,3,4,5,6,7],'Access-session admission, directed backhaul probe and application service receipt jointly bound service evidence.','Radio link connected while backhaul or consumer path fails; service is degraded.','Old-route probe arrives after relay rotation and must not validate the new route.','Probe current directed route and endpoint generation, drain/reconcile backlog and verify consumer service before withdrawal.'),
(30,[1,2,3,4,5,6,7,8],'Task DAG, multidimensional reservation, input transfer, exact-attempt execution and consumer validation are distinct.','GPU free but memory unavailable; CPU count or network upload alone cannot admit full job.','Late source result competes with committed migrated target attempt; one exact acceptance authority is required.','Validate checkpoint and target attempt, accept correct-version result once, then independently verify source cleanup and resource release.'),
(31,[1,2,3,4,5,6,7,8],'Passenger manifest, briefing, restraint checks, aircraft landing and safe exit are identity-bound.','Passenger count equals two but one manifest identity is substituted; count does not prove boarding safety.','Weather permit valid for earlier slot conflicts with delayed departure time.','Reconcile identities and fresh weather/slot checks before new departure; after landing verify each actual disembarkation.'),
(32,[1,2,3,4,5,6],'Connection itinerary, airport readiness, aircraft segment and later transfer acceptance stay separate.','Diversion landing occurs but original onward connection is missed; itinerary not completed.','Original airport permission is reused at alternate airport or for a different passenger manifest.','Obtain alternate-specific readiness and a new onward arrangement, then reconcile all passengers against exact manifest.'),
(33,[2,3,4,5,6,7],'Three exact aircraft share script version; commanded formation and observed poses/separation remain different.','All takeoff ACKs arrive but U3 remains grounded; synchronization not established.','Emergency-exit trajectory crosses another aircraft path while both individual commands are admissible.','Re-arbitrate current trajectories/airspace and verify actual safe separation, then reconcile all three aircraft before zone release.'),
(34,[1,2,3,4,5,6],'Dock occupancy, safety isolation, battery/tool identity, latch state and renewed release checks remain separate.','Swap command completes but latch sensor unknown; aircraft is not ready merely because charge is high.','Reservation expired while vehicle physically occupies dock; lease expiry does not clear occupancy.','Confirm safe isolation and exact installed component/latch, reconcile actual occupancy, revalidate and issue a fresh release.'),
(35,[1,2,3,4,5,6,7],'Requests retain scoped command owners; pad/charger/locker/corridor are committed as one compatible bundle.','One subreservation succeeds and another fails; partial success does not authorize full operation.','Two systems issue conflicting commands to same target/time without arbitration; priority labels do not imply an override.','Resolve exact authority, release verified unused subclaims, allocate fresh compatible bundle and verify effect before final release.')]

def emit(name,obj): (OUT/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
def flatten_ids(v):
 if isinstance(v,dict):
  for k,x in v.items():
   if k=='id' and isinstance(x,str): yield x
   elif isinstance(x,(dict,list)):yield from flatten_ids(x)
 elif isinstance(v,list):
  for x in v:yield from flatten_ids(x)
ACT={}
for i,a in enumerate(D['agriculture']['activities']):ACT[a['activity_index']]=('agriculture',a,f'/activities/{i}',a['steps'])
for i,a in enumerate(D['city']['workflow_instances']):ACT[a['catalog_index']]=('city',a,f'/workflow_instances/{i}',a['steps'])
for i,a in enumerate(D['delivery']['scenarios']):
 if a['catalog_index'] is not None:ACT[a['catalog_index']]=('delivery',a,f'/scenarios/{i}',a['step_mappings'])
for i,a in enumerate(D['network']['original_activity_cases']):ACT[a['catalog_activity_index']]=('network',a,f'/original_activity_cases/{i}',a['source_step_mappings'])
ledger=[]; steps=[]; scenarios=[]
for idx,salient,*texts in CASES:
 domain,a,pointer,ss=ACT[idx]; cat=CAT[idx-1]
 key={'agriculture':'steps','city':'steps','delivery':'step_mappings','network':'source_step_mappings'}[domain]
 bp={'agriculture':'step_specific_authored_branches','city':'generic_branch_templates_with_step_field_bindings','delivery':'scenario_specific_narrative_plus_step_inputs','network':'generic_activity_phases_plus_step_failure_descriptions'}[domain]
 evidence=[]
 for si,s in enumerate(ss,1):
  label=s.get('source_step_name',s.get('exact_source_step')); assert label==cat['steps'][si-1],(idx,si,label)
  ref={'artifact':FILES[domain],'pointer':f'{pointer}/{key}/{si-1}'}
  ids=sorted(set(flatten_ids(s)))
  if domain=='agriculture': ids=list(s.get('concrete_chain',{}).values());ids=[x for x in ids if isinstance(x,str)]
  elif domain=='city':ids=list(s['instance_refs'].values());ids=[x for x in ids if isinstance(x,str)]
  else:ids=[v for k,v in s.items() if k.endswith('_ref') and isinstance(v,str)]
  step={'activity_index':idx,'step_index':si,'source_step':label,'domain':domain,'source':ref,'binding_refs':ids,'branch_evidence_quality':bp,'native_execution':'not_run','independent_domain_review':'source_semantics_and_counterexamples_only','remaining_requirement':'Bind producer/evaluator/authority for this exact step and execute applicable positive and negative evidence paths; do not force unrelated types.'}
  steps.append(step)
  if si in salient:evidence.append({'step_index':si,'source_step':label,**ref,'binding_refs':ids[:8]})
 entry={'activity_index':idx,'name':cat['name'],'domain':domain,'source_step_count':len(ss),'source_steps_exact':cat['steps'],'source':{'artifact':FILES[domain],'pointer':pointer},'stage1_branch_quality':bp,'scenarios':[],'verdict':'review_cases_defined; native_execution_unverified','evidence':evidence}
 for branch,desc in zip(['normal','abnormal','conflict','recovery'],texts):
  fid=f'DOM-A{idx:02d}-{branch.upper()}'
  record={'id':fid,'activity_index':idx,'branch':branch,'description':desc,'scope':'authored independent review challenge; not source event, not legal rule','source_step_indices':salient,'source_evidence':evidence,'expected_boundary':'Preserve each distinct claim, exact identities and unknown evidence; never infer real completion/permission from this authored case.','native_execution_status':'not_run','review_status':'specified_not_executed'}
  scenarios.append(record);entry['scenarios'].append(fid)
 ledger.append(entry)
assert len(ledger)==35 and len(steps)==226 and len(scenarios)==140
machines=[]
for i,m in enumerate(D['network']['machine_information_activity_inventory']):
 case=next(x for x in D['network']['machine_activity_cases'] if x['id']==m['case_ref'])
 machines.append({'id':m['id'],'name':m['source_name'],'case_ref':m['case_ref'],'source':{'artifact':FILES['network'],'pointer':f'/machine_information_activity_inventory/{i}'},'phases':m['lifecycle'],'coverage':'concrete_authored_four_phase_evidence; not_executed','caveat':'Expected True/False/Unknown and admission values are fixture expectations, not computed or observed outcomes.','native_producer_gap':m['native_producer_gap'],'independent_challenge':'Preserve case phase, exact endpoint/attempt/generation and context fact; a metric threshold cannot substitute for context admission.'})
manifest={k:{'path':str(ROOT/v),'sha256':hashlib.sha256((ROOT/v).read_bytes()).hexdigest()} for k,v in FILES.items()}
emit('coverage-ledger.json',{'schema':'p08.independent-domain-coverage/v1','scope':'static domain review, source extraction coverage and explicit adversarial scenarios; no exhaustive or runtime assurance','sources':manifest,'activity_count':35,'source_step_count':226,'machine_activity_count':20,'activities':ledger,'steps':steps,'machine_activities':machines})
emit('adversarial-scenarios.json',{'schema':'p08.domain-adversarial-scenarios/v1','scope':'140 independently authored scenarios covering four meaningful branches for all 35 business activities; these are test designs, not executed validations','scenarios':scenarios})
print(json.dumps({'activities':len(ledger),'steps':len(steps),'machines':len(machines),'authored_challenges':len(scenarios),'sources':manifest},indent=2))
