import { test, expect } from '@playwright/test';

test('real traffic console: draft, compiler, operator accident, award, city photo and shared cut',async({page,baseURL})=>{
 const screenshot=(name:string)=>test.info().outputPath(`${name}.png`);
 if (!baseURL) throw Error('Console e2e requires its configured API URL');
 await page.goto(`/?api=${encodeURIComponent(baseURL)}`);
 await expect(page.getByTestId('home-page')).toBeVisible();
 await page.screenshot({path:screenshot('home')});
 await page.getByTestId('nav-aerograph').click();await expect(page.getByTestId('aerograph-page')).toBeVisible();
 await page.screenshot({path:screenshot('aerograph')});
 await page.getByTestId('nav-runs').click();await expect(page.getByTestId('runs-page')).toBeVisible();
 await page.screenshot({path:screenshot('runs')});
 await page.getByTestId('nav-home').click();await page.getByTestId('open-traffic-demo').click();
 await page.waitForURL(/\/studio\?template=traffic-accident/);
 await expect(page.getByTestId('studio-step-entities')).toBeVisible({timeout:60_000});
 await page.getByTestId('studio-step-rules').click();
 await expect(page.getByLabel('Package ID')).toHaveValue('traffic.accident');
 await page.getByRole('button',{name:'Validate',exact:true}).click();
 await expect(page.getByRole('button',{name:'Run now',exact:true})).toBeEnabled({timeout:60_000});
 await page.screenshot({path:screenshot('studio')});
 await page.getByRole('button',{name:'Run now',exact:true}).click();
 await page.waitForURL(/\/runs\/run-/,{timeout:60_000});
 const run=page.url().match(/\/runs\/(run-[a-f0-9]+)/)![1];
 await expect(page.getByTestId('dual-run-views')).toBeVisible({timeout:60_000});
 await page.getByLabel('Injection point').selectOption('accident');
 await expect(page.getByRole('button',{name:'Submit typed ingress'})).toBeEnabled({timeout:60_000});
 await page.getByRole('button',{name:'Submit typed ingress'}).click();
 await expect(page.getByText('Admission receipts · 1')).toBeVisible({timeout:30_000});
 await page.getByText('Decision / LangGraph and typed event records at this cut',{exact:true}).click();
 await expect(page.getByText('traffic.award.committed',{exact:true}).first()).toBeVisible({timeout:300_000});
 await expect.poll(async()=>{const failed=page.getByText('traffic.capture.failed',{exact:true});if(await failed.count())throw Error(`Recorded capture failure: ${await failed.first().locator('..').textContent()}`);return page.evaluate(async id=>{const r=await fetch(`/v1/runs/${id}/artifacts`);if(!r.ok)throw Error(`Artifact HTTP ${r.status}: ${await r.text()}`);const rows:unknown=await r.json();if(!Array.isArray(rows))throw Error('Artifact response must be an array');if(!rows.length){const status=await fetch('/v1/runs');if(!status.ok)throw Error(`Run status HTTP ${status.status}`);const runs=await status.json();const run=runs.find((row:{id:string})=>row.id===id);if(!run)throw Error('Run status is unavailable');if(['faulted','interrupted','stopped','completed'].includes(run.status))throw Error(`Run ${run.status} before capture: ${run.error??'no artifact recorded'}`);}return rows.length;},run);},{timeout:900_000,intervals:[5000]}).toBeGreaterThan(0);
 await page.getByRole('button',{name:'Refresh stored artifacts'}).click();
 await page.getByRole('button',{name:'Open photo'}).first().click();
 await expect(page.getByAltText(/^Stored capture /)).toBeVisible({timeout:60_000});

 await page.getByRole('button',{name:'Alpha',exact:true}).click();
 await page.screenshot({path:screenshot('run')});
 await page.getByText(/Recorded overlays/).click();
 const transition=page.getByTestId('chain-transition').first();const targetCut=await transition.getAttribute('data-transition-cut');await transition.click();
 await page.getByTestId('nav-inspect').click();await page.waitForURL(/\/inspect\/run-/);
 await page.screenshot({path:screenshot('inspect')});
 await page.setViewportSize({width:1280,height:1000});
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:screenshot('inspect-1280')});
 const graph=page.getByRole('region',{name:'Synchronized AeroGraph view'});const dual=page.getByTestId('dual-run-views');
 await expect(dual).toHaveAttribute('data-cut',targetCut as string);
 await expect(graph).toHaveAttribute('data-cut',await dual.getAttribute('data-cut') as string);
 await expect(page.getByTestId('synchronized-city')).toHaveAttribute('data-cut',await dual.getAttribute('data-cut') as string);
 await page.getByRole('button',{name:'Simulation stop',exact:true}).click();
});
