import { useState } from 'react';
import { Alert, Button, Card, Input, Select, Table, Tag } from 'antd';
import { Details } from '../../console/Details';
import { ExpressionControl } from '../../behaviours/ExpressionControl';
import { readableName } from '../guided-model';
import type { Workspace } from '../api';
import type { GuidedStepProps } from './PredicatesStep';
interface Props extends GuidedStepProps {profiles?:Record<string,Record<string,unknown>>}
export function AgentsStep({workspace,api,save,onApply,onChange}:Props) {
 const decisions=workspace.scenario.engines?.decisions,config=decisions?.config;
 const [provider,setProvider]=useState({base_url:String(config?.provider?.base_url ?? ''),model:String(config?.provider?.model ?? ''),api_key_env:String(config?.provider?.api_key_env ?? '')}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[grantKind,setGrantKind]=useState('fields');
 const live=decisions?.plugin==='langgraph',mode=!decisions?'No decision plugin':live?(config?.provider?.mode==='live'?'Live LangGraph':config?.provider?.mode==='stub'?'Recorded model responses':'LangGraph'):decisions.plugin==='traffic_decisions'&&config?.mode==='stub'?'Scripted decisions':readableName(decisions.plugin);
 const changeConfig=(next:Record<string,unknown>)=>onChange({...workspace.scenario,engines:{...workspace.scenario.engines,decisions:{...decisions,config:next}}});
 const apply=async(body:unknown)=>{setBusy(true);setError('');try{await save();onApply(await api.request<Workspace>(`/v1/studio/workspaces/${workspace.id}/decision-profile`,body));}catch(problem){setError(String(problem));}finally{setBusy(false);}};
 const triggers=Array.isArray(config?.triggers)?config.triggers:[];
 const scriptedPoints=config?.latency_ns?Object.keys(config.latency_ns):[];
 const grants=Object.entries(config?.grants ?? {}).flatMap(([kind,rows])=>Array.isArray(rows)?rows.map((row:any,index)=>({key:`${kind}/${index}`,kind,subject:row.entity??row.source??row.schema??row.relation,field:row.field??row.topic??row.target,row})):[]);
 return <div className="guided-root"><Card title="Decision profile" extra={<Tag color={live?'blue':'default'}>{mode}</Tag>}><p className="guided-muted">Decision agents propose reports and bids. Behaviour chains admit the proposal and apply state updates through the assigned field writers.</p>{!decisions?<Alert type="info" message="No decision plugin configured" description="Add a decision partition through Domain plugins or the scenario source."/>:<><div className="guided-agent-summary"><div><span className="guided-label">Decision engine</span><strong>{readableName(decisions.plugin)}</strong></div><div><span className="guided-label">Decision points</span><strong>{triggers.length?triggers.map((row:any)=>readableName(row.schema)).join(' · '):scriptedPoints.length?scriptedPoints.map(readableName).join(' · '):'No triggers configured'}</strong></div></div>{workspace.scenario.id==='traffic-accident'&&<Button disabled={busy} onClick={()=>void apply({mode:'scripted'})}>Use scripted decisions</Button>}<Details title="Decision profile source"><pre>{JSON.stringify(decisions,null,2)}</pre></Details></>}</Card>
 <Card title="LangGraph model"><p className="guided-muted">Connect a model provider for the next run. Scripted mode remains available for reproducible demo runs.</p><div className="guided-form"><label>Provider URL<Input aria-label="Live provider base_url" value={provider.base_url} placeholder="https://your-provider/v1" onChange={event=>setProvider({...provider,base_url:event.target.value})}/></label><label>Model name<Input aria-label="Live provider model" value={provider.model} placeholder="Provider model name" onChange={event=>setProvider({...provider,model:event.target.value})}/></label><label>API key environment variable<Input aria-label="Live provider api_key_env" value={provider.api_key_env} placeholder="e.g. MODEL_API_KEY" onChange={event=>setProvider({...provider,api_key_env:event.target.value})}/></label><Button loading={busy} disabled={Object.values(provider).some(value=>!value.trim())||workspace.scenario.id!=='traffic-accident'} onClick={()=>void apply({provider})}>Use live LangGraph for next run</Button></div>{error&&<Alert type="error" showIcon message="Decision profile could not be applied" description={error}/>}<Details title="Decision profile endpoint"><p>POST /v1/studio/workspaces/{workspace.id}/decision-profile</p></Details></Card>
 {live&&<Card title="Graph & tool access"><div className="guided-form"><label>Graph factory<Input aria-label="Agent graph factory" value={config.factory} onChange={event=>changeConfig({...config,factory:event.target.value})}/></label>{config.options?.prompt_name!==undefined&&<label>Prompt name<Input value={config.options.prompt_name} onChange={event=>changeConfig({...config,options:{...config.options,prompt_name:event.target.value}})}/></label>}</div><h4>Granted tools and observations</h4><Table size="small" rowKey="key" pagination={{pageSize:8}} dataSource={grants} columns={[{title:'Access',dataIndex:'kind',render:readableName},{title:'Entity / event',dataIndex:'subject',render:(id)=>id?readableName(id):'Not configured'},{title:'Field / topic',dataIndex:'field',render:(id)=>id?readableName(id):'Not configured'},{title:'Details',key:'details',render:(_,row)=><Details title="Tool grant"><pre>{JSON.stringify(row.row,null,2)}</pre></Details>}]}/><Select aria-label="Agent grant category" value={grantKind} onChange={setGrantKind} options={['fields','relations','commands','facts','events'].map(value=>({value,label:readableName(value)}))}/><ExpressionControl label="Agent tool grants" value={config.grants?.[grantKind]} onChange={next=>changeConfig({...config,grants:{...config.grants,[grantKind]:next}})}/><Details title="Agent execution configuration"><ExpressionControl label="Agent options" value={config.options} onChange={next=>changeConfig({...config,options:next})}/><ExpressionControl label="Agent budget" value={config.budget} onChange={next=>changeConfig({...config,budget:next})}/><ExpressionControl label="Agent provider" value={config.provider} onChange={next=>changeConfig({...config,provider:next})}/></Details></Card>}
 </div>;
}
