import { useMemo, useState } from 'react';
import { Alert, Button, Card, Collapse, Input, Select, Space, Table, Tag } from 'antd';
import { BehavioursPanel } from '../BehavioursPanel';
import { Details } from '../../console/Details';
import { ExpressionControl } from '../../behaviours/ExpressionControl';
import { applicableFields, isA, mapping, type Draft } from '../../behaviours/model';
import { readableName } from '../guided-model';
import { packagesOf, isInline, type GuidedStepProps, type CatalogProps } from './PredicatesStep';

interface Props extends GuidedStepProps, CatalogProps {scenario:Record<string,any>;onValidityChange?:(valid:boolean)=>void}
export function appendPredicateRule(scenario:Record<string,any>,index:number,id:string,predicate:string,match:Draft,action:Draft):Record<string,any> {
 const packages=packagesOf(scenario),pkg=packages[index];
 if(!isInline(pkg)||!mapping(pkg.predicates)||!mapping(pkg.predicates[predicate])) throw Error('Choose an inline package predicate');
 const row=pkg.predicates[predicate] as Draft;
 if(!id.trim()||mapping(pkg.chains)&&id in pkg.chains) throw Error('Choose a unique rule name');
 const chain={roles:row.roles,trigger:{predicate,edge:'entered'},initial:'waiting',terminal:['done'],states:['waiting','done'],transitions:[{id:'act',from:'waiting',on:{instance:'activated'},to:'done',actions:[{...action,id:'action'},{id:'finish',kind:'complete',status:'completed'}]}]};
 const next={...pkg,chains:{...(mapping(pkg.chains)?pkg.chains:{}),[id]:chain},bindings:[...(Array.isArray(pkg.bindings)?pkg.bindings:[]),{id:`${id}-binding`,chain:id,match,multiplicity:'once_per_entity',on_unbind:'retain_until_terminal'}]};
 return {...scenario,behaviours:packages.map((value,i)=>i===index?next:value)};
}
export function RulesStep({workspace,api,save,onApply,onChange,scenario,types,fields,relations,onValidityChange}:Props) {
 const packages=packagesOf(scenario),inline=packages.map((pkg,index)=>({pkg,index})).filter(row=>isInline(row.pkg));
 const [predicateKey,setPredicateKey]=useState<string>(),[name,setName]=useState(''),[roleBindings,setRoleBindings]=useState<Record<string,string>>({}),[targetRole,setTargetRole]=useState<string>(),[field,setField]=useState<string>(),[value,setValue]=useState<unknown>(),[error,setError]=useState('');
 const predicateOptions=inline.flatMap(({pkg,index})=>Object.keys(mapping(pkg.predicates)?pkg.predicates:{}).map(id=>({value:`${index}/${id}`,label:readableName(id)})));
 const pkgIndex=predicateKey?Number(predicateKey.slice(0,predicateKey.indexOf('/'))):undefined,predicateId=predicateKey?.slice(predicateKey.indexOf('/')+1);
 const pkg=pkgIndex===undefined?undefined:packages[pkgIndex],predicate=pkg&&predicateId&&mapping(pkg.predicates)?pkg.predicates[predicateId]:undefined;
 const roles=mapping(predicate)&&mapping(predicate.roles)?predicate.roles:{};
 const targetType=targetRole&&typeof roles[targetRole]==='string'?roles[targetRole] as string:undefined;
 const applicable=targetType?applicableFields(targetType,types,fields):[];
 const rows=useMemo(()=>inline.flatMap(({pkg,index})=>Object.entries(mapping(pkg.chains)?pkg.chains:{}).filter(([,chain])=>mapping(chain)).map(([id,chain])=>{const row=chain as Draft,bindings=(Array.isArray(pkg.bindings)?pkg.bindings:[]).filter((binding:any)=>binding.chain===id);return {key:`${index}/${id}`,id,chain:row,bindings};})),[scenario.behaviours]);
 const common={api,workspace,scenario,types,fields,relations,onChange,onApply,save,onValidityChange:onValidityChange ?? (()=>{})};
 return <div className="guided-root">
  <Card title="Create a predicate rule"><p className="guided-muted">When a condition becomes true, apply a state update and let subsequent predicate transitions continue the workflow.</p><div className="guided-rule-builder"><label>Rule name<Input aria-label="Rule name" value={name} onChange={event=>setName(event.target.value)} placeholder="e.g. incident-alert"/></label><label>When<Select aria-label="Rule predicate" placeholder="Choose a predicate" value={predicateKey} options={predicateOptions} onChange={key=>{setPredicateKey(key);setRoleBindings({});setTargetRole(undefined);setField(undefined);setValue(undefined);}}/></label><span className="guided-rule-connector">becomes true</span></div>
  {Object.entries(roles).map(([role,type])=><label className="guided-rule-role" key={role}>For {readableName(role)}<Select aria-label={`Rule entity ${role}`} placeholder={`Choose a ${readableName(String(type))}`} value={roleBindings[role]} options={[{value:'@type',label:`Every ${readableName(String(type))}`},...(Array.isArray(scenario.entities)?scenario.entities:[]).filter((entity:any)=>isA(entity.type,String(type),types)).map((entity:any)=>({value:entity.id,label:readableName(entity.id)}))]} onChange={next=>setRoleBindings({...roleBindings,[role]:next})}/></label>)}
  <div className="guided-rule-builder"><span className="guided-rule-connector">→ Set state</span><label>Target role<Select aria-label="Rule action role" value={targetRole} options={Object.keys(roles).map(role=>({value:role,label:readableName(role)}))} onChange={next=>{setTargetRole(next);setField(undefined);}}/></label><label>Field<Select aria-label="Rule action field" showSearch optionFilterProp="label" value={field} options={applicable.map(row=>({value:String(row.id),label:readableName(String(row.id))}))} onChange={setField}/></label></div>
  {field&&<ExpressionControl label="Rule state value" value={value} onChange={setValue}/>}
  <Button disabled={!name||!predicateId||pkgIndex===undefined||!targetRole||!field||value===undefined||Object.keys(roles).some(role=>!roleBindings[role])} onClick={()=>{try{const match=Object.fromEntries(Object.entries(roles).map(([role,type])=>[role,roleBindings[role]==='@type'?{is_a:type}:{entity:roleBindings[role]}]));onChange(appendPredicateRule(scenario,pkgIndex!,name,predicateId!,match,{kind:'set',entity:{$role:targetRole},field,value}));setName('');setError('');}catch(problem){setError(String(problem));}}}>Add rule to draft</Button>{error&&<Alert type="error" message={error}/>}<p className="guided-muted">The compiler checks that the behaviour plugin owns the chosen field and that its value matches the field schema.</p></Card>
  <Card title="Event chains"><Table size="small" rowKey="key" pagination={{pageSize:6}} dataSource={rows} columns={[{title:'Chain',dataIndex:'id',render:readableName},{title:'States',key:'states',render:(_,row)=>Array.isArray(row.chain.states)?row.chain.states.map((state:string)=><Tag key={state}>{readableName(state)}</Tag>):'No states'},{title:'Binding',key:'bindings',render:(_,row)=>row.bindings.map((binding:any)=><p key={binding.id} className="guided-binding">Auto-instantiated {binding.multiplicity==='once_per_task_episode'?'for each task episode':'for each matching entity'} · {Object.entries(mapping(binding.match)?binding.match:{}).map(([role,selector])=>`${readableName(role)}: ${mapping(selector)?readableName(String(selector.entity ?? selector.is_a ?? 'relation match')):'unsupported selector'}`).join(' · ')}</p>)}]} expandable={{expandedRowRender:row=><Details title={`${readableName(row.id)} chain`}><pre>{JSON.stringify(row.chain,null,2)}</pre></Details>}}/></Card>
  <Collapse className="guided-rules-editor" defaultActiveKey={['editor']} items={[{key:'editor',label:'State-machine graphs, transitions and actions',children:<BehavioursPanel {...common} initialTab="chains"/>}]}/>
  <Card title="Conflict rules & injection points">{inline.map(({pkg,index})=><div key={index}><h3>{readableName(String(pkg.id))}</h3><Table size="small" rowKey="id" pagination={false} dataSource={Array.isArray(pkg.conflicts)?pkg.conflicts:[]} columns={[{title:'Conflict rule',dataIndex:'id',render:readableName},{title:'Condition',dataIndex:'predicate',render:readableName},{title:'Event',dataIndex:'emits',render:readableName}]}/><h4>External events an operator can fire</h4><Table size="small" rowKey="id" pagination={false} dataSource={Array.isArray(pkg.injection_points)?pkg.injection_points:[]} columns={[{title:'Injection point',dataIndex:'id',render:readableName},{title:'Event',dataIndex:'emits',render:(id)=>id?readableName(id):'Typed command'},{title:'Payload fields',key:'payload',render:(_,point)=>{const schema=scenario.registry?.messages?.find((row:any)=>row.id===point.emits)?.schema;const resolved=typeof schema==='string'?scenario.registry?.schemas?.[schema]:schema;return mapping(resolved?.members)?Object.keys(resolved.members).map(readableName).join(', '):<Details title="Payload schema"><pre>{JSON.stringify(point.schema ?? schema ?? point,null,2)}</pre></Details>;}}]}/></div>)}</Card>
 </div>;
}
